### PR TITLE
Convert Physics automated tests in Sandbox/Utils suites to use prefab system

### PR DESCRIPTION
**Pull request by chiyenteng**
Converted the following Physics automated tests from **TestSuite_Sandbox/TestSuite_Utils**:
- Tests passed before/after conversion:
  - ScriptCanvas_GetCollisionNameReturnsName
  - ScriptCanvas_GetCollisionNameReturnsNothingWhenHasToggledLayer
- Tests failed before/after conversion:
  - test_physmaterial_editor (This test actually does not open any prefab level/file)

Also the following tests got removed from **TestSuite_Utils** since no actual test file/module exist:
- UtilTest_Tracer_PicksErrorsAndWarnings
- UtilTest_Managed_Files

Note: Only one test(test_FileManagement_FindingFiles) passed in **TestSuite_Utils** and it doesn't need to be converted. This test suite probably hasn't been maintained for quite some time.

Signed-off-by: chiyenteng <82238204+chiyenteng@users.noreply.github.com>

### CODE REVIEW

**Comment by greerdv** [comment]
LGTM. 

I think those two tests you removed from the suite do exist in https://github.com/o3de/o3de/tree/development/AutomatedTesting/Gem/PythonTests/Physics/utils but one appears to be a basically empty test which does nothing and so I see no problem in removing it. The other one seems to be verifying that errors and warnings are picked up. That does seem like it might be a useful test, but it could be restructured to not need any levels or script canvas assets and I wouldn't consider it as a physics test - it seems like more of a systems test to me. But perhaps a GHI should be created for the systems team to look at reinstating that test if they think it provides value?

**Review by greerdv — APPROVED** [review]

**Comment by chiyenteng** [comment]
> LGTM.
> 
> I think those two tests you removed from the suite do exist in https://github.com/o3de/o3de/tree/development/AutomatedTesting/Gem/PythonTests/Physics/utils but one appears to be a basically empty test which does nothing and so I see no problem in removing it. The other one seems to be verifying that errors and warnings are picked up. That does seem like it might be a useful test, but it could be restructured to not need any levels or script canvas assets and I wouldn't consider it as a physics test - it seems like more of a systems test to me. But perhaps a GHI should be created for the systems team to look at reinstating that test if they think it provides value?

That's fine with me. I will create a ticket for this concern. Thanks.

**Review by jckand-amzn — APPROVED** [review]
Looks good to me.

**Comment by chiyenteng** [comment]
> LGTM.
> 
> I think those two tests you removed from the suite do exist in https://github.com/o3de/o3de/tree/development/AutomatedTesting/Gem/PythonTests/Physics/utils but one appears to be a basically empty test which does nothing and so I see no problem in removing it. The other one seems to be verifying that errors and warnings are picked up. That does seem like it might be a useful test, but it could be restructured to not need any levels or script canvas assets and I wouldn't consider it as a physics test - it seems like more of a systems test to me. But perhaps a GHI should be created for the systems team to look at reinstating that test if they think it provides value?

GHI created: #8027

**Pull request merged**
