### PR TITLE
Update Mac OS icons with new logo

### LINKED ISSUE #9359: Mac OS Template icons have not been updated to use the new logo
**Describe the bug**
Mac OS Template icons have not been updated to use the new logo

**Steps to reproduce**
1. Download the latest development or stabilization installer.
2. Navigate to 

```
Templates\DefaultProject\Template\Resources\Platform\Mac\Images.xcassets\TestDPAppIcon.appiconset
```
and
```
Templates\MinimalProject\Template\Resources\Platform\Mac\Images.xcassets\TestDPAppIcon.appiconset
```
and
```
AutomatedTesting\Gem\Resources\MacLauncher\Images.xcassets\AppIcon.appiconset
```
and
```
o3de\Code\Editor\Platform\Mac\Images.xcassets\EditorAppIcon.appiconset
```

**Expected behavior**
Logos are updated.

**Actual behavior**
Old logo remains.

**Screenshots/Video**
image

**Found in Branch**
development@0dbd6f1c092475a655f38df4568b9b5f99b90daf

### PR DESCRIPTION
**Pull request by AMZN-daimini**
Signed-off-by: Danilo Aimini <82231674+AMZN-daimini@users.noreply.github.com>

Closes #9359

### CODE REVIEW

**Review by hultonha — APPROVED** [review]
Thanks for doing this!

**Review by gadams3 — APPROVED** [review]

**Review by amzn-sj — COMMENTED** [review]
I think these would also need to be replaced:
https://github.com/o3de/o3de/tree/development/Code/Tools/AssetProcessor/Platform/Mac/Images.xcassets

They're for the AssetProcessor

**Review by lumberyard-employee-dm — APPROVED** [review]

**Comment by AMZN-daimini** [comment]
> I think these would also need to be replaced: https://github.com/o3de/o3de/tree/development/Code/Tools/AssetProcessor/Platform/Mac/Images.xcassets
> 
> They're for the AssetProcessor

Thanks, fixed!

**Review by amzn-sj — APPROVED** [review]

**Comment by AMZN-daimini** [comment]
After feedback, we also changed the preview icons to remove the risk of triggering tridecaphobia.

**Before**
https://files.slack.com/files-pri/T015GUGD2V6-F03E7D65GCC/image.png

**After**
image

**Comment by tonybalandiuk** [comment]
Since this will be an exception, here's the tracking
- [ ] 1.    Owning SIG requests the exception, by a Sig Representative (Chair/co-chair) adding the PR to the exception requests queue board.
- [ ] 2.	 Unrelated SIG representative (chair/cochair) approves the exception, adding a comment indicating approval and the SIG they represent.
- [ ] 3.	UX SIG representative (chair/cochair) approves the exception, adding a comment indicating approval and the SIG they represent.
- [ ] 4.	Testing SIG representative (chair/cochair) approves the exception, adding a comment indicating approval and the SIG they represent.
- [ ] 5.	If all approvals are accepted exception PR is merged
- [ ] 6.	Merged PR is verified successful via testing. If Merged PR verification testing failed, consult reps from step 3-5 and discussion occurs on fixing the failure vs backing out change
- [ ] 7.	Exception is complete

**Comment by AMZN-daimini** [comment]
I was made aware of these default textures for Atom, so we've fixed these up too
image

**Comment by AMZN-Dk** [comment]
Approved from Testing SIG.

**Comment by lumberyard-employee-dm** [comment]
Approved on behalf of SIG-Core

**Review by lsemp3d — APPROVED** [review]
Approved on behalf of SIG-Content

**Comment by AMZN-daimini** [comment]
Got all approvals, merging this into stabilization/2205.

**Pull request merged**
