### PR TITLE
chore(EmotionFX): remove LegacyRender method and drop RenderPlugin and dependencies

### PR DESCRIPTION
**Pull request by pollend**
this is a continuation of the previous changes where I removed the Opengl view from EMotionFX. RenderOpenglPlugin inherited RenderPlugin so I removed that and all its dependencies. I can remove the Opengl plugin next after this set of changes. there are a couple other classes such as the manipulators that can be easily removed after this. 

ref: https://github.com/o3de/o3de/pull/9834

Signed-off-by: Michael Pollind <mpollind@gmail.com>

### CODE REVIEW

**Review by moraaar — APPROVED** [review]
LGTM. Thanks for cleaning up legacy code.

**Comment by hultonha** [comment]
Thanks for continuing this work @pollend, tagging @amzn-jillich and @amzn-rhhong to take a look too. Cheers!

**Review by hultonha — COMMENTED** [review]
Change looks good but I'd like @amzn-rhhong and/or @amzn-jillich to sign-off on this before we merge. Thanks!

**Review by cgalvan — APPROVED** [review]

**Comment by cgalvan** [comment]
@pollend  Got a compile error in AR
```
[2022-06-13T15:22:45.832Z] /data/workspace/o3de/Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/MainWindow.cpp:1099:24: error: no member named 'LogError' in namespace 'MCore'
[2022-06-13T15:22:45.832Z]                 MCore::LogError("Failed to create window using plugin '%s'", FromQtString(pluginName).c_str());
[2022-06-13T15:22:45.832Z]                 ~~~~~~~^
[2022-06-13T15:22:45.832Z] /data/workspace/o3de/Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/MainWindow.cpp:1278:20: error: no member named 'LogError' in namespace 'MCore'
[2022-06-13T15:22:45.832Z]             MCore::LogError("Could not load actor '%s'.", fileName);
[2022-06-13T15:22:45.832Z]             ~~~~~~~^
[2022-06-13T15:22:45.832Z] /data/workspace/o3de/Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/MainWindow.cpp:1884:20: error: no member named 'LogError' in namespace 'MCore'
[2022-06-13T15:22:45.832Z]             MCore::LogError("Failed to load layout from file '%s'", filename.c_str());
[2022-06-13T15:22:45.832Z]             ~~~~~~~^
[2022-06-13T15:22:45.832Z] /data/workspace/o3de/Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/MainWindow.cpp:1901:24: error: no member named 'LogError' in namespace 'MCore'
[2022-06-13T15:22:45.832Z]                 MCore::LogError("Failed to remove layout file '%s'", FromQtString(m_layoutFileBeingRemoved).c_str());
[2022-06-13T15:22:45.832Z]                 ~~~~~~~^
[2022-06-13T15:22:45.832Z] /data/workspace/o3de/Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/MainWindow.cpp:1908:24: error: no member named 'LogInfo' in namespace 'MCore'
[2022-06-13T15:22:45.832Z]                 MCore::LogInfo("Successfullly removed layout file '%s'", FromQtString(m_layoutFileBeingRemoved).c_str());
[2022-06-13T15:22:45.832Z]                 ~~~~~~~^
[2022-06-13T15:22:45.832Z] /data/workspace/o3de/Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/MainWindow.cpp:1978:20: error: no member named 'LogError' in namespace 'MCore'
[2022-06-13T15:22:45.832Z]             MCore::LogError("Failed to load layout from file '%s'", filename.c_str());
[2022-06-13T15:22:45.832Z]             ~~~~~~~^
[2022-06-13T15:22:45.832Z] /data/workspace/o3de/Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/MainWindow.cpp:1998:28: error: no member named 'LogError' in namespace 'MCore'
[2022-06-13T15:22:45.832Z]                     MCore::LogError(outResult.c_str());
[2022-06-13T15:22:45.832Z]                     ~~~~~~~^
[2022-06-13T15:22:45.832Z] /data/workspace/o3de/Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/MainWindow.cpp:2023:28: error: no member named 'LogError' in namespace 'MCore'
[2022-06-13T15:22:45.832Z]                     MCore::LogError(outResult.c_str());
[2022-06-13T15:22:45.832Z]                     ~~~~~~~^
[2022-06-13T15:22:45.832Z] /data/workspace/o3de/Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/MainWindow.cpp:2420:14: error: member access into incomplete type 'QDragEnterEvent'
[2022-06-13T15:22:45.832Z]         event->acceptProposedAction();
[2022-06-13T15:22:45.832Z]              ^
[2022-06-13T15:22:45.832Z] /data/workspace/3rdParty/packages/qt-5.15.2-rev8-linux/qt/include/QtWidgets/qwidget.h:84:7: note: forward declaration of 'QDragEnterEvent'
[2022-06-13T15:22:45.832Z] class QDragEnterEvent;
[2022-06-13T15:22:45.832Z]       ^
[2022-06-13T15:22:45.833Z] /data/workspace/o3de/Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/MainWindow.cpp:2446:42: error: member access into incomplete type 'QDropEvent'
[2022-06-13T15:22:45.833Z]         const QMimeData* mimeData = event->mimeData();
[2022-06-13T15:22:45.833Z]                                          ^
[2022-06-13T15:22:45.833Z] /data/workspace/3rdParty/packages/qt-5.15.2-rev8-linux/qt/include/QtWidgets/qwidget.h:87:7: note: forward declaration of 'QDropEvent'
[2022-06-13T15:22:45.833Z] class QDropEvent;
[2022-06-13T15:22:45.833Z]       ^
[2022-06-13T15:22:45.833Z] /data/workspace/o3de/Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/MainWindow.cpp:2461:35: error: member access into incomplete type 'QDropEvent'
[2022-06-13T15:22:45.833Z]         LoadFiles(fileNames, event->pos().x(), event->pos().y());
[2022-06-13T15:22:45.833Z]                                   ^
[2022-06-13T15:22:45.833Z] /data/workspace/3rdParty/packages/qt-5.15.2-rev8-linux/qt/include/QtWidgets/qwidget.h:87:7: note: forward declaration of 'QDropEvent'
[2022-06-13T15:22:45.833Z] class QDropEvent;
[2022-06-13T15:22:45.833Z]       ^
[2022-06-13T15:22:45.833Z] /data/workspace/o3de/Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/MainWindow.cpp:2461:53: error: member access into incomplete type 'QDropEvent'
[2022-06-13T15:22:45.833Z]         LoadFiles(fileNames, event->pos().x(), event->pos().y());
[2022-06-13T15:22:45.833Z]                                                     ^
[2022-06-13T15:22:45.833Z] /data/workspace/3rdParty/packages/qt-5.15.2-rev8-linux/qt/include/QtWidgets/qwidget.h:87:7: note: forward declaration of 'QDropEvent'
[2022-06-13T15:22:45.833Z] class QDropEvent;
[2022-06-13T15:22:45.833Z]       ^
[2022-06-13T15:22:45.833Z] /data/workspace/o3de/Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/MainWindow.cpp:2463:14: error: member access into incomplete type 'QDropEvent'
[2022-06-13T15:22:45.833Z]         event->acceptProposedAction();
[2022-06-13T15:22:45.833Z]              ^
[2022-06-13T15:22:45.833Z] /data/workspace/3rdParty/packages/qt-5.15.2-rev8-linux/qt/include/QtWidgets/qwidget.h:87:7: note: forward declaration of 'QDropEvent'
[2022-06-13T15:22:45.833Z] class QDropEvent;
[2022-06-13T15:22:45.833Z]       ^
[2022-06-13T15:22:45.833Z] /data/workspace/o3de/Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/MainWindow.cpp:2471:18: error: member access into incomplete type 'QCloseEvent'
[2022-06-13T15:22:45.833Z]             event->ignore();
[2022-06-13T15:22:45.833Z]                  ^
[2022-06-13T15:22:45.833Z] /data/workspace/3rdParty/packages/qt-5.15.2-rev8-linux/qt/include/QtWidgets/qwidget.h:80:7: note: forward declaration of 'QCloseEvent'
[2022-06-13T15:22:45.833Z] class QCloseEvent;
[2022-06-13T15:22:45.833Z]       ^
[2022-06-13T15:22:45.833Z] 14 errors generated.
```

**Comment by pollend** [comment]
looks like compiling with unity hide some errors ... I'll look at this later tonight.

**Comment by cgalvan** [comment]
@pollend Thanks, I've kicked off a new AR!

**Comment by hultonha** [comment]
Before anyone merges this it would be good to get confirmation from @amzn-rhhong and/or @amzn-jillich please. Thanks!

**Pull request merged**
