### PR TITLE
Default flag sytems to use TaskGraph

### PR DESCRIPTION
**Pull request by rgba16f**
Signed-off-by: rgba16f <82187279+rgba16f@users.noreply.github.com>

### CODE REVIEW

**Review by jeremyong-az — COMMENTED** [review]
Can we add an assert if we try to `Submit` an empty task graph? In case someone does, I think the `waitForCompletion` event can be left in a signaled state to avoid the bug you encountered here.

**Review by jeremyong-az — APPROVED** [review]

**Comment by rgba16f** [comment]
> Can we add an assert if we try to `Submit` an empty task graph? In case someone does, I think the `waitForCompletion` event can be left in a signaled state to avoid the bug you encountered here.

Assert added to TaskGraph::Submit

**Review by amzn-jillich — APPROVED** [review]

**Review by AMZN-koppersr — APPROVED** [review]

**Comment by jeremyong-az** [comment]
Also suggest making the task graph + wait no-op if a submit/wait actually is performed on an empty graph.

**Comment by rgba16f** [comment]
This finally passed AR, I'll submit tomorrow morning. 
I'll add a jira for Jeremy's suggestion to deal with an empty task graph and wait.

**Pull request merged**
