### PR TITLE
Replace Editor assets to reflect logo changes.

### PR DESCRIPTION
**Pull request by AMZN-daimini**
### Editor
image
image
image
image
image
image

### Project Manager
image
image
image

### Installer
image

### CODE REVIEW

**Review by alexmontAmazon — APPROVED** [review]
screenshots look good, .ui file is sane... not sure what else to pick at, so... approved ;)

**Review by AMZN-nggieber — APPROVED** [review]
Didn't know git had diff support for svgs. Good job showing all the screenshots!

**Review by AMZN-Phil — APPROVED** [review]

**Review by cgalvan — APPROVED** [review]

**Review by Kadino — APPROVED** [review]
Looks like sig-testing was added as an icon exists in the iOS portion of AzTestRunner. Looks good!

**Review by rainbj — APPROVED** [review]
Approved visual changes.

**Comment by tonybalandiuk** [comment]
**Exception Tracking**

- [ ] 1.    Owning SIG requests the exception, by a Sig Representative (Chair/co-chair) adding the PR to the exception requests queue board.
- [ ] 2.	 Unrelated SIG representative (chair/cochair) approves the exception, adding a comment indicating approval and the SIG they represent.
- [ ] 3.	UX SIG representative (chair/cochair) approves the exception, adding a comment indicating approval and the SIG they represent.
- [ ] 4.	Testing SIG representative (chair/cochair) approves the exception, adding a comment indicating approval and the SIG they represent.
- [ ] 5.	If all approvals are accepted exception PR is merged
- [ ] 6.	Merged PR is verified successful via testing. If Merged PR verification testing failed, consult reps from step 3-5 and discussion occurs on fixing the failure vs backing out change
- [ ] 7.	Exception is complete

**Review by tonybalandiuk — APPROVED** [review]
On behalf of SIG-Release these are approved

**Comment by tonybalandiuk** [comment]
We are on Step 5 now. This is OK to merge

**Comment by AMZN-daimini** [comment]
Given the extent of the change (only assets and minor .ui file changes), I am merging it now despite today being a Friday. I will stay around to verify the next stabilization build is green just in case.

**Comment by LB-ArturZieba** [comment]
All mentioned O3DE logos/icons were verified on the Stabilization_2205 (32e9143) build to display the new design. It should be noted however, that due to https://github.com/o3de/o3de/issues/7314, the Edit Platform Settings Android/iOS Icons/Splashscreens can only be viewed on the AutomatedTesting project.

**Pull request merged**
