### PR TITLE
feat(ScriptCanvas): add vector2/3/4 and color to multiply node

### PR DESCRIPTION
**Pull request by pollend**
Signed-off-by: Michael Pollind <mpollind@gmail.com>

## What does this PR do?

adds support to vector2/3/4 and color to multiply node. 

## How was this PR tested?

add script canvas unit test for multiply just not sure how to run the test for the script canvas

### CODE REVIEW

**Review by lsemp3d — APPROVED** [review]

**Review by hultonha — APPROVED** [review]

**Review by cgalvan — APPROVED** [review]

**Comment by cgalvan** [comment]
@pollend Can you pull latest `development` to your branch and then re-push? There's a unit test failure in `AzCore` that shouldn't be caused by your change.

**Comment by pollend** [comment]
> @pollend Can you pull latest `development` to your branch and then re-push? There's a unit test failure in `AzCore` that shouldn't be caused by your change.

how do I run the unit test I added?

**Comment by cgalvan** [comment]
> @cgalvan any clue how I run the unit test I added?

Sorry I just meant I think the `development` your branch was based on already had an un-related unit test failure, I think yours should be OK

**Comment by pollend** [comment]
> > @cgalvan any clue how I run the unit test I added?
> 
> Sorry I just meant I think the `development` your branch was based on already had an un-related unit test failure, I think yours should be OK

how do I run the script canvas test?

> > @cgalvan any clue how I run the unit test I added?
> 
> Sorry I just meant I think the `development` your branch was based on already had an un-related unit test failure, I think yours should be OK

how I run this unit test to see if my changes are correct: [ScriptCanvasTesting/Assets/ScriptCanvas/UnitTests/LY_SC_UnitTest_OperatorMul.scriptcanvas](https://github.com/o3de/o3de/pull/11284/files#diff-c63e058209c78a77686d8e215d5ef7dc9b2e5b2aa677df6dcb997d10e0b29c42)

**Comment by lsemp3d** [comment]
> > > @cgalvan any clue how I run the unit test I added?
> > 
> > 
> > Sorry I just meant I think the `development` your branch was based on already had an un-related unit test failure, I think yours should be OK
> 
> how do I run the script canvas test?
> 
> > > @cgalvan any clue how I run the unit test I added?
> > 
> > 
> > Sorry I just meant I think the `development` your branch was based on already had an un-related unit test failure, I think yours should be OK
> 
> how I run this unit test to see if my changes are correct: [ScriptCanvasTesting/Assets/ScriptCanvas/UnitTests/LY_SC_UnitTest_OperatorMul.scriptcanvas](https://github.com/o3de/o3de/pull/11284/files#diff-c63e058209c78a77686d8e215d5ef7dc9b2e5b2aa677df6dcb997d10e0b29c42)

@carlitosan can you provide instructions for running SC unit tests? thanks!

**Pull request merged**
