### PR TITLE
Update MSVC to use new lambda processing

### PR DESCRIPTION
**Pull request by hultonha**
This fixes a crash that would be caused by MSVC not correctly parsing lambdas

See this link for more details - https://developercommunity.visualstudio.com/t/A-lambda-that-binds-the-this-pointer-w/1467873

### CODE REVIEW

**Comment by lawsonamzn** [comment]
Is this a MSVC problem only (ie, the rest would work just fine in these cases?) 
Or are we opening the floodgates to stuff working on MSVC but not on other platforms?

**Review by lumberyard-employee-dm — APPROVED** [review]
This is an MSVC compiler bug workaround

**Comment by hultonha** [comment]
> Is this a MSVC problem only (ie, the rest would work just fine in these cases?)
> Or are we opening the floodgates to stuff working on MSVC but not on other platforms?

Yup this is just an MSVC bug. Behavior works fine on GCC/Clang. See this reply from MSFT

> Hi: this is due to a limitation of the old/original lambda processing code: it is token based and hence has trouble detecting when exactly it needs to capture ‘this’. To fix this issue you should use the new lambda processor: to do this you can add ‘/Zc:lambda’ to the command-line (or you can use '/std:c++latest which implies ‘/Zc:lambda’).
> Thanks
> Jonathan Caves

https://developercommunity.visualstudio.com/t/A-lambda-that-binds-the-this-pointer-w/1467873

**Review by amznestebanpapp — APPROVED** [review]

**Comment by hultonha** [comment]
The most recent change (f8a8046) is to workaround a bug in the MSVC compiler when using the new lambda processing (it doesn't play nice with structured bindings unfortunately 🙁 It looks like this is actually fixed, but only very recently, so some of the build machines don't have this version of the compiler, so I'm removing the use of structured bindings for now.

**Comment by amznestebanpapp** [comment]
> The most recent change ([f8a8046](https://github.com/o3de/o3de/commit/f8a80468ab27e34edc0d75d475da6928a645a8ec)) is to workaround a bug in the MSVC compiler when using the new lambda processing (it doesn't play nice with structured bindings unfortunately 🙁). It looks like this is actually fixed, but only very recently, so some of the build machines don't have this version of the compiler, so I'm removing the use of structured bindings for now.

All build machines should have the same version of the compiler, they are spawned out of the same AMI. There is currently an issue with the GPU ones that is being fixed. 
If you know the version where it was fixed, we could bump the version we use in Jenkins and stablish that one as the minimal version to use for O3DE.
However, if this fix avoids it, better. Just concerned about someone else falling into the same issue, seems not obvious.

**Comment by hultonha** [comment]
> > The most recent change ([f8a8046](https://github.com/o3de/o3de/commit/f8a80468ab27e34edc0d75d475da6928a645a8ec)) is to workaround a bug in the MSVC compiler when using the new lambda processing (it doesn't play nice with structured bindings unfortunately 🙁). It looks like this is actually fixed, but only very recently, so some of the build machines don't have this version of the compiler, so I'm removing the use of structured bindings for now.
> 
> All build machines should have the same version of the compiler, they are spawned out of the same AMI. There is currently an issue with the GPU ones that is being fixed.
> If you know the version where it was fixed, we could bump the version we use in Jenkins and stablish that one as the minimal version to use for O3DE.
> However, if this fix avoids it, better. Just concerned about someone else falling into the same issue, seems non obvious.

Okay understood, I think it's just that I must have locally got a later version of VS that our minimal supported one which is why it worked for me and not the build machines. There was only one occurrence of this pattern (a structured binding in a lambda) so hopefully shouldn't crop up again anytime soon and with a bit of luck when the build machines do get upgraded it'll stop being an issue. Thanks!

**Pull request merged**
