### PR TITLE
Missing xcassets

### PR DESCRIPTION
**Pull request by amzn-mgwynn**
IOS nightly builds were failing due to missing Images.xcassets in AutomatedTesting project. Some assets were removed but contents.json files were not updated to reflect changes, causing a failure in automated builds.

### CODE REVIEW

**Review by spham-amzn — APPROVED** [review]

**Review by amzn-sj — COMMENTED** [review]
This change is going to break the window size. iOS was using the size of the launch image to determine screen bounds(see: #1625). If we're ok with that, it's fine. But we probably need to notify QA/anyone trying to run this on iOS that this is a known issue.

**Comment by amzn-mgwynn** [comment]
> This change is going to break the window size. iOS was using the size of the launch image to determine screen bounds(see: #1625). If we're ok with that, it's fine. But we probably need to notify QA/anyone trying to run this on iOS that this is a known issue.

Those images don't exist to be used anyways. The resolutions removed (1125x2436, 2436x1125, 1242x2208, 2208x1242, 750x1134) don't have corresponding assets in AutomatedTesting/Gem/Resources/IOSLauncher/Images.xcassets/LaunchImage.launchimage

The available resolutions for the launch image are 768x1024, 1024x768, 1536x2048, 2048x1536, 640x960 and 640x1136

**Comment by amzn-sj** [comment]
> > This change is going to break the window size. iOS was using the size of the launch image to determine screen bounds(see: #1625). If we're ok with that, it's fine. But we probably need to notify QA/anyone trying to run this on iOS that this is a known issue.
> 
> Those images don't exist to be used anyways. The resolutions removed (1125x2436, 2436x1125, 1242x2208, 2208x1242, 750x1134) don't have corresponding assets in AutomatedTesting/Gem/Resources/IOSLauncher/Images.xcassets/LaunchImage.launchimage
> 
> The available resolutions for the launch image are 768x1024, 1024x768, 1536x2048, 2048x1536, 640x960 and 640x1136

I see. Looks like it was broken in this commit: https://github.com/o3de/o3de/commit/635473e5cf9053fbb1e16e0b561452b6d2b29ba8
Not sure what that was addressing but it looks like it reverted my changes and deleted a bunch of files.

**Review by amzn-sj — APPROVED** [review]
Since this is resulting in a build error, I think we can check this in to fix the issue. Another issue can be opened if window size becomes an issue since this *only affects AutomatedTesting* project.

**Pull request merged**
