### PR TITLE
Wind Info

### PR DESCRIPTION
**Pull request by tjmgd**
Notify relative component to acquire wind information when the tag of global wind and local wind in PhysX configuration changes.

### CODE REVIEW

**Comment by AlexOteiza** [comment]
Can you explain a little bit how this change works? Thanks a lot!

**Comment by MoMoPF** [comment]
> Can you explain a little bit how this change works? Thanks a lot!

When the global/local wind tag in configuration is changed, the **WindProvider::EntityGroupHandler** will be recreated instead of the old one in wind provider. However, relative entity which is relying on the wind provider to get velocity will be delete form  the member **m_entities**  of the old **EntityGroupHandler**(This EntityGroupHandler was deleted just now). This is the reason that once we change the tag in configuration, whatever we do with the tag, it won't affect relative entity  because the entity is not in the **m_entities**.
So the change makes sure that if an **EntityGroupHandler** is created, OnTick() will be invoked once, which sends a global notification for the global wind or checks the entity in the AABB for the local wind.

PS: This commit can solve the problem about global wind completely and the problem about local wind partly. To deal with the local wind, please check this commit: https://github.com/o3de/o3de/pull/6505

**Review by lawsonamzn — APPROVED** [review]
Analysis: 
The EntityGroupHandler's purpose is to call its m_changeCallback function whenever something important changes such as the entities providing wind, their AABBs or their force values.

So it listens for those events and sets m_changed to true whenever something significant changes.

Its tick function checks if m_changed is true, calls the callback, and sets m_changed to false.

This means that if there are no entities that satisfy it (for example, no entities providing wind tags), it will never call its callback.

This change makes it be guaranteed to call its callback at least once (on the next tick) regardless of whether it has any entities associated with it providing it bounding volumes.

**Review by AlexOteiza — APPROVED** [review]

**Review by SergeyAMZN — APPROVED** [review]

**Comment by greerdv** [comment]
Hi @tjmgd, a bunch of people were off for Christmas holidays, so apologies that this has been left for so long.

Could you please do a merge from development into your branch? The change can't be submitted until it goes through the CI/CD system and that's failing at the moment because the branch hasn't been updated from development for a while.

After you do that I can run it through the CI/CD again and get it submitted.

Apologies again for the delay.

**Comment by tjmgd** [comment]
> Hi @tjmgd, a bunch of people were off for Christmas holidays, so apologies that this has been left for so long.
> 
> Could you please do a merge from development into your branch? The change can't be submitted until it goes through the CI/CD system and that's failing at the moment because the branch hasn't been updated from development for a while.
> 
> After you do that I can run it through the CI/CD again and get it submitted.
> 
> Apologies again for the delay

**Pull request merged**
