### PR TITLE
Make asset_profile_nounity non-blocking

### PR DESCRIPTION
**Pull request by shirangj**
Signed-off-by: Shirang Jia <shiranj@amazon.com>

### CODE REVIEW

**Review by galibzon — APPROVED** [review]

**Comment by lumberyard-employee-dm** [comment]
Does this mean that other linux jobs can run parallel aith thw asset_profile_nounity job?

**Comment by shirangj** [comment]
> 

No, they will still run sequentially, but Assets step failure won't block other steps after. You can see it in https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/PR-8832/3/pipeline

**Review by amzn-changml — APPROVED** [review]
I'm fine with the change, but we are, of course, allowing a failure to bypass AR. Github will still mark this check as failure for PRs, however. 

For it to pass PR checks, the build has to be successful, marked as successful (even with the failure), or overridden by a maintainer. We do need contributors to be aware of the state we choose to allow, even if it's short term.

**Comment by shirangj** [comment]
> I'm fine with the change, but we are, of course, allowing a failure to bypass AR. Github will still mark this check as failure for PRs, however.
> 
> For it to pass PR checks, the build has to be successful, marked as successful (even with the failure), or overridden by a maintainer. We do need contributors to be aware of the state we choose to allow, even if it's short term.

Yeah, failures in non-blocking step will mark the build as unstable and PR status check rule only accept successful build, we will send out an email to let everyone know the override workflow.

**Review by brianherrera — APPROVED** [review]

**Comment by brianherrera** [comment]
> > I'm fine with the change, but we are, of course, allowing a failure to bypass AR. Github will still mark this check as failure for PRs, however.
> > For it to pass PR checks, the build has to be successful, marked as successful (even with the failure), or overridden by a maintainer. We do need contributors to be aware of the state we choose to allow, even if it's short term.
> 
> Yeah, failures in non-blocking step will mark the build as unstable and PR status check rule only accept successful build, we will send out an email to let everyone know the override workflow.

Agreed. I prefer the override workflow, so that a maintainer will have to acknowledge the build status. This prevents us from ignoring the failures entirely.

**Pull request merged**
