### PR TITLE
refactor(Lua Editor): consolidate LUAEditorPlainTextEdit

### PR DESCRIPTION
**Pull request by pollend**
Signed-off-by: Michael Pollind <mpollind@gmail.com>

## What does this PR do?

this AzToolsFramework::PlainTextEdit is only used with this LUAEditorPlainTextEdit. I just consolidated the class under one concrete type. A lot of the implementation details seems pretty exclusive to  LUAEditorPlainTextEdit so it seems like a pretty straightforward change to do so. Would be pretty easy to split these back up if there is a strong need else I think this should make the code easier to work with. 

## How was this PR tested?

I made some changes to migrate a lot of the existing signals to method pointers so any missing signals should of been caught during compile time. verify that the lua editor is working.

### CODE REVIEW

**Review by cgalvan — APPROVED** [review]
I think you're right I'm not sure how much value it offered as a generic class, and as you pointed out it hadn't been used yet. We can always bring it back if needed!

**Comment by cgalvan** [comment]
@pollend Got a few compile errors on the AR run:

```
[2022-09-27T17:32:11.999Z] In file included from /data/workspace/o3de/Code/Tools/LuaIDE/Source/LUA/LUAEditorFoldingWidget.cpp:9:
[2022-09-27T17:32:11.999Z] In file included from /data/workspace/o3de/Code/Tools/LuaIDE/Source/LUA/LUAEditorFoldingWidget.hxx:13:
[2022-09-27T17:32:11.999Z] /data/workspace/o3de/Code/Tools/LuaIDE/./Source/LUA/LUAEditorPlainTextEdit.hxx:25:56: error: no type named 'SystemAllocator' in namespace 'AZ'
[2022-09-27T17:32:11.999Z]         AZ_CLASS_ALLOCATOR(LUAEditorPlainTextEdit, AZ::SystemAllocator, 0);
[2022-09-27T17:32:11.999Z]                                                    ~~~~^
[2022-09-27T17:32:11.999Z] /data/workspace/o3de/Code/Tools/LuaIDE/./Source/LUA/LUAEditorPlainTextEdit.hxx:25:73: error: expected parameter declarator
[2022-09-27T17:32:11.999Z]         AZ_CLASS_ALLOCATOR(LUAEditorPlainTextEdit, AZ::SystemAllocator, 0);
[2022-09-27T17:32:11.999Z]                                                                         ^
[2022-09-27T17:32:11.999Z] /data/workspace/o3de/Code/Tools/LuaIDE/./Source/LUA/LUAEditorPlainTextEdit.hxx:25:73: error: expected ')'
[2022-09-27T17:32:11.999Z] /data/workspace/o3de/Code/Tools/LuaIDE/./Source/LUA/LUAEditorPlainTextEdit.hxx:25:27: note: to match this '('
[2022-09-27T17:32:11.999Z]         AZ_CLASS_ALLOCATOR(LUAEditorPlainTextEdit, AZ::SystemAllocator, 0);
[2022-09-27T17:32:11.999Z]                           ^
[2022-09-27T17:32:11.999Z] /data/workspace/o3de/Code/Tools/LuaIDE/./Source/LUA/LUAEditorPlainTextEdit.hxx:25:9: error: C++ requires a type specifier for all declarations
[2022-09-27T17:32:11.999Z]         AZ_CLASS_ALLOCATOR(LUAEditorPlainTextEdit, AZ::SystemAllocator, 0);
[2022-09-27T17:32:11.999Z]         ^
[2022-09-27T17:32:11.999Z] In file included from /data/workspace/o3de/Code/Tools/LuaIDE/Source/LUA/LUAEditorFoldingWidget.cpp:9:
[2022-09-27T17:32:11.999Z] /data/workspace/o3de/Code/Tools/LuaIDE/Source/LUA/LUAEditorFoldingWidget.hxx:27:47: error: no type named 'SystemAllocator' in namespace 'AZ'
[2022-09-27T17:32:11.999Z]         AZ_CLASS_ALLOCATOR(FoldingWidget, AZ::SystemAllocator, 0);
[2022-09-27T17:32:11.999Z]                                           ~~~~^
[2022-09-27T17:32:11.999Z] /data/workspace/o3de/Code/Tools/LuaIDE/Source/LUA/LUAEditorFoldingWidget.hxx:27:64: error: expected parameter declarator
[2022-09-27T17:32:11.999Z]         AZ_CLASS_ALLOCATOR(FoldingWidget, AZ::SystemAllocator, 0);
[2022-09-27T17:32:11.999Z]                                                                ^
[2022-09-27T17:32:11.999Z] /data/workspace/o3de/Code/Tools/LuaIDE/Source/LUA/LUAEditorFoldingWidget.hxx:27:64: error: expected ')'
[2022-09-27T17:32:11.999Z] /data/workspace/o3de/Code/Tools/LuaIDE/Source/LUA/LUAEditorFoldingWidget.hxx:27:27: note: to match this '('
[2022-09-27T17:32:11.999Z]         AZ_CLASS_ALLOCATOR(FoldingWidget, AZ::SystemAllocator, 0);
[2022-09-27T17:32:11.999Z]                           ^
[2022-09-27T17:32:11.999Z] /data/workspace/o3de/Code/Tools/LuaIDE/Source/LUA/LUAEditorFoldingWidget.hxx:27:9: error: C++ requires a type specifier for all declarations
[2022-09-27T17:32:11.999Z]         AZ_CLASS_ALLOCATOR(FoldingWidget, AZ::SystemAllocator, 0);
[2022-09-27T17:32:11.999Z]         ^
[2022-09-27T17:32:11.999Z] 8 errors generated.
```

**Comment by pollend** [comment]
Sounds like I'm missing an include. Looks like unity build is hiding my build problem.

**Comment by cgalvan** [comment]
Thanks @pollend  I've kicked off a new AR build

**Review by gadams3 — APPROVED** [review]
We should look into making this more generic. I recently had a need for a plain text editor for material canvas shader code snippets. It would be useful to have a standard control, with standard styling and features for editing “code”.

**Pull request merged**
