### PR TITLE
Show link to log while building in Project Manager.

### PR DESCRIPTION
**Pull request by AMZN-Phil**

### CODE REVIEW

**Review by AMZN-nggieber — COMMENTED** [review]
Can I get a preview image?

**Comment by AMZN-Phil** [comment]
BuildShowLogs

**Comment by AMZN-alexpete** [comment]
Can we move the text to be just below the "Building Project..." text?  And, if it's simple to do, I'd make the "Click to" text darker - like a light grey.

**Review by AMZN-nggieber — CHANGES_REQUESTED** [review]
Can you horizontally center the "Click to View Logs" text?

**Comment by AMZN-Phil** [comment]
Updated layout:
BuildShowLogs

**Review by AMZN-nggieber — APPROVED** [review]

**Review by AMZN-ScottR — APPROVED** [review]

**Review by AMZN-alexpete — APPROVED** [review]

**Pull request merged**
