### PR TITLE
Unbatching EditorTests to execute as EditorSingleTests

### PR DESCRIPTION
**Pull request by jckand-amzn**
## What does this PR do?

Moves all current Main suite Editor tests to execute as EditorSingleTest. Removing the batching of tests due to intermittent failures in PR AR runs:

https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/PR-10387/1/pipeline/624
https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/PR-10323/9/pipeline/624/

## How was this PR tested?

Tested EditorTests_Main locally--all tests passed. Execution time is slightly higher than when run as batched, so tests may need to be moved to the Periodic suite to reduce runtime in another PR.

### CODE REVIEW

**Review by smurly — APPROVED** [review]

**Review by cgalvan — APPROVED** [review]

**Review by Kadino — APPROVED** [review]
This represents a significantly painful drift away from performance, due to poor editor stability. Unfortunate that both parallel and batch execution are no longer trusted.

**Comment by Kadino** [comment]
I expect this change will increase test execution duration by around 3 minutes. If all modules follow this path, it will quickly require moving tests from AR and into periodic (non-gated) execution.

**Comment by jckand-amzn** [comment]
> I expect this change will increase test execution duration by around 3 minutes. If all modules follow this path, it will quickly require moving tests from AR and into periodic (non-gated) execution.

Unfortunately, I believe it will. Luckily, at this point, out of all the tests I manage, this is the only suite that has so far required this. I think it's likely due to the UI interactions performed via PySide in the tests, however they were all running consistently well for several months, so I'm not entirely sure what's changed recently that's introduced the instability.

**Comment by jckand-amzn** [comment]
> > I expect this change will increase test execution duration by around 3 minutes. If all modules follow this path, it will quickly require moving tests from AR and into periodic (non-gated) execution.
> 
> Unfortunately, I believe it will. Luckily, at this point, out of all the tests I manage, this is the only suite that has so far required this. I think it's likely due to the UI interactions performed via PySide in the tests, however they were all running consistently well for several months, so I'm not entirely sure what's changed recently that's introduced the instability.

Changes have now passed PR AR, and the increase in time is noticeable, but not alarmingly so:

```
Mostly Batched:

[2022-06-28T21:58:07.135Z] 135/138 Test #185: AutomatedTesting::EditorTests_Main.main::TEST_RUN ........................   Passed  150.08 sec


All EditorSingleTest:
[2022-06-28T22:51:40.651Z] 135/138 Test #185: AutomatedTesting::EditorTests_Main.main::TEST_RUN ........................   Passed  176.99 sec
```

The EditorTests suite is kind of an odd duck in that there are multiple test classes in TestSuite_Main due to different Editor flags needing to be set for different kinds of tests, so it didn't benefit as much from EditorSharedTest as some other suites.

**Review by moraaar — APPROVED** [review]

**Pull request merged**
