### PR TITLE
Changed one of AreaLightBus's SetIntensity Methods to a Different Name

### PR DESCRIPTION
**Pull request by TheOneAbis**
## What does this PR do?

Changed to SetIntensityAndMode. O3DE's EBus system does not work with methods that have multiple overloads, so either we would need to change the EBus system to work with multiple overloads or change the Area Light Bus to not have multiple overloads of a single method. I went with the latter, as it's an infinitely easier change.

I also took the liberty to add this as an extra method with tooltips for Script Canvas, as it did not exist as a proper script canvas node yet.

Deprecates [issue#16553](https://github.com/o3de/o3de/issues/16553)

_Please describe your PR. For a bug fix, what was the old behavior, what is the new behavior?_

Old behavior: Could not invoke a bus call to SetIntensity(), as a compilation error would occur upon calling Event() saying no instance of overloaded function matches the argument list, then lists the SetIntensity method as an unknown type, as shown below:

image

New Behavior: Can now explicitely call either SetIntensity or SetIntensityAndMode without issue. Furthermore, this second method is also reflected into Script Canvas now (previously, Script canvas only has the version of SetIntensity that only accepted the intensity, but no intensity mpde).

## How was this PR tested?

Attempting to invoke a bus event with this method. If no compilation errors and the method itself does as expected, test is successful. I went into a scene, added an entity with a light component, and added a script that uses SetIntensityAndMode to set the light to something obviously different (like 500 lumens of 500 candela).

### CODE REVIEW

**Review by gadams3 — APPROVED** [review]

**Review by phuchau1989 — APPROVED** [review]

**Comment by TheOneAbis** [comment]
hello, any updates on this PR?

**Review by cgalvan — APPROVED** [review]

**Comment by cgalvan** [comment]
@TheOneAbis There's an AR issue in your branch that is unrelated to your changes. Can you please pull in latest development into your branch so I can re-run AR? Here are the steps to do so if you are unfamiliar:

https://docs.o3de.org/docs/contributing/to-code/git-workflow/#ongoing-git-workflow-steps

Thanks!

**Comment by TheOneAbis** [comment]
thanks for notifying me. I have merged latest changes into my branch, let me know if there's anything else I need to fix thanks

**Comment by cgalvan** [comment]
@TheOneAbis Thanks! I've started a new AR run now, I'll let you know the results!

**Comment by TheOneAbis** [comment]
I appreciate it!

**Pull request merged**
