### PR TITLE
bugfix: fix missing icon for whitebox plugin

### PR DESCRIPTION
**Pull request by pollend**
didn't get the chance to build this but I'm pretty sure that its a problem with the case of the filepath. Couldn't figure out why the white box module wasn't available in my workspace. I think I forgot to rebuild the project. I'll try to validate it tonight haven't rebuilt my workspace in some time.

https://github.com/o3de/o3de/issues/9051

### CODE REVIEW

**Review by gadams3 — APPROVED** [review]

**Review by hultonha — APPROVED** [review]
Good spot @pollend! The dreaded path case sensitivity on Linux strikes again 😅 The other way to solve this might be to update the path in the source code that's loading the files (to match the casing), but this also makes sense. This looks safe and solid to me, I'll look at getting a build kicked off shortly 👍 (though we might have to wait a little while as I think development might be red at the moment)

**Comment by pollend** [comment]
just verified that this fixes the problem:

image

**Comment by hultonha** [comment]
Thanks for the updated screenshot @pollend! 👍

**Comment by cgalvan** [comment]
Thanks for fixing this! I've kicked off an AR build.

**Comment by cgalvan** [comment]
I've gotten the same AR failure twice, can you try pulling in the latest `development` and I can retry?

**Comment by pollend** [comment]
@cgalvan I rebased it

**Comment by pollend** [comment]
> > Ar still seems to be failing?
> 
> We're seeing some instability in the tests of late, the best thing to do is create an AR issue here - https://github.com/o3de/o3de/issues/new?assignees=&labels=needs-triage%2Ckind%2Fbug%2Ckind%2Fautomation&template=ar_bug_report.md&title=AR+Bug+Report (here's an example of one I created earlier - #9304, #9301, #9248 etc...). It'd be worth checking if yours looks to be something similar, we're working on getting it root-caused and fixed ASAP.

sounds good, I'll take a look later tonight.

**Comment by pollend** [comment]
looks like the Ar passed @hultonha I'll still open up that ticket

**Pull request merged**
