### PR TITLE
Fixing the failing test_Material_DefaultLibraryUpdatedAcrossLevels tests in Physics TestSuite_Periodic 

### PR DESCRIPTION
**Pull request by FuzzyCarterAWS**
`os.getcwd()` was returning the _build\*\bin\profile_ directory causing the tests to blow up.

Sanitized CWD call to insure that it's returning the O3DE root directory by passing `os.getcwd()` through the LyTestTools Abstract Resource Locator's `_find_engine_root()` helper.

Addtionally, these tests have been updated to include the Slice → Prefab conversion.

Note: These tests will fail if we ever moved AutomatedTesting outside of the O3DE repo into its own project repository. If this every happens, there needs to be a strike team effort to rewrite a massive swath of tests to support the `AbstractResourceLocator` object so the `project()` method can be used to return the project path no matter where it's located. This effort was not used since it would require a larger rewrite of these tests.

Testing Performed:
Ran tests locally through pycharm and CLI and they are now passing.

Signed-off-by: Fuzzy Carter <jscar@amazon.com>

### CODE REVIEW

**Review by chiyenteng — COMMENTED** [review]
Can you also include slice/prefab automated test conversion as well?

**Review by Kadino — APPROVED** [review]
Interesting, ly_test_tools had an assumption that the workspace object would be used but it is not available to tests using EditorPythonBindings / EditorTest.

This is a valid reuse of an existing tool, which could be made easier if the functionality was attached to a simpler library in LyTT. Agree that it should be handled for a generic project, which likely requires looking at the project manifest. Cut this as a feature request: https://github.com/o3de/o3de/issues/8051

**Review by smurly — APPROVED** [review]

**Review by chiyenteng — APPROVED** [review]

**Comment by FuzzyCarterAWS** [comment]
Updated to include Prefab conversion.

**Review by Kadino — APPROVED** [review]

**Comment by hultonha** [comment]
Awesome find @FuzzyCarterAWS! 😄 Thanks for fixing this!

**Pull request merged**
