### PR TITLE
Make RPI pass template pointed object const

### PR DESCRIPTION
**Pull request by Bindless-Chicken**
**Description**
This PR changes the `GetPassTemplate` function from the pass library and pass system so that they return const pointer to const objects. Previously the returned object wasn't const allowing direct modification to the underlying template in the pass library.  
**This change will introduce a breaking change as all the call to `GetPassTemplate` will need to update their returned object signature to `const AZStd::shared_ptr<const RPI::PassTemplate>`.**

This PR also introduces the `HasTemplate` function in the pass system to expose the function with the same name in the pass library. This is intended as a replacement to the following pattern, that introduced a bump in the shared ptr counter.
```
const AZStd::shared_ptr<const RPI::PassTemplate> rtPassTemplate = RPI::PassSystemInterface::Get()->GetPassTemplate(renderPassTemplateName);
if (rtPassTemplate == nullptr)
{
}
```
That can now be expressed as:
```
if (!RPI::PassSystemInterface::Get()->HasTemplate(renderPassTemplateName))
{
}
```

**Tests**
- Ran the  ASV automated testing _fullsuite with DX12 on windows - No issue reported
- Ran the editor in various scenario

### CODE REVIEW

**Comment by Bindless-Chicken** [comment]
You can find the required changes to ASV here: https://github.com/o3de/o3de-atom-sampleviewer/pull/348
_**All test were passed successfully with the above changes applied.**_

**Comment by rgba16f** [comment]
Please attach the output of a successful run of AtomSampleViewers Automated testing _fullsuite script

**Comment by Bindless-Chicken** [comment]
> Please attach the output of a successful run of AtomSampleViewers Automated testing _fullsuite script
See my previous message, all the tests ran successfully with the PR mentioned ;)

**Comment by rgba16f** [comment]
It is up for debate what the current standard is :)
Currently it's between these 2 approaches -
1) a screen cap of the test results like here - https://github.com/o3de/o3de-atom-sampleviewer/pull/345
2) a testing section listing what you tested like here - https://github.com/o3de/o3de/pull/7762

I'd say you are close to meeting 2, All tests is a little bit of an ambiguous statement. All tests in the fullsuite script passed on DX12 is enough for now.

**Comment by Bindless-Chicken** [comment]
Point taken! I couldn't remember what we had agreed during the last sig meeting.
I'll edit the original message, but it could be helpful to have a template for PR (same we have for issues), where contributors could tick which test they ran, and listing the requirements per different areas. I'll raise the topic on the discord.

**Review by rgba16f — APPROVED** [review]
I think this could be a lot neater if you added a typedef for 
`AZStd::shared_ptr<const RPI::PassTemplate>`
such as 
`using PassTemplatePtr = AZStd::shared_ptr<const RPI::PassTemplate>;`
There are several examples where we do that already in Atom.

**Comment by Bindless-Chicken** [comment]
I personally dislike this pattern as it hides the actual implementation details and can make things a bit confusing. Take `RenderPipelinePtr` in that case the pointed object is non const, but the naming is extremely similar. To try to clear up the ambiguity we could make it into `ConstPassTemplatePtr` (as seen on `ConstViewPtr`) but on top of making it a tad longer, I would also argue that the fact that this is a shared pointer (as opposed to the similar `QueryPoolPtr` which is unique) bears some importance as it implies atomic ref counting.
What do you think?

**Comment by rgba16f** [comment]
> I personally dislike this pattern as it hides the actual implementation details and can make things a bit confusing. Take `RenderPipelinePtr` in that case the pointed object is non const, but the naming is extremely similar. To try to clear up the ambiguity we could make it into `ConstPassTemplatePtr` (as seen on `ConstViewPtr`) but on top of making it a tad longer, I would also argue that the fact that this is a shared pointer (as opposed to the similar `QueryPoolPtr` which is unique) bears some importance as it implies atomic ref counting. What do you think?

I think for most engineers using the system the main point is that it's a ptr.  const & shared are only relevant if you get into the guts of how the system works, in which case you could dig into what the typedef was. Without the typedef it's a lot of line noise  inducing cognitive burden just to understand it's a pointer.
There isn't any coding standard guidance around this, and I don't think it should block the PR. It's more of a style choice :)

**Review by gadams3 — APPROVED** [review]

**Review by cgalvan — APPROVED** [review]

**Pull request merged**
