### PR TITLE
Migrate CDK stacks to CDK v2

### PR DESCRIPTION
**Pull request by lmbr-pip**
# What does this PR do?

This PR migrates the AWS Gems stacks (currently has only the AWS Core gem) to [CDK v2](https://aws.amazon.com/about-aws/whats-new/2021/12/aws-cloud-development-kit-cdk-generally-available/) stacks, as CDK v1 is now end of life. This ensure the CDK templates continue to work.

* Archive CDK v1 version of these stacks so folks can migrate existing stacks if needed (cdkv1 folder)
* Provide CDK v2 compatible application (cdk folder)

This does not attempt to use any new CDK v2 constructs, its just a patching so CDK templates continue to work.

Aim to convert all the AWS Gems to CKD v2 and push at once (once approved).

# How tested?
Deployed stacks and ran integration tests against them on Windows.

Signed-off-by: Pip Potter <61438964+lmbr-pip@users.noreply.github.com>

### CODE REVIEW

**Review by allisaurus — COMMENTED** [review]
Looks good to me - changes seem to mostly reflect new lib names & imports vs. changes to stack functionality.

> currently has only the AWS Core gem

In case this wasn't already the plan, I'd prefer we upgrade one gem per PR, to keep review diff size down and prevent potential issues with some future construct update derailing the larger effort.

**Comment by junbo75** [comment]
Looks good to me as well.

**Comment by lmbr-pip** [comment]
Need to convert other 3 gems

- [ ]  AWS GameLift: https://github.com/o3de/o3de/pull/11463
- [ ] AWS ClientAuth
- [ ] AWS Metrics

**Comment by lmbr-pip** [comment]
Building all these changes into a feature branch, so this PR is no longer required.

**Pull request closed without merging**
