### PR TITLE
Don't apply external property changes to widget while the user is editing the property

### PR DESCRIPTION
**Pull request by yuriy0**
A follow up to https://github.com/o3de/o3de/pull/2936 and https://github.com/o3de/o3de/pull/1468 .

These two previous changes solved the issue for several different reflected property widgets. This isn't really a scalable solution because the issue applies to all reflected property widgets, and the user is able to define their own widgets for their own types. In particular, even with those two PRs, the issue still occurs for PhysX collision layers, collision groups, and material ID selection widgets.

This change will (hopefully!) fix the issue once and for all for every reflected property widget, by handling the case where a user is editing a particular property in the reflected property editor.

### CODE REVIEW

**Comment by monroegm** [comment]
@yuriy0 Were you able to address the feedback yet?

**Comment by yuriy0** [comment]
@NicholasVanSickle re:
> If possible I'd like to avoid components changing authored data without user input at all

From this perspective, it's really an issue with the editor animation preview. The problem is as you describe - "the Actor component adjusts entities' transforms while doing an animation preview and triggers a full property refresh that stomps on authoring data". other animation system component have the same issue (adjusts transforms of editor entities).

These could each be fixed on a case by case basis, but the fixes may end up being complex:
- the Actor component shouldn't apply motion extraction in the editor (easy enough)
- the Simple Motion component should hide the "editor actor" and create its own "preview actor" (which is an entity copied from the editor actor configuration) and play animations on that. this wouldn't effect the editor actor. (a bit more involved, but manageable)
- the Attachment component should also create "preview" copies of its entity when the actor enters "preview mode". Then, which components on that entity does it clone? this is where it gets a bit hairy.

Maybe the correct approach is to simply eliminate all of the "editor preview" functionalities on these components altogether, and create a new interface for enabling 'simulation mode' for only one specific entity or a group of entities.

In my mind, the solution in this PR is a bit of a quick and dirty workaround which should be removed once something like the above is implemented.

**Comment by amznestebanpapp** [comment]
@NicholasVanSickle any updates to @yuriy0's last comment?

**Comment by monroegm** [comment]
@yuriy0 Are you still trying to get in?

**Comment by monroegm** [comment]
Closing. Please open a new PR if this is needed in the future.

**Pull request closed without merging**
