### PR TITLE
fix the generated restricted and engines folders

### PR DESCRIPTION
**Pull request by byrcolin**
fix the generated restricted and engines folders, they should be in the <user>/O3DE  user folder not the <user>/.o3de configuration folder

Signed-off-by: byrcolin <byrcolin@amazon.com>

### CODE REVIEW

**Comment by spham-amzn** [comment]
Stabilization is locked, so this will need to go through the exception process

**Review by spham-amzn — APPROVED** [review]

**Review by AMZN-alexpete — APPROVED** [review]

**Comment by tonybalandiuk** [comment]
- [ ] 1.    Owning SIG requests the exception, by a Sig Representative (Chair/co-chair) adding the PR to the exception requests queue board.
- [ ] 2.	 Unrelated SIG representative (chair/cochair) approves the exception, adding a comment indicating approval and the SIG they represent.
- [ ] 3.	UX SIG representative (chair/cochair) approves the exception, adding a comment indicating approval and the SIG they represent.
- [ ] 4.	Testing SIG representative (chair/cochair) approves the exception, adding a comment indicating approval and the SIG they represent.
- [ ] 5.	If all approvals are accepted exception PR is merged
- [ ] 6.	Merged PR is verified successful via testing. If Merged PR verification testing failed, consult reps from step 3-5 and discussion occurs on fixing the failure vs backing out change
- [ ] 7.	Exception is complete

**Review by amzn-phist — APPROVED** [review]

**Comment by byrcolin** [comment]
Q) Quick Question, what is the impact for users if this is not included in stabilization?
A) Its not too bad, its the way we mistakenly shipped it last time. The folders are simply in the wrong place. All user o3de objects should be in the O3DE folder by default, that's why it exists. The .o3de folder is only for configuration and cache, perhaps 3rdparty and registry. I would argue more should probably be moved out of there like logs and download, but the ones I moved are no question, these are in the wrong place moves. The impact on the customer is they will potentially have o3de object in an unobvious place as the .o3de is hidden  from the user by default. They could always move those objects and re register them in the correct locations, but that would have to be explained and they would have to do it themselves. If the question is can we ship without this, yes, we could, we have in the past, but we shouldn't, it's an easy enough change, low risk.
Q) Will this change break any existing users?
A) No. It shouldn't. Objects in the configuration folder are still just as valid as ones outside the folder, so if the customer already has o3de objects in the .o3de folder then they will still function. This would effect ht location of any new o3de objects they would make as they would goto into a different folder by default.

**Review by lsemp3d — APPROVED** [review]

**Comment by lumberyard-employee-dm** [comment]
While I believe the change is innocuous, I don't think that is a good reason to add an exception for changing the default folder where new O3DE "engines" and "restricted" objects are created.

The effect on users of stabilization of the default engine folder paths being at `~/.o3de/Engines` is 0% as the engine isn't "created" from the o3de python scripts so it is just unused field in the o3de manifest.
For the default restricted folder, it doesn't matter at this point where it is located `~/.o3de/Restricted` is located and it being in hidden folder on Linux and Mac is probably actually better for it.

I think this change will have zero impact on users of the 2205 release and we should just merge the change into development as.

**Comment by Ulrick28** [comment]
@lumberyard-employee-dm If I understand correctly you are saying this change would have no real impact to users submitted or not to stabilization. It also sounds like there is some disagreement on some of the folder and object locations. If I am correct, then I concur this change should be submitted to Development only and wait for the following release.

**Comment by lumberyard-employee-dm** [comment]
> @lumberyard-employee-dm If I understand correctly you are saying this change would have no real impact to users whether or not it is submittedto stabilization. It also sounds like there is some disagreement on some of the folder and object locations. If I am correct, then I concur this change should be submitted to Development only and wait for the following release.

Yes, I am saying whether this change makes it into stabilization or not, I don't see any downstream users being impacted by it.

**Comment by tonybalandiuk** [comment]
Thanks @lumberyard-employee-dm for your input. At this point, pleas hold on submitting this PR. We will review further on 5/5 in the morning.

**Comment by lumberyard-employee-dm** [comment]
You can re-target this PR to the development to branch by clicking on the stabilization/2205 link right below the summary.
I see PR as still valid, just not for the stabilization/2205 branch image

**Pull request closed without merging**
