### PR TITLE
Roll back full screen camera fix

### PR DESCRIPTION
**Pull request by hultonha**
Roll back full screen camera fix and enable disabled test until all issues can be fixed

## What does this PR do?

Rolls back the full screen game mode camera fix that interacted badly with normal `Ctrl-G` functionality. This full screen game mode will be investigated separately.

(Note: The bad interaction seemed to be caused by this change - https://github.com/o3de/o3de/pull/14889/files)

## How was this PR tested?

Tested in Editor, ran automated tests + AR run

### CODE REVIEW

**Review by SergeyAMZN — APPROVED** [review]

**Review by amzn-ahmadkrm — APPROVED** [review]
lgtm!

**Review by moraaar — APPROVED** [review]
LGTM. Maybe you should probably reopen the bug https://github.com/o3de/o3de/issues/14527 for now so it's clear it's not fixed at the moment in development.

**Comment by hultonha** [comment]
> LGTM. Maybe you should probably reopen the bug #14527 for now so it's clear it's not fixed at the moment in development.

I actually have a fix for this already! So as soon as this is merged I'll back out the back out 😅 and create another PR with the change :+1:

**Comment by moraaar** [comment]
>I'll back out the back out 😅

love this :)

**Comment by hultonha** [comment]
> > I'll back out the back out 😅
> 
> love this :)

Here's the change again, now working for fullscreen and normal Ctrl-G behaviour 🙂 - https://github.com/o3de/o3de/pull/15119

**Pull request merged**
