### PR TITLE
Atom/16852

### PR DESCRIPTION
**Pull request by HogJonny-AMZN**
This PR is handing some refactoring related to the DCCsi (Dcc Scripting Interface)
- reduce cyclical import collisions
- simplify the editor boostrapping related to the DCCsi (as well as perf)
- some housecleaning
- scaffold for future features (per-editor app bootstrap logic)

### CODE REVIEW

**Comment by HogJonny-AMZN** [comment]
With the current state of the PR
- azpy/config_utils.py does not import from other azpy modules including constants (there was some cyclical import dependencies occurring.)
- added a simple commandline for some testing (this module help bootstrap external standalone utils.)
image

**Comment by HogJonny-AMZN** [comment]
Help for cmdline options
image

**Comment by HogJonny-AMZN** [comment]
enabled debug data and auto-attach wingide debugging
image

**Comment by HogJonny-AMZN** [comment]
DccScriptingInterface\Editor\Scripts\bootstrap.py
1. added a simple cli to test/debug externally (outside editor)
2. added scaffolding to control how/what is bootstrapping depending on the editor (so can alter which modules run where)
3. bootstrapping doesn't envoke the config.py which can slow start times (synthetic env, we only run it now in a test mode so we can continue to implement and test it)

here is the cli without debug
image

**Comment by HogJonny-AMZN** [comment]
Here is the bootstrap.py with cli test flags enabled:
image

**Review by gadams3 — APPROVED** [review]
Looks good from what I can tell. Only recommendation is to separate large renames into their own pull requests. They don't need much attention and will be reviewed quickly. This will help the reviewer isolate and focus on the critical changes more easily.

**Review by benblack75 — APPROVED** [review]

**Pull request merged**
