### PR TITLE
BlendGraphWidget: remove nodes from group from assignment menu

### PR DESCRIPTION
**Pull request by Be-ing**
Previously, the checked menu item representing the group the nodes were already in didn't do anything. Now selecting that menu item removes the nodes from that group, as expected when unchecking the item.

Follow up to https://github.com/o3de/o3de/pull/13416#discussion_r1034006566

## How was this PR tested?

manually

### CODE REVIEW

**Review by cgalvan — APPROVED** [review]

**Comment by hultonha** [comment]
Any chance you could please add a video and/or screen shot for this functionality please @Be-ing. Thanks!

**Review by hultonha — APPROVED** [review]
Change looks good but would be helpful from a UX perspective to see the change in action to help with the review. Thanks!

**Comment by Be-ing** [comment]
Here is a video of the added functionality:
[remove-from-node-group.webm](https://user-images.githubusercontent.com/9455094/205209143-0536600a-d015-4301-9cda-c7e7b9149e04.webm)

**Comment by hultonha** [comment]
Change looks good @Be-ing - I just want to check how this works with multiple selections (as I know @aambrosano was working on this recently and there's some subtleties there). Might be worth quickly syncing with him about the change and if it sounds good I can hit the merge button shortly!

**Comment by Be-ing** [comment]
Good question. Previously the menu item didn't do anything and was unchecked if multiple nodes were selected. Now the menu item is checked if all the selected nodes are within the same group:

https://user-images.githubusercontent.com/9455094/205395560-06d993eb-4caa-47d0-a36f-dc6d4747fa65.mp4

**Comment by FuzzyCarterAWS** [comment]
@hultonha @Be-ing 

Added references to the workflows in o3d3/o3de#22.

**Review by hultonha — CHANGES_REQUESTED** [review]
Putting a block on this temporarily as this does change functionality I previously discussed with @aambrosano.

Could @Be-ing and @aambrosano please have a call to discuss and go over what myself and @aambrosano discussed last week. Sorry for the confusion but there's so many weird edge cases with multiple selections and different groups, we want to make sure we get this right. Thanks!

Please poke me once you've talked and I can remove the change request.

**Comment by cgalvan** [comment]
@Be-ing It sounds like from the offline discussions that this behavior has been replaced in favor of a different workflow. Feel free to re-open if that changes!

**Pull request closed without merging**
