### PR TITLE
Disable invalid operations related to procedural prefabs in the Inspector

### LINKED ISSUE #6338: Prefab Focus Mode: Lock Transform and Reset Transform Appear Usable Within Read-Only Entity Components
**Describe the bug**
The Lock and Reset Transform buttons appear usable when expanding the hamburger menu within read only entity components inside the Entity Inspector

**Pre-requisites**

1. Procedural Prefabs are enabled in AutomatedTesting\user\Registry\editorpreferences.setreg:

```
{
    "Amazon": {
        "Preferences": {
            "EnablePrefabSystem": true,
            "EnablePrefabSystemWipFeatures": true
        }
    },
    "O3DE": {
        "Preferences": {
            "Prefabs": {
                "SaveAllPrefabs": "Ask every time",
                "UseProceduralPrefabs": true
            }
        }
    }
}

```
**Steps to reproduce**

1.     Launch the Editor and open a new or existing level.
2.     Instantiate any .procprefab into the Entity Outliner.
3.     Enter Focus Mode on the .procprefab, and select a read-only entity. 
4.     In the Entity Inspector, expand the transform component's hamburger menu (or right-click the transform component)

**Expected behavior**
Only the "Copy Component" field is available for components within a read-only entity. 

**Actual behavior**
Lock Transform and Reset Transform appear usable.

**Screenshots/Video**
image

**Found in Branch**
development@a8a96d3e66853fdd

### PR DESCRIPTION
**Pull request by AMZN-daimini**
### Disable additional transform component context menu items that allow the user to clear the transform.
image

### Prevent the user from selecting invalid entities via the entity picker (for example, reparenting entities under a procedural prefab, which is read-only).
noReparentingViaPicker

Fixes #6338 and #6343

Signed-off-by: Danilo Aimini <82231674+AMZN-daimini@users.noreply.github.com>

### CODE REVIEW

**Review by NicholasVanSickle — APPROVED** [review]

**Review by AMZN-stankowi — COMMENTED** [review]
Can you add some automated tests for these behaviors? They should be possible here https://github.com/o3de/o3de/blob/development/Code/Framework/AzToolsFramework/Tests/TransformComponent.cpp

**Comment by AMZN-daimini** [comment]
> Can you add some automated tests for these behaviors? They should be possible here https://github.com/o3de/o3de/blob/development/Code/Framework/AzToolsFramework/Tests/TransformComponent.cpp

I think I can add a few pretty quickly, yes!

**Review by jackalbe — APPROVED** [review]

**Comment by AMZN-daimini** [comment]
Having issues running the tests locally. I'm doing a full rebuild.
Depending on how much of an issue it becomes, I may submit this without the tests and add a follow-up PR with the tests. Still hope to make things work tho :D

**Comment by AMZN-daimini** [comment]
Ok, a few updates:
- I had to revert part of the fix, since adding those checks on the actual implementation of SetParent broke the existing tests. As with many other checks like this, we really only want the UI to be unable to execute certain operations, but the backend should still be able to do them.
- As a result of the above, the fix still works from the UI side (since the codepath that is triggered by changing an EntityId via the RPE triggers ValidatePotentialParent) but it cannot be easily hit from unit tests.

I am adding a task to add an automated test for this, but it will either require some more instrumentation on the unit test side or a python test that replicates the UI behavior.

**Review by AMZN-koppersr — APPROVED** [review]

**Comment by alexmontAmazon** [comment]
@AMZN-daimini , is this ready to go, or are you still working on this?

**Comment by AMZN-daimini** [comment]
> @AMZN-daimini , is this ready to go, or are you still working on this?

Ready to go, I could not add unit tests before leaving but the changes are finalized :)

**Pull request merged**
