### PR TITLE
Proposed fix for Issue #10479. Where downloading a gem doesn't work a…

### PR DESCRIPTION
**Pull request by incisor**
…fter a previous gem download.

## What does this PR do?

Fixes the issue [#10479](https://github.com/o3de/o3de/issues/10479)

The issue happens because the index map is not updated when a row is removed and the model indexes in the gem model updates. 

We can walk what happens using the PopcornFX repo.
1. When the repo is added there will be two gems that will be added named "PopcornFX 2.9" and "PopcornFX"
2. Gem Catalog screen's model is filled and two gems are added to the model and their model indexes are placed to "m_nameToIndexMap" which is a QHash for easier retrieval of model indexes later on.
3. "PopcornFX 2.9" is set to row 116 and "PopcornFX" to row 117. Note: this could be different depending on the number of gems in your machine.
4. Downloading "PopcornFX 2.9" will trigger a download and after a successful download the model index will be removed and re-added to the gem model. 
5. The gem model will update "PopcornFX" to row 116 because the previous model index("PopcornFX 2.9") was deleted but later added so "PopcornFX 2.9" is now in row 117.
6. The gem model is correct but the index map is not. When fetching "PopcornFX" it will return row 117 which is now "PopcornFX 2.9" and will not download since the download status is already set to downloaded.

## How was this PR tested?

Using PopcornFX repo as a test, after adding the repo download PopcornFX 2.9 first then see if downloading PopcornFX gem will be successful.

### CODE REVIEW

**Comment by AMZN-alexpete** [comment]
Thanks for looking into this @incisor !  I think you're on the right track here with the fix, but I suggest we use the Qt::rowsRemoved signal instead - whenever `removeRow` is called it calls `removeRows` and[ in that code it sends the before and after signals](https://github.com/qt/qtbase/blob/067b53864112c084587fa9a507eb4bde3d50a6e1/src/gui/itemmodels/qstandarditemmodel.cpp#L1748).  We were already listening to the `rowsAboutToBeRemoved` signal, 

You could add method called `OnRowsRemoved` like this
```
    void GemModel::OnRowsRemoved(const QModelIndex& parent, int first, [[maybe_unused]] int last)
    {
        // fix up the name to index map for all rows that changed
        for (int row = first; row < rowCount(); ++row)
        {
            const QModelIndex modelIndex = index(row, 0, parent);
            m_nameToIndexMap[GetName(modelIndex)] = modelIndex;
        }
    }
```
And connected it like this in the `GemModel` constructor
```
    connect(this, &QAbstractItemModel::rowsRemoved, this, &GemModel::OnRowsRemoved);
```
You'll also need to declare the function in the header in the slots section
```
        void OnRowsRemoved(const QModelIndex& parent, int first, int last);
```

**Comment by incisor** [comment]
> Thanks for looking into this @incisor ! I think you're on the right track here with the fix, but I suggest we use the Qt::rowsRemoved signal instead - whenever `removeRow` is called it calls `removeRows` and[ in that code it sends the before and after signals](https://github.com/qt/qtbase/blob/067b53864112c084587fa9a507eb4bde3d50a6e1/src/gui/itemmodels/qstandarditemmodel.cpp#L1748). We were already listening to the `rowsAboutToBeRemoved` signal,
> 
> You could add method called `OnRowsRemoved` like this
> 
> ```
>     void GemModel::OnRowsRemoved(const QModelIndex& parent, int first, [[maybe_unused]] int last)
>     {
>         // fix up the name to index map for all rows that changed
>         for (int row = first; row < rowCount(); ++row)
>         {
>             const QModelIndex modelIndex = index(row, 0, parent);
>             m_nameToIndexMap[GetName(modelIndex)] = modelIndex;
>         }
>     }
> ```
> 
> And connected it like this in the `GemModel` constructor
> 
> ```
>     connect(this, &QAbstractItemModel::rowsRemoved, this, &GemModel::OnRowsRemoved);
> ```
> 
> You'll also need to declare the function in the header in the slots section
> 
> ```
>         void OnRowsRemoved(const QModelIndex& parent, int first, int last);
> ```

Tried your suggestion and it does make it simpler. Pushed the changes. Thanks!

**Comment by AMZN-alexpete** [comment]
Thanks for making those changes @incisor, one more thing is needed before this change can be merged - you need to "sign" your commits to pass the DCO check, it's really simple to do More information about what DCO signing is can be found here https://github.com/apps/dco and these are the commits that don't have signing https://github.com/o3de/o3de/pull/10487/checks?check_run_id=7159026696

**Comment by incisor** [comment]
@AMZN-alexpete , commits signed-off now. Thanks!

**Comment by cgalvan** [comment]
@incisor Thanks for fixing the DCO issues, I've kicked off a new AR run

**Review by cgalvan — APPROVED** [review]

**Review by AMZN-alexpete — APPROVED** [review]

**Pull request merged**
