### PR TITLE
feat: replace old trackview icons

### PR DESCRIPTION
**Pull request by pollend**
## What does this PR do?

I would like to replace the rest of the track view icons. these are a couple of the icons i could find from EmotionFX and a couple of tweaked ones. 
image

## How was this PR tested?

_Please describe any testing performed._

### CODE REVIEW

**Review by lsemp3d — APPROVED** [review]

**Comment by lsemp3d** [comment]
@pollend I really like this change but it looks like it needs a merge from development to get it to build. Happy to run the build if you can update it

**Comment by pollend** [comment]
@lsemp3d I was hoping to get updated icons, from sig-ux.

**Comment by lsemp3d** [comment]
> @lsemp3d I was hoping to get updated icons, from sig-ux.  

I think these are a good start

**Comment by AMZN-daimini** [comment]
Love this, thanks for looking into it :D

Ideally, instead of adding these to a folder specific to the TrackView, you could give those icons more generic names and add them to the AzQtComponents Images folder: https://github.com/o3de/o3de/tree/development/Code/Framework/AzQtComponents/AzQtComponents/Images

This way they can be re-used across different tools (A "Playback" folder would likely contain most of them). Of course there may be some icons that are very specific to the TrackView workflows, but the common ones should be reusable.

On top of this, are the icons that were replaced still referenced somewhere? Deleting them if they are orphaned would be another small win :)

**Comment by lsemp3d** [comment]
> Love this, thanks for looking into it :D
> 
> Ideally, instead of adding these to a folder specific to the TrackView, you could give those icons more generic names and add them to the AzQtComponents Images folder: https://github.com/o3de/o3de/tree/development/Code/Framework/AzQtComponents/AzQtComponents/Images
> 
> This way they can be re-used across different tools (A "Playback" folder would likely contain most of them). Of course there may be some icons that are very specific to the TrackView workflows, but the common ones should be reusable.
> 
> On top of this, are the icons that were replaced still referenced somewhere? Deleting them if they are orphaned would be another small win :)

@pollend should we hold off on merging to make these changes?

**Comment by pollend** [comment]
I think I was just following what was already established. All the icons I think are duplicated but I think it makes sense to have like a standard set of icons for consistency.

**Comment by lsemp3d** [comment]
> I think I was just following what was already established. All the icons I think are duplicated but I think it makes sense to have like a standard set of icons for consistency.
> 
> I also haven't looked at this in a long time so I don't remember which icons I changed. I think I borrowed icons from emotionfx and added my own using inkscape.

I can merge and create a new issue with @AMZN-daimini 's suggestions

**Pull request merged**
