### PR TITLE
chore(WhiteBox): update cvar constants based on functionality

### PR DESCRIPTION
**Pull request by pollend**
## What does this PR do?

This just updates the CVAR based on the functionality of the color. I think this is a lot more maintainable. 

## How was this PR tested?

some of the color are slightly different.

### CODE REVIEW

**Comment by hultonha** [comment]
@pollend It looks like this contains more changes than just the rename of CVARs - it might be necessary to redo this PR with only those changes to keep things atomic. Thanks!

**Comment by hultonha** [comment]
Ah I see okay, understood :+1:

**Review by cgalvan — APPROVED** [review]

**Comment by hultonha** [comment]
Just kicked off a build :+1:

**Comment by cgalvan** [comment]
Thanks @pollend  I've kicked off a new AR build

**Pull request merged**
