### PR TITLE
Revert Asset Picker View to previous one

### PR DESCRIPTION
**Pull request by AMZN-Igarri**
Signed-off-by: AMZN-Igarri <82394219+AMZN-Igarri@users.noreply.github.com>

### CODE REVIEW

**Review by hultonha — APPROVED** [review]
LGTM, thanks for updating 👍

**Review by jcartwright- — APPROVED** [review]
This aligns to our discussion! Thanks

**Comment by amzn-leenguy** [comment]
I don't understand enough context here to sign this one off. Let me know if you want to sync or just explain here. Sorry! lol @AMZN-Igarri

**Comment by AMZN-Igarri** [comment]
@amzn-leenguy So basically we had a meeting and decided to revert the changes to the Asset Picker back to the default Tree View, and rethink these newer changes later

**Review by jonawals — APPROVED** [review]

**Pull request merged**
