### PR TITLE
Enabling WhiteBox tests on Linux

### PR DESCRIPTION
**Pull request by jckand-amzn**
Signed-off-by: jckand-amzn <82226555+jckand-amzn@users.noreply.github.com>

### CODE REVIEW

**Comment by hultonha** [comment]
@jckand-amzn you are a legend! 😄 Thank you! Fingers crossed everything passes 🤞

**Review by hultonha — APPROVED** [review]

**Comment by Kadino** [comment]
I assume other commits already updated the tests themselves. Mind adding those to the description?

If it's green it ships! Though I'll still examine the logs to make sure the tests actually ran :)

**Comment by jckand-amzn** [comment]
> I assume other commits already updated the tests themselves. Mind adding those to the description?
> 
> If it's green it ships! Though I'll still examine the logs to make sure the tests actually ran :)

Andrea moved the tests into the optimized framework in #7600. Nothing I could see in the conversions seemed platform dependent, so they *shouldn't* need any further work. Will definitely verify they've run properly before merging.

**Comment by jckand-amzn** [comment]
@hultonha , unfortunately it appears there will be some troubleshooting necessary to fix up one of the tests. I opened a new GitHub Issue for that failing test at #7828. Going to close this PR out until that issue is addressed.

**Comment by hultonha** [comment]
> @hultonha , unfortunately it appears there will be some troubleshooting necessary to fix up an issue with one of the tests. I opened a new GitHub Issue for that failing test at #7828. Going to close this PR out until that issue is addressed.

Botheration... okay thanks for trying, was definitely worth a shot 😅 It might be worth re-opening and moving to draft for now as we do still want this at some point (or if the next PR flips the switch that's fine)

**Pull request closed without merging**
