### PR TITLE
Promote IndexedDataVector to public Feature/Utils header

### PR DESCRIPTION
**Pull request by jeremyong-az**
Also adds a new constructor to specify the reservation size if 128 elements by default are not needed.

### CODE REVIEW

**Comment by jeremyong-az** [comment]
For the reviewer, the PR is split into two commits. The first commit moves the files with no changes at all. The second commit consolidates the inl header with the main header, fixes some comments, and adds a new constructor for specifying the initial reservation size.

**Comment by invertednormal** [comment]
Only thing I'm wondering about is why remove the inl file? That's a pretty common way to keep implementation separate from the interface in templated classes.

**Comment by jeremyong-az** [comment]
> Only thing I'm wondering about is why remove the inl file? That's a pretty common way to keep implementation separate from the interface in templated classes.

Well, the MultiIndexedDataVector doesn't do this, and personally I'm not a huge fan of the inl pattern because it breaks intellisense often. In this case also, it felt like the implementation was small, and even somewhat useful to see to understand what the data structure is doing. If you feel strongly about it, I don't mind reverting that aspect of the change, but I would prefer not to.

**Comment by kberg-amzn** [comment]
Personally I like the split .h/.inl pattern as a customer, since often the .h file provides the only up to date formal documentation for people trying to use a system. Having implementation details mixed into the class declaration makes it quite hard for the reader to extract the public facing API. Witness our AZStd classes as evidence, which are just non-standard enough that referencing online std documentation instead is potentially dangerous.

**Comment by kberg-amzn** [comment]
Though what you've done to append the .inl contents to the end of the .h mitigates my concern almost entirely. I am far less opposed to people merging in .inl changes the way you have done.

**Comment by jeremyong-az** [comment]
Yea, I like the separation of interface from implementation for sure (makes interface far more readable). I do also dislike not being able to F12 symbols and red squiggles in the editor though 💯

**Review by invertednormal — APPROVED** [review]
I still prefer the h / inl separation but it's not a deal breaker, at least the implementation is kept separate in the header instead of being combined with the declaration.

While you're in here modifying the file, you could combine the two namespaces into one to save a level of indentation -

namespace AZ::Render
{
    /// code
}

**Comment by jeremyong-az** [comment]
> I still prefer the h / inl separation but it's not a deal breaker, at least the implementation is kept separate in the header instead of being combined with the declaration.
> 
> While you're in here modifying the file, you could combine the two namespaces into one to save a level of indentation -
> 
> namespace AZ::Render
> {
> /// code
> }

Will do as soon as I confirm I didn't introduce any build issues via CI

**Review by galibzon — APPROVED** [review]

**Review by gadams3 — APPROVED** [review]

**Review by rgba16f — APPROVED** [review]
Can you add a comment separator between the interface and the implementation.
We usually use ////////////////////////////

**Comment by jeremyong-az** [comment]
Good news everyone! Oh a whim, I redid the `.h` and `.inl` separation and what I found was, it was _the way_ in which this separation was done before that was breaking intellisense. The `.inl` file was being expanded within the outer namespace `AZ::Render` so when viewing the `.inl` file itself, intellisense couldn't reason about where the symbols were originally declared.

**Pull request merged**
