### PR TITLE
Workaround VS2022 compiler issue in Debug configuration

### PR DESCRIPTION
**Pull request by lumberyard-employee-dm**
When builing the AnimGraphStateMachineInterruptionTests.cpp in debug
configuration using the MSVC v143 toolset, the `EXPECT_EQ` calls fail to
compile when both parameters are bools.

Instead of using EXPECT_EQ for the comparison of booleans, EXPECT_THAT
is used instead and that avoids the compiler issue.

Below is the compiler issue
```
1>------ Build started: Project: EMotionFX.Tests, Configuration: debug
x64 ------
1>AnimGraphStateMachineInterruptionTests.cpp
1>D:\o3de\o3de\Gems\EMotionFX\Code\Tests\AnimGraphStateMachineInterruptionTests.cpp(171,25):
error C2039: 'Compare': is not a member of 'testing::internal'
1>D:\o3de\o3de\Gems\EMotionFX\Code\Tests\AnimGraphStateMachineInterruptionTests.cpp(171,25):
error C2039:                         EXPECT_EQ(activeObjects.m_stateA,
compareAgainst.m_stateA)
1>D:\o3de\o3de\Gems\EMotionFX\Code\Tests\AnimGraphStateMachineInterruptionTests.cpp(171,25):
error C2039:                         ^
1>D:\3rdParty\packages\googletest-1.8.1-rev4-windows\googletest\include\gmock/gmock-more-actions.h(45):
message : see declaration of 'testing::internal'
1>D:\3rdParty\packages\googletest-1.8.1-rev4-windows\googletest\include\gmock/gmock-more-actions.h(45):
message : namespace internal {
1>D:\o3de\o3de\Gems\EMotionFX\Code\Tests\AnimGraphStateMachineInterruptionTests.cpp(173,25):
error C2039: 'Compare': is not a member of 'testing::internal'
1>D:\o3de\o3de\Gems\EMotionFX\Code\Tests\AnimGraphStateMachineInterruptionTests.cpp(173,25):
error C2039:                         EXPECT_EQ(activeObjects.m_stateB,
compareAgainst.m_stateB)
1>D:\o3de\o3de\Gems\EMotionFX\Code\Tests\AnimGraphStateMachineInterruptionTests.cpp(173,25):
error C2039:                         ^
1>D:\3rdParty\packages\googletest-1.8.1-rev4-windows\googletest\include\gmock/gmock-more-actions.h(45):
message : see declaration of 'testing::internal'
1>D:\3rdParty\packages\googletest-1.8.1-rev4-windows\googletest\include\gmock/gmock-more-actions.h(45):
message : namespace internal {
1>D:\o3de\o3de\Gems\EMotionFX\Code\Tests\AnimGraphStateMachineInterruptionTests.cpp(175,25):
error C2039: 'Compare': is not a member of 'testing::internal'
1>D:\o3de\o3de\Gems\EMotionFX\Code\Tests\AnimGraphStateMachineInterruptionTests.cpp(175,25):
error C2039:                         EXPECT_EQ(activeObjects.m_stateC,
compareAgainst.m_stateC)
1>D:\o3de\o3de\Gems\EMotionFX\Code\Tests\AnimGraphStateMachineInterruptionTests.cpp(175,25):
error C2039:                         ^
1>D:\3rdParty\packages\googletest-1.8.1-rev4-windows\googletest\include\gmock/gmock-more-actions.h(45):
message : see declaration of 'testing::internal'
1>D:\3rdParty\packages\googletest-1.8.1-rev4-windows\googletest\include\gmock/gmock-more-actions.h(45):
message : namespace internal {
1>D:\o3de\o3de\Gems\EMotionFX\Code\Tests\AnimGraphStateMachineInterruptionTests.cpp(177,25):
error C2039: 'Compare': is not a member of 'testing::internal'
1>D:\o3de\o3de\Gems\EMotionFX\Code\Tests\AnimGraphStateMachineInterruptionTests.cpp(177,25):
error C2039:
EXPECT_EQ(activeObjects.m_transitionLeft,
compareAgainst.m_transitionLeft)
1>D:\o3de\o3de\Gems\EMotionFX\Code\Tests\AnimGraphStateMachineInterruptionTests.cpp(177,25):
error C2039:                         ^
1>D:\3rdParty\packages\googletest-1.8.1-rev4-windows\googletest\include\gmock/gmock-more-actions.h(45):
message : see declaration of 'testing::internal'
1>D:\3rdParty\packages\googletest-1.8.1-rev4-windows\googletest\include\gmock/gmock-more-actions.h(45):
message : namespace internal {
1>D:\o3de\o3de\Gems\EMotionFX\Code\Tests\AnimGraphStateMachineInterruptionTests.cpp(179,25):
error C2039: 'Compare': is not a member of 'testing::internal'
1>D:\o3de\o3de\Gems\EMotionFX\Code\Tests\AnimGraphStateMachineInterruptionTests.cpp(179,25):
error C2039:
EXPECT_EQ(activeObjects.m_transitionMiddle,
compareAgainst.m_transitionMiddle)
1>D:\o3de\o3de\Gems\EMotionFX\Code\Tests\AnimGraphStateMachineInterruptionTests.cpp(179,25):
error C2039:                         ^
1>D:\3rdParty\packages\googletest-1.8.1-rev4-windows\googletest\include\gmock/gmock-more-actions.h(45):
message : see declaration of 'testing::internal'
1>D:\3rdParty\packages\googletest-1.8.1-rev4-windows\googletest\include\gmock/gmock-more-actions.h(45):
message : namespace internal {
1>D:\o3de\o3de\Gems\EMotionFX\Code\Tests\AnimGraphStateMachineInterruptionTests.cpp(181,25):
error C2039: 'Compare': is not a member of 'testing::internal'
1>D:\o3de\o3de\Gems\EMotionFX\Code\Tests\AnimGraphStateMachineInterruptionTests.cpp(181,25):
error C2039:
EXPECT_EQ(activeObjects.m_transitionRight,
compareAgainst.m_transitionRight)
1>D:\o3de\o3de\Gems\EMotionFX\Code\Tests\AnimGraphStateMachineInterruptionTests.cpp(181,25):
error C2039:                         ^
1>D:\3rdParty\packages\googletest-1.8.1-rev4-windows\googletest\include\gmock/gmock-more-actions.h(45):
message : see declaration of 'testing::internal'
1>D:\3rdParty\packages\googletest-1.8.1-rev4-windows\googletest\include\gmock/gmock-more-actions.h(45):
message : namespace internal {
1>Done building project "EMotionFX.Tests.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped
==========
```

Signed-off-by: lumberyard-employee-dm <56135373+lumberyard-employee-dm@users.noreply.github.com>

## How was this PR tested?

Built the EMotionFX.Tests project for the debug configuration using VS2022 successfully.

### CODE REVIEW

**Review by cgalvan — APPROVED** [review]

**Review by jackalbe — APPROVED** [review]

**Comment by lumberyard-employee-dm** [comment]
Apparently this issue also occurs in profile and release in the [nightly build](https://jenkins.build.o3de.org/job/O3DE_periodic-incremental-daily/job/development/66/execution/node/1075/log/?consoleFull).

@amzn-changml @brianherrera It would be nice to get one VS2022 build step as part of the AR pipeline to have these issues be caught outside of the nightly

**Comment by lumberyard-employee-dm** [comment]
I think we should swap around the https://github.com/o3de/o3de/blob/development/scripts/build/Platform/Windows/build_config.json#L332-L353 for the VS2019 release build and the VS2022 release build, so that the VS2022 release build is part of AR and the VS2019 release build is part of the nightly.

**Comment by brianherrera** [comment]
> I think we should swap around the https://github.com/o3de/o3de/blob/development/scripts/build/Platform/Windows/build_config.json#L332-L353 for the VS2019 release build and the VS2022 release build, so that the VS2022 release build is part of AR and the VS2019 release build is part of the nightly.

That works for me and avoids having to increase the cost of adding a VS2022 node to the AR run. Mike is planning to bring this up to the next TSC meeting regarding adding VS2022 support.

**Comment by amzn-changml** [comment]
> I think we should swap around the https://github.com/o3de/o3de/blob/development/scripts/build/Platform/Windows/build_config.json#L332-L353 for the VS2019 release build and the VS2022 release build, so that the VS2022 release build is part of AR and the VS2019 release build is part of the nightly.

I can agree with that

> > I think we should swap around the https://github.com/o3de/o3de/blob/development/scripts/build/Platform/Windows/build_config.json#L332-L353 for the VS2019 release build and the VS2022 release build, so that the VS2022 release build is part of AR and the VS2019 release build is part of the nightly.
> 
> That works for me and avoids having to increase the cost of adding a VS2022 node to the AR run. Mike is planning to bring this up to the next TSC meeting regarding adding VS2022 support.

I can agree with that. We can at least utilize the label for a vs2022 enabled node for the purposes of this AR (`windows-vs2022`)

**Pull request merged**
