### PR TITLE
Removing .cgf files from Assets\Editor\Objects Directory

### PR DESCRIPTION
**Pull request by ParasiteSt**
## What does this PR do?
This is a simple PR, just removing some .cgf files that are no longer in use by the editor.

Should resolve this issue
https://github.com/o3de/o3de/issues/2550
## How was this PR tested?

_Please describe any testing performed._
This is my first PR, and I am not sure what should be tested, or needs to be tested?

### CODE REVIEW

**Comment by ParasiteSt** [comment]
There is a couple more on the issue, but I did not remove them as they are in the Automated Testing directory, and I am not sure how testing would work for that either. These are the files, and I can remove them as well if its wanted.
image

**Review by gadams3 — APPROVED** [review]
This is great and should have been done ages ago. Nothing should be using these anymore. I would search the code base to see if there are any references to any of these files. To test, I would just build and make sure the asset processor doesn't have any failures. Launch the editor with the automated testing project active. You can run unit tests from Visual Studio by selecting any one of the test targets in any affected project. Most of the CGF files would probably be referenced from script if at all. They're not used at all in the engine anymore, at least they should not be. You can also run all of the Python automated tests locally but this is just asset removal and the automatic review process should report any issues.

**Comment by ParasiteSt** [comment]
I rebuilt the engine and launched my project with no errors in the AP that have to do with the .cgf files. I am rebuilding the Automated Testing Project with the removal of the rest of the .cgf files to make sure that commit is good to come in.

**Comment by ParasiteSt** [comment]
One small possible problem, I did do a quick check for the automated testing .cgf files, and this one prefab asset does come up with a reference of some kind. Is this going to be an issue if I remove the Lumbertank_body.cgf?
image

**Comment by ParasiteSt** [comment]
I added one last commit that takes care of the Automated Testing project's .cgf files, and also removed the .mtl, and .tif files related to the .cgf files in Automated Testing. If the removal of the textures and material is an unwanted change let me know, but from the looks of it, there is no reason to keep them as no fbx file is using those files.

I also ran the Automated Testing project, and the AP does not have any errors relating to .cgf changes, but I cannot test the one file that referenced the .cgf file as it is not showing up in the AP though it is in the project folder.
image

**Review by mbalfour-amzn — APPROVED** [review]

**Comment by mbalfour-amzn** [comment]
> One small possible problem, I did do a quick check for the automated testing .cgf files, and this one prefab asset does come up with a reference of some kind. Is this going to be an issue if I remove the Lumbertank_body.cgf? It is in a pythontests directory, so I would assume the automatic review should report any issues on this. image

Heh, I'm pretty sure you've found an automated test that ought to be removed as well, though that can get cleaned up separately. This prefab was converted from a slice that looks like it used to reference the legacy assets through components that no longer exist. In converting to the prefab, the comment components remained that described what the test was doing, but all the other components that referenced the meshes were stripped out, so I'm pretty sure the test wouldn't even do anything any longer.

Regardless, since the reference to "lumbertank_body.cgf" is just in the text of a comment component, it shouldn't block removal of the cgfs.

**Comment by gadams3** [comment]
You need to resolve the DCO issues by following the instructions linked in the workflow section. Then the change can be approved and the automated review build started.

**Comment by ParasiteSt** [comment]
I believe I fixed the DCO issue. If not let me know and I may need help getting it fixed.

**Review by cgalvan — APPROVED** [review]
Thanks for doing this!

**Comment by ParasiteSt** [comment]
@cgalvan I am not sure if you kicked off the build, but everything seems to have passed, but someone that is authorized to merge pull requests will have to merge this one.

**Comment by cgalvan** [comment]
> @cgalvan I am not sure if you kicked off the build, but everything seems to have passed, but someone that is authorized to merge pull requests will have to merge this one.

Yep the build has passed, so I have merged now! Thanks again for doing this.

**Comment by AMZN-daimini** [comment]
Fixes #2550

**Pull request merged**
