### PR TITLE
add a check if a view is already registered

### PR DESCRIPTION
**Pull request by kh-huawei**
Proposed quick fix for #9559: Check and assert if a view is registered a second time with a different view tag.

This is the easiest proposed fix in that it just doesn't allow registering a view with a different ViewTag. Not sure if this is a problem, or if using a view for multiple ViewTags is something people want to use.

Unfortunately the only way to unregister a persistent view is to register a different view with the same ViewTag, so this makes the Pipeline somewhat less flexible.

### CODE REVIEW

**Review by cgalvan — APPROVED** [review]

**Review by VickyAtAZ — APPROVED** [review]

**Comment by rgba16f** [comment]
From the AutomatedReview build error it looks like this branch needs updating with the latest code from mainline.

> [2022-07-07T15:57:30.424Z] AssetProcessor: The database in the Cache folder appears to be from a NEWER version of Asset Processor than this one.
[2022-07-07T15:57:30.424Z] To prevent loss of data in the cache for the newer version, this Asset Processor will close.

**Comment by hultonha** [comment]
@kh-huawei could you please merge in latest from development please and then I'll kick off another build. Thanks!

**Comment by kh-huawei** [comment]
i've rebased my branch onto the latest from development.

**Comment by hultonha** [comment]
Thanks @kh-huawei! Just kicked off another build now 👍

**Comment by cgalvan** [comment]
@kh-huawei AR run revealed this compile error:

```
[2022-07-25T16:11:28.306Z] D:/workspace/o3de/Gems/Atom/RPI/Code/Source/RPI.Public/RenderPipeline.cpp(196,18): error C2220: the following warning is treated as an error [D:\workspace\o3de\build\windows\External\RPI-2e3543d9\Code\Atom_RPI.Public.vcxproj]

[2022-07-25T16:11:28.316Z]               auto canRegister = CanRegisterView(viewTag, view.get());

[2022-07-25T16:11:28.316Z]   unity_0_cxx.cxx

[2022-07-25T16:11:28.316Z]                    ^

[2022-07-25T16:11:28.316Z] D:/workspace/o3de/Gems/Atom/RPI/Code/Source/RPI.Public/RenderPipeline.cpp(196,18): warning C4189: 'canRegister': local variable is initialized but not referenced [D:\workspace\o3de\build\windows\External\RPI-2e3543d9\Code\Atom_RPI.Public.vcxproj]

[2022-07-25T16:11:28.316Z]               auto canRegister = CanRegisterView(viewTag, view.get());

[2022-07-25T16:11:28.602Z]                    ^

[2022-07-25T16:11:28.602Z] D:/workspace/o3de/Gems/Atom/RPI/Code/Source/RPI.Public/RenderPipeline.cpp(272,18): warning C4189: 'canRegister': local variable is initialized but not referenced [D:\workspace\o3de\build\windows\External\RPI-2e3543d9\Code\Atom_RPI.Public.vcxproj]

[2022-07-25T16:11:28.602Z]               auto canRegister = CanRegisterView(viewTag, view.get());

[2022-07-25T16:11:28.859Z]                    ^
```

**Comment by kh-huawei** [comment]
Re-based again, and moved the call to the function inside the AZ_Assert, so it's not even called in release mode.

**Comment by cgalvan** [comment]
@kh-huawei Thanks! I've kicked off a new AR run now

**Comment by cgalvan** [comment]
@kh-huawei The builds were successful but this unit test now fails

```
[2022-07-27T16:57:59.635Z] [ RUN      ] RenderPipelineTests.ViewFunctionsTest
[2022-07-27T16:57:59.635Z] D:\workspace\o3de\Code\Framework\AzCore\AzCore/UnitTest/UnitTest.h(175): error: View [testViewB] is already registered for persistent ViewTag [viewTag1].
[2022-07-27T16:57:59.635Z] 
[2022-07-27T16:57:59.635Z] D:\workspace\o3de\Code\Framework\AzCore\AzCore/UnitTest/UnitTest.h(175): error: View [testViewB] is already registered for persistent ViewTag [viewTag1].
[2022-07-27T16:57:59.635Z] 
[2022-07-27T16:57:59.635Z] D:/workspace/o3de/Gems/Atom/RPI/Code/Source/RPI.Public/RenderPipeline.cpp(271): error: View [testViewB] is already registered for ViewTag [viewTag2].
[2022-07-27T16:57:59.635Z] [  FAILED  ] RenderPipelineTests.ViewFunctionsTest (12 ms)
```

**Comment by kh-huawei** [comment]
This unit test failed somewhat by design, since this PR explicitly added this check.
I've updated the Unit Test now so that it passes, and i hope that is an okay thing to do for a PR.

**Comment by cgalvan** [comment]
> This unit test failed somewhat by design, since this PR explicitly added this check. I've updated the Unit Test now so that it passes, and i hope that is an okay thing to do in a PR.

Yep I agree, this is an appropriate instance where it was OK to modify the failing unit test since as you pointed out this exact behavior was modified. Thanks for updating the unit test and expanding to validate this case! I've kicked off a new AR.

**Pull request merged**
