### PR TITLE
Remove unused 3rd parameter for AZ_CLASS_ALLOCATOR.

### PR DESCRIPTION
**Pull request by Jackie9527**
Signed-off-by: Jackie9527 <80555200+Jackie9527@users.noreply.github.com>

## What does this PR do?

The 3rd parameter of `AZ_CLASS_ALLOCATOR` is useless, which could be misleading.

The old style as follows:
```
AZ_CLASS_ALLOCATOR(AutomatedTestingModule, AZ::SystemAllocator, 0);
```

Here is recommended:
```
AZ_CLASS_ALLOCATOR(AutomatedTestingModule, AZ::SystemAllocator);
```

## How was this PR tested?
Verified by running UT cases, such as:
remove-unused-3rd-param-01
remove-unused-3rd-param-02
remove-unused-3rd-param-03
remove-unused-3rd-param-04
remove-unused-3rd-param-05
remove-unused-3rd-param-06

### CODE REVIEW

**Review by burelc-amzn — APPROVED** [review]
Thanks so much for this!

**Review by rgba16f — APPROVED** [review]

**Review by mbalfour-amzn — APPROVED** [review]

**Comment by lawsonamzn** [comment]
Won't this break all 3rd party customer gems?  We try to avoid doing this.  (Is there a way to make the old macro still work?)

**Review by gadams3 — APPROVED** [review]

**Comment by lumberyard-employee-dm** [comment]
@Jackie9527 Can you post the script or command you used to perform the replacement?

**Comment by mbalfour-amzn** [comment]
> Won't this break all 3rd party contributor / partner gems? We try to avoid doing this. (Is there a way to make the old macro still work?)

I don't see a change to the macro definition itself in Memory.h, so I _think_ this is just changing all the engine uses of the macro, not the macro itself?

**Comment by lawsonamzn** [comment]
I hope all the folks shipping this did the same check as I did, but I checked out that repo, added an old style allocator (with the ,0) to it, ensured it still worked.  Then I also did a 
```
git diff dc444c414 | grep -v -i CLASS_ALLOCATOR | grep -i "+++"```
 to ensure that there were no other changes except for changes to class allocator lines.

Confirmed.  Shipit.

**Review by lawsonamzn — APPROVED** [review]

**Comment by spham-amzn** [comment]
> I hope all the folks shipping this did the same check as I did, but I checked out that repo, added an old style allocator (with the ,0) to it, ensured it still worked. Then I also did a
> 
> ```
> git diff dc444c414 | grep -v -i CLASS_ALLOCATOR | grep -i "+++"
> ```
> 
> to ensure that there were no other changes except for changes to class allocator lines.
> 
> Confirmed. Shipit.

Very Unix-y! I like it

**Comment by Jackie9527** [comment]
> @Jackie9527 Can you post the script or command you used to perform the replacement?

I used VSCode to search, check and replace.
The key word is `Allocator, 0)`, which is replaced to `Allocator)`.

**Comment by lumberyard-employee-dm** [comment]
> > @Jackie9527 Can you post the script or command you used to perform the replacement?
> 
> I used VSCode to search, check and replace. The key word is `Allocator, 0)`, which is replaced to `Allocator)`.

Thanks for posting the command, I verified it the search only catches `AZ_CLASS_ALLOCATOR` lines using bash
```bash
$ find . \( -name "*.cpp" -o -name "*.h" -o -name "*.hxx" \) -exec grep -F "Allocator, 0)" {} \; > allocator.txt
$ awk '{ $1=$1; print }' < allocator.txt | sort > sorted.txt
```

It takes a while to run, but it outputs a sorted file of lines that only start with AZ_CLASS_ALLOCATOR*
[sorted.txt](https://github.com/o3de/o3de/files/10712607/sorted.txt)

**Review by lumberyard-employee-dm — APPROVED** [review]

**Comment by AMZN-daimini** [comment]
Hi there, automated review failed with some error, see report here:
https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/PR-14530/3/pipeline/531

You may also need to pull latest to resolve the conflicts that have arisen since last week.
Let me know when this is fixed and I can start AR again :)

**Comment by Jackie9527** [comment]
> Hi there, automated review failed with some error, see report here: https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/PR-14530/3/pipeline/531
> 
> You may also need to pull latest to resolve the conflicts that have arisen since last week. Let me know when this is fixed and I can start AR again :)

done, the branch has been rebased using the latest commit [4f5259babfc5d4d7f05587e4c1d86b5de3bcb8ec].

**Comment by lumberyard-employee-dm** [comment]
> > Hi there, automated review failed with some error, see report here: https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/PR-14530/3/pipeline/531
> > You may also need to pull latest to resolve the conflicts that have arisen since last week. Let me know when this is fixed and I can start AR again :)
> 
> done, the branch has been rebased using the latest commit [[4f5259b](https://github.com/o3de/o3de/commit/4f5259babfc5d4d7f05587e4c1d86b5de3bcb8ec)].

Another build is in progress at https://jenkins.build.o3de.org/job/O3DE/job/PR-14530/

**Comment by Jackie9527** [comment]
> Hi there, automated review failed with some error, see report here: https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/PR-14530/3/pipeline/531
> 
> You may also need to pull latest to resolve the conflicts that have arisen since last week. Let me know when this is fixed and I can start AR again :)

Good news is that most of the testcases are passed, only one is failed.
Bad news is that I don't know how to fix that, because I have run AzCore.Tests successfully on my machine.
image

**Comment by lumberyard-employee-dm** [comment]
> > Hi there, automated review failed with some error, see report here: https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/PR-14530/3/pipeline/531
> > You may also need to pull latest to resolve the conflicts that have arisen since last week. Let me know when this is fixed and I can start AR again :)
> 
> Good news is that most of the testcases are passed, only one is failed. Bad news is that I don't know how to fix that, because I have run AzCore.Tests successfully on my machine. image

The failure that occurred in the AzCore.Tests was in the `Parallel_Thread.Test`, which is currently unstable and there is a github issue to address it (https://github.com/o3de/o3de/issues/14536).
I have re-kicked off another build and it should pass this time.

**Pull request merged**
