### PR TITLE
Add support for getting value from enums defined with AZ_ENUM_CLASS_WITH_UNDERLYING_TYPE in PropertyTreeEditor.GetProperty

### PR DESCRIPTION
**Pull request by AMZN-daimini**
Mirrors https://github.com/o3de/o3de/pull/8763 for GetProperty.

Verified with this script:
```
import azlmbr
import azlmbr.bus as bus
import azlmbr.editor as editor
import azlmbr.entity as entity
import azlmbr.math as math
from azlmbr.entity import EntityId

# Create Entity
entityId = editor.ToolsApplicationRequestBus(bus.Broadcast, 'CreateNewEntity', EntityId())

# Add Light Component
typeIdsList = editor.EditorComponentAPIBus(bus.Broadcast, 'FindComponentTypeIdsByEntityType', ["Light"], entity.EntityType().Game)
componentOutcome = editor.EditorComponentAPIBus(bus.Broadcast, 'AddComponentsOfType', entityId, typeIdsList)

# Get ComponentEntityIdPair
components = componentOutcome.GetValue()
component = components[0]

# Set Shadow Map Size
shadowMapSizePath =  'Controller|Configuration|Shadows|Shadowmap size'
outcome = editor.EditorComponentAPIBus(bus.Broadcast, "SetComponentProperty", component, shadowMapSizePath, 512)

# Get Shadow Map Size
outcome = editor.EditorComponentAPIBus(bus.Broadcast, 'GetComponentProperty', component, shadowMapSizePath)
if(outcome.IsSuccess()):
    newValue = outcome.GetValue()
    print(newValue)
```

Before, it would fail and print this
```
(python) - The type (Render::ShadowmapSize) does not implement the __str__ method or did not return a valid value, trying __repr__.
[Warning] (python) - The type (Render::ShadowmapSize) does not implement the __repr__ method.
(python_test) - <Render::ShadowmapSize via PythonProxyObject at 2317630735144>
(python_test) -
```

After this change, it succeeds and prints the value as expected
```
512
```

### CODE REVIEW

**Review by hultonha — APPROVED** [review]
Change looks good, but would be even better if we checked in the test script in the description as a test at the same time 😛

**Comment by AMZN-daimini** [comment]
Changed the implementation to still allow material fields to work as intended. Will run AR again once it goes green.

**Comment by AMZN-daimini** [comment]
> Change looks good, but would be even better if we checked in the test script in the description as a test at the same time 😛

The bug was filed while writing automation tests, so it will be covered by the tests using it :)

**Comment by hultonha** [comment]
> > Change looks good, but would be even better if we checked in the test script in the description as a test at the same time 😛
> 
> The bug was filed while writing automation tests, so it will be covered by the tests using it :)

Awesome! 😄 Thanks for the info 🙂

**Pull request merged**
