### PR TITLE
Fix camera transforms being reset when switching to default editor camera

### PR DESCRIPTION
**Pull request by srikappa-amzn**
Problem:
A recent PR made some changes to the way default editor camera works : https://github.com/o3de/o3de/pull/4627/files . 
As part of that PR, [this change](https://github.com/o3de/o3de/blob/026919c11bf771957600dc6350cd78b8aaa5dc39/Code/Editor/EditorViewportWidget.cpp#L2019-L2020) was introduced which modifies the view matrix of the default camera when switching from a custom camera to the default camera. But the active camera is still the custom one, which gets notified when the view matrix changes from [this code](https://github.com/o3de/o3de/blob/development/Gems/Camera/Code/Source/CameraComponentController.cpp#L196-L202) . That will make the active camera's transform component get overridden with the default editor camera's transform component resulting in https://github.com/o3de/o3de/issues/2795

Solution:
Do the view matrix update of the default camera after the atom view is updated. By doing so, the previously conntect handlers to the view matrix change handlers to the viewport context will be disconnected first [using this code](https://github.com/o3de/o3de/blob/bcfe3d38786abd850fd5f88f3d967de7e282be11/Gems/Atom/RPI/Code/Source/RPI.Public/ViewportContext.cpp#L238-L239), which will prevent the previously used camera from getting modified.

Testing:
Tested with 3 cameras(default one, camera in an entity in the level, camera in a prefab in the level). Was able to freely switch between the 3 cameras without any issues.

### CODE REVIEW

**Review by cgalvan — APPROVED** [review]

**Review by chiyenteng — APPROVED** [review]

**Review by NicholasVanSickle — APPROVED** [review]
Nice catch, LGTM

**Review by AMZN-mnaumov — APPROVED** [review]

**Review by AMZN-Igarri — APPROVED** [review]
Nice one! LGTM!

**Comment by hultonha** [comment]
Does this also relate to https://github.com/o3de/o3de/issues/2734? Would be great to check

Also this is exactly the sort of thing that it would be fantastic to have a test for, I'll see if I can work with @AMZN-Igarri to set one up as that will help us stop playing whack-a-mole with these bugs

**Comment by srikappa-amzn** [comment]
> Does this also relate to #2734? Would be great to check
> 
> Also this is exactly the sort of thing that it would be fantastic to have a test for, I'll see if I can work with @AMZN-Igarri to set one up as that will help us stop playing whack-a-mole with these bugs

Can't reproduce #2374 after this change. 

And I totally agree with you on having tests for viewport camera selector widget. I did put some breakpoints in the code to see if this code has any tests written around it so that I can modify/add a test. But unfortunately there isn't a test fixture for any of this. Since this code is pretty new to me, I've discussed with @AMZN-Igarri and he agreed to adding tests for the widget. I created a follow up issue for this : https://github.com/o3de/o3de/issues/5400

**Comment by hultonha** [comment]
Thanks for the update @srikappa-amzn, I'd be inclined to close https://github.com/o3de/o3de/issues/2734 but @AMZN-daimini might want to double check too? I'll see if I can repro tomorrow too and if not I can close it out 👍

**Pull request merged**
