### PR TITLE
PipelineState build fix for non-unity builds

### PR DESCRIPTION
**Pull request by SergeyAMZN**
Signed-off-by: Sergey Pereslavtsev <pereslav@amazon.com>

### CODE REVIEW

**Review by moraaar — APPROVED** [review]
LGTM

**Review by lawsonamzn — APPROVED** [review]
But why?  Did someone 'using namespace' at global scope??

**Review by srikappa-amzn — APPROVED** [review]

**Comment by SergeyAMZN** [comment]
> But why? Did someone 'using namespace' at global scope??

We have lots of `using namespace AZ;` in the global scope inside .cpp files

**Comment by lumberyard-employee-dm** [comment]
> > But why? Did someone 'using namespace' at global scope??
> 
> We have lots of `using namespace AZ;` in the global scope inside .cpp files

This isn't the [first time](https://github.com/o3de/o3de/pull/7184) this has bit us.

We need to perform a pass to eradicate `using namespace` at both global and namespace scope.

**Pull request merged**
