### PR TITLE
Fix some debug compile errors introduced by https://github.com/o3de/o3de/pull/3903

### PR DESCRIPTION
**Pull request by bosnichd**
Signed-off-by: bosnichd <bosnichd@amazon.com>

### CODE REVIEW

**Review by amznestebanpapp — APPROVED** [review]

**Comment by amznestebanpapp** [comment]
FYI @nemerle

**Review by lawsonamzn — APPROVED** [review]
Weird how IsOrthoNormal just disappeard.  I'm guessing it was ONLY used in debug inside asserts, and thus the linter suggested it was unused.

**Review by lumberyard-employee-dm — APPROVED** [review]

**Review by AMZN-daimini — APPROVED** [review]

**Comment by nemerle** [comment]
Mea culpa guys :disappointed: The problem boils down to the length of a single build ( especially since those have to be done in non-unity fashion )

**Comment by bosnichd** [comment]
> Weird how IsOrthoNormal just disappeard. I'm guessing it was ONLY used in debug inside asserts, and thus the linter suggested it was unused.

Yeah, it was only being used inside asserts, which it seems we have #defined to AZ_Assert when USE_AZ_ASSERT is #defined, which then compiles to nothing in debug.

I probably could have just removed the asserts themselves (like I did for the one in Cry_Camera.h), because the asserts don't do anything unless in debug, and they are all in legacy code, but by the time I realised that I had already resurrected the function instead, and considering we want to remove this whole file at some point soon anyway I figured it's not a big deal either way.

**Comment by bosnichd** [comment]
> Mea culpa guys 😞 The problem boils down to the length of a single build ( especially since those have to be done in non-unity fashion ), each build pair (windows+linux) would add ~3h to a single iteration.

All good! Didn't take long to fix at all. This legacy code is a minefield, and there's always going to be some variation of build/configuration we don't catch when removing significant amounts of code like this. But the more we chip away at it the less problems it will cause, and I would speculate that the cumulative time saved by devs not having to compile all this unused stuff anymore far outweighs the small inconvenience of debug being broken for a few hours, so your efforts to help get rid of it all are truly appreciated:)

**Comment by amznestebanpapp** [comment]
> > Mea culpa guys 😞 The problem boils down to the length of a single build ( especially since those have to be done in non-unity fashion ), each build pair (windows+linux) would add ~3h to a single iteration.

+1 dont worry, some builds are expected to be broken (thats why they are not blocking merges).
Something that can help in the future is to use debug for these things since debug is a superset of profile (and profile a superset of release). However, this is not the best way for every change, e.g. if enabling unused warnings, was better to go the other way around.

**Pull request merged**
