### PR TITLE
bugfix: resolve tab order problem with component window for propertyAssetCtrl

### PR DESCRIPTION
**Pull request by pollend**
ref issue: https://github.com/o3de/o3de/issues/9130

### CODE REVIEW

**Review by amzn-jillich — APPROVED** [review]

**Review by hultonha — COMMENTED** [review]
The change looks good but I want to check is there anything else going on with the usage by Physics specifically. Does this also fix this issue - https://github.com/o3de/o3de/issues/4994? I just want to verify there isn't anything else Physics specific that's wrong here. Might also be worth testing out some of the other controls to ensure nothing else breaks (tagging @AMZN-daimini and @cgalvan for visibility as they are likely best placed to review this)

**Review by gadams3 — APPROVED** [review]

**Review by cgalvan — APPROVED** [review]

**Comment by cgalvan** [comment]
> > The change looks good but I want to check is there anything else going on with the usage by Physics specifically. Does this also fix this issue - #4994? I just want to verify there isn't anything else Physics specific that's wrong here. Might also be worth testing out some of the other controls to ensure nothing else breaks (tagging @AMZN-daimini and @cgalvan for visibility as they are likely best placed to review this)
> 
> I'm pretty sure that is a different control, anyways this is just related to tab order where you tab to the next control. don't think it would be related. the controls this change affects on PhysxCollider is Physx Mesh, and Library.

Sorry @hultonha  I don't think this will fix that other issue :(  Like pollend pointed out, this is to fix the tab order for asset fields, not the tag field like in the issue you mentioned.

Also, while this is a nice fix, I don't think this will fix #9130 because it mentions not being able to tab between the X/Y/Z fields which is for a vector control, not an asset property.

**Comment by cgalvan** [comment]
@pollend It looks like the development branch was red when your branch was created. Could you please pull in latest development to your branch so I can kick off a new AR build?

**Comment by pollend** [comment]
> > > The change looks good but I want to check is there anything else going on with the usage by Physics specifically. Does this also fix this issue - #4994? I just want to verify there isn't anything else Physics specific that's wrong here. Might also be worth testing out some of the other controls to ensure nothing else breaks (tagging @AMZN-daimini and @cgalvan for visibility as they are likely best placed to review this)
> > 
> > 
> > I'm pretty sure that is a different control, anyways this is just related to tab order where you tab to the next control. don't think it would be related. the controls this change affects on PhysxCollider is Physx Mesh, and Library.
> 
> Sorry @hultonha I don't think this will fix that other issue :( Like pollend pointed out, this is to fix the tab order for asset fields, not the tag field like in the issue you mentioned.
> 
> Also, while this is a nice fix, I don't think this will fix #9130 because it mentions not being able to tab between the X/Y/Z fields which is for a vector control, not an asset property.

it fixes that to Physx Mesh is using the same component :D

**Comment by pollend** [comment]
Collision Layer, Collides With and Trigger are not included in that list so they are not included in the tab order that is another problems.

**Comment by pollend** [comment]
> > > The change looks good but I want to check is there anything else going on with the usage by Physics specifically. Does this also fix this issue - #4994? I just want to verify there isn't anything else Physics specific that's wrong here. Might also be worth testing out some of the other controls to ensure nothing else breaks (tagging @AMZN-daimini and @cgalvan for visibility as they are likely best placed to review this)
> > 
> > 
> > I'm pretty sure that is a different control, anyways this is just related to tab order where you tab to the next control. don't think it would be related. the controls this change affects on PhysxCollider is Physx Mesh, and Library.
> 
> Sorry @hultonha I don't think this will fix that other issue :( Like pollend pointed out, this is to fix the tab order for asset fields, not the tag field like in the issue you mentioned.
> 
> Also, while this is a nice fix, I don't think this will fix #9130 because it mentions not being able to tab between the X/Y/Z fields which is for a vector control, not an asset property.

I would be interested in looking at that issue as well.

**Comment by hultonha** [comment]
Thanks for the info @cgalvan, j just wanted to double check 🙂 Thanks for the updated info @pollend, I'll try kick off a build later today 👍

**Pull request merged**
