### PR TITLE
Add options to FBX settings which allow re-computing normals based on geometry

### PR DESCRIPTION
**Pull request by yuriy0**

### CODE REVIEW

**Comment by yuriy0** [comment]
This also changes the default tangent method to "MikkT" (was "FromSource") which might be undesired

**Comment by amznestebanpapp** [comment]
@yuriy0 seems this PR is still being worked on, if that is the case, I suggest to move it to Draft until its ready to be reviewed and moved forward.
If there is anything we can help with to expedite this, let us know.

**Comment by rainbj** [comment]
Hi team, it sounds if we plan on just adding this feature as a button, or drop-down, or toggle switch. When you are ready can you attach a screenshot so Sig-UX can sign off on this ticker. Overall we are good with the functional direction. Thanks

**Comment by rainbj** [comment]
@amzn-jillich is this ticket still being worked on?

**Comment by yuyihsu** [comment]
We will close this ticket since the last activity was from Nov 2021, and no one has been working on this one since then. Please feel free to open the ticket later if new activity is needed.

**Pull request closed without merging**
