### PR TITLE
feat(EmotionFX): add rotation manipulator for RotationParameter

### PR DESCRIPTION
**Pull request by pollend**
one thing to note is how is this going to be used in practice seems kind of inconvenient to have the manipulator sit at 0,0,0? I would imagine this following the position of another parameter or parenting this to an existing bone. 

- add RotationManipulator for atom viewport
- remove MCore RotateManipulator
- fixed include paths 

https://user-images.githubusercontent.com/854359/174221449-6af8f018-adc9-42dd-97da-035753e48588.mp4

Signed-off-by: Michael Pollind <mpollind@gmail.com>

### CODE REVIEW

**Comment by amzn-rhhong** [comment]
Great PR. But I think we should definitely get the rotation manipulator to snap to the character, not always staying at 0,0,0

**Review by amzn-rhhong — CHANGES_REQUESTED** [review]
Make sure the rotation manipulator follows the character too

**Comment by pollend** [comment]
https://user-images.githubusercontent.com/854359/174825534-d703c58f-a88f-4432-b528-f7d36f7bfb37.mp4

**Comment by cgalvan** [comment]
@pollend Got some errors on the AR run
```
[2022-06-21T16:07:45.900Z] D:/workspace/o3de/Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ParameterEditor/RotationParameterEditor.cpp(146,75): error C2220: the following warning is treated as an error [D:\workspace\o3de\build\windows\External\EMotionFX-78fb240e\Code\EMotionFX.Editor.Static.vcxproj]

[2022-06-21T16:07:45.909Z]       void RotationParameterEditor::OnTick(float delta, AZ::ScriptTimePoint timePoint)

[2022-06-21T16:07:45.909Z]                                                                             ^

[2022-06-21T16:07:45.909Z] D:/workspace/o3de/Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ParameterEditor/RotationParameterEditor.cpp(146,75): warning C4100: 'timePoint': unreferenced formal parameter [D:\workspace\o3de\build\windows\External\EMotionFX-78fb240e\Code\EMotionFX.Editor.Static.vcxproj]

[2022-06-21T16:07:45.909Z]       void RotationParameterEditor::OnTick(float delta, AZ::ScriptTimePoint timePoint)

[2022-06-21T16:07:45.909Z]                                                                             ^

[2022-06-21T16:07:45.909Z] D:/workspace/o3de/Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ParameterEditor/RotationParameterEditor.cpp(146,48): warning C4100: 'delta': unreferenced formal parameter [D:\workspace\o3de\build\windows\External\EMotionFX-78fb240e\Code\EMotionFX.Editor.Static.vcxproj]

[2022-06-21T16:07:45.909Z]       void RotationParameterEditor::OnTick(float delta, AZ::ScriptTimePoint timePoint)

[2022-06-21T16:07:45.909Z]                                                  ^

[2022-06-21T16:07:47.284Z] --------------------------------------------------------------------------------
```

**Comment by pollend** [comment]
> @pollend Got some errors on the AR run
> 
> ```
> [2022-06-21T16:07:45.900Z] D:/workspace/o3de/Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ParameterEditor/RotationParameterEditor.cpp(146,75): error C2220: the following warning is treated as an error [D:\workspace\o3de\build\windows\External\EMotionFX-78fb240e\Code\EMotionFX.Editor.Static.vcxproj]
> 
> [2022-06-21T16:07:45.909Z]       void RotationParameterEditor::OnTick(float delta, AZ::ScriptTimePoint timePoint)
> 
> [2022-06-21T16:07:45.909Z]                                                                             ^
> 
> [2022-06-21T16:07:45.909Z] D:/workspace/o3de/Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ParameterEditor/RotationParameterEditor.cpp(146,75): warning C4100: 'timePoint': unreferenced formal parameter [D:\workspace\o3de\build\windows\External\EMotionFX-78fb240e\Code\EMotionFX.Editor.Static.vcxproj]
> 
> [2022-06-21T16:07:45.909Z]       void RotationParameterEditor::OnTick(float delta, AZ::ScriptTimePoint timePoint)
> 
> [2022-06-21T16:07:45.909Z]                                                                             ^
> 
> [2022-06-21T16:07:45.909Z] D:/workspace/o3de/Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ParameterEditor/RotationParameterEditor.cpp(146,48): warning C4100: 'delta': unreferenced formal parameter [D:\workspace\o3de\build\windows\External\EMotionFX-78fb240e\Code\EMotionFX.Editor.Static.vcxproj]
> 
> [2022-06-21T16:07:45.909Z]       void RotationParameterEditor::OnTick(float delta, AZ::ScriptTimePoint timePoint)
> 
> [2022-06-21T16:07:45.909Z]                                                  ^
> 
> [2022-06-21T16:07:47.284Z] --------------------------------------------------------------------------------
> ```

look like I need to mark them as unused ...

**Review by amzn-rhhong — APPROVED** [review]

**Pull request merged**
