### PR TITLE
Added missing EntityId.h include to FocusModeInterface.h

### PR DESCRIPTION
**Pull request by lumberyard-employee-dm**
Signed-off-by: lumberyard-employee-dm <56135373+lumberyard-employee-dm@users.noreply.github.com>

relates to #4264

### CODE REVIEW

**Review by AMZN-daimini — APPROVED** [review]
This didn't get flagged in my AR run for some reason, thanks for fixing it :)

**Review by srikappa-amzn — APPROVED** [review]

**Comment by lumberyard-employee-dm** [comment]
> 
> 
> This didn't get flagged in my AR run for some reason, thanks for fixing it :)

AR doesn't run Linux builds with unity off.
So another source file added the include of EntityId.h most likely in unity builds

**Review by gadams3 — APPROVED** [review]

**Review by srikappa-amzn — APPROVED** [review]

**Review by cgalvan — APPROVED** [review]

**Comment by srikappa-amzn** [comment]
> > This didn't get flagged in my AR run for some reason, thanks for fixing it :)
> 
> AR doesn't run Linux builds with unity off. So another source file added the include of EntityId.h most likely in unity builds

@lumberyard-employee-dm , but it failed the AR run for me. So why does it run with unity off for me on my PR's AR run when it did not do that for @AMZN-daimini  ?

**Comment by lumberyard-employee-dm** [comment]
> 
> 
> > > This didn't get flagged in my AR run for some reason, thanks for fixing it :)
> > 
> > 
> > AR doesn't run Linux builds with unity off. So another source file added the include of EntityId.h most likely in unity builds
> 
> @lumberyard-employee-dm , but it failed the AR run for me. So why does it run with unity off for me on my PR's AR run when it did not do that for @AMZN-daimini ?

Your AR build was using Unity Builds.
It is just that the you most likely modified AzToolsFramework enough, such that the unity file that contains the `PrefabFocusHandler.cpp` no longer contained the the source .cpp before it that added the EntityId.h include.

**Pull request merged**
