### PR TITLE
Slice Level UI Removal | Remove slice-related settings from Editor Preferences.

### PR DESCRIPTION
**Pull request by AMZN-daimini**
## What does this PR do?
Initial PR to start implementing this RFC: 
https://github.com/o3de/sig-content/issues/148

This changes the `IsPrefabSystemEnabled` utility function to always return true. Places that query this function will be reworked to remove the now unnecessary code paths in follow-up PRs.
```
bool Application::IsPrefabSystemEnabled() const
{
    AZ_Warning("Application", false, "'IsPrefabSystemEnabled' is deprecated, the editor only supports prefabs for level editing.");
    return true;
}
```

Only option that was left behind is `Slice Save location` in the `Files` page of the preferences dialog. That is because that setting is used by the UI Editor. I have updated the labeling and description to specify that.

## How was this PR tested?

Manual testing

### CODE REVIEW

**Comment by guillaume-haerinck** [comment]
Hey :) Can it wait until https://github.com/o3de/o3de/pull/17478 is merged ? I want to be able to specify a commit hash where its possible to follow the whole doc in this PR (https://github.com/o3de/o3de.org/pull/2545). You PR will make the optional step of opening slice files with O3DE less straightforward

**Comment by AMZN-daimini** [comment]
> Hey :) Can it wait until #17478 is merged ? I want to be able to specify a commit hash where its possible to follow the whole doc in this PR ([o3de/o3de.org#2545](https://github.com/o3de/o3de.org/pull/2545)). Your PR will make the optional step of opening slice files with O3DE less straightforward

Sure! We could also look into a tag as well.

**Comment by AMZN-daimini** [comment]
Converted to draft :)

**Comment by AMZN-daimini** [comment]
Re-opening since I received confirmation from @guillaume-haerinck that the slice-to-prefab conversion tooling is in.

**Review by forkercat — APPROVED** [review]

**Pull request merged**
