### PR TITLE
feat: remove legacy perforce plugin

### PR DESCRIPTION
**Pull request by pollend**
## What does this PR do?

the legacy perforce plugin just forwards state from the SourceControlAPI. pretty straight forward to consolidate everything underneath the component interface and drop ISourceControl. 

## How was this PR tested?

need to setup a local perforce instance and verify that perforce source control still works.

### CODE REVIEW

**Review by gadams3 — APPROVED** [review]

**Comment by pollend** [comment]
@gadams3 I roughly set this up. Not familiar with perforce or all the expectations

**Review by galibzon — APPROVED** [review]

**Comment by pollend** [comment]
I would like to start getting rid of GetClassFactory

**Comment by nick-l-o3de** [comment]
Is this waiting on another different commit or is it its own thing?  I see another P4 related PR

**Comment by nick-l-o3de** [comment]
I'm okay with this - although soon after, we should see about moving it from AzToolsFramework into extras or something.

**Comment by pollend** [comment]
> I'm okay with this - although soon after, we should see about moving it from AzToolsFramework into extras or something.

yep, this is the first step there is some other code i can remove after dropping the legacy plugin.

**Comment by guillaume-haerinck** [comment]
So is perforce still properly working after this PR ? Like see file status, get latest, check it out ? Its a pretty central feature it would be super annoying to break it

**Comment by pollend** [comment]
> So is perforce still properly working after this PR ? Like see file status, get latest, check it out ? Its a pretty central feature it would be super annoying to break it

this code just forward state to legacy SourceControl code. The actual perforce logic is actually in the editor code.

**Comment by nick-l-o3de** [comment]
Hmm validation failed due to 

```
error C2220: the following warning is treated as an error [D:\workspace\o3de\build\windows\Code\Framework\AzToolsFramework\AzToolsFramework.vcxproj]

       using namespace AzToolsFramework;
                                      ^
Code/Framework/AzToolsFramework/AzToolsFramework/SourceControl/PerforceSettings.cpp(25,37): warning C4515: 'AzToolsFramework': namespace uses itself

**Comment by pollend** [comment]
that's weird i don't think i ran into this?

**Pull request merged**
