### PR TITLE
Allow both , and . as the decimalPoint in double input

### PR DESCRIPTION
**Pull request by jjjoness**
Signed-off-by: John Jones-Steele <jjjoness@amazon.com>

### CODE REVIEW

**Review by mbalfour-amzn — COMMENTED** [review]
Can you provide some context around this change?  On the surface, it looks like invalid.  With a US locale, I would expect "100,000" to mean one hundred thousand, not one hundred.  Isn't this the whole point of _having_ locales?

**Comment by jjjoness** [comment]
I queried this in https://jira.agscollab.com/browse/LYN-4571 and was told by Benjamin Jillich this is how it should be. Personally, I agree with you and we should leave it to locale.

**Comment by lumberyard-employee-dm** [comment]
> I queried this in LYN-4571 and was told by @amzn-jillich this is how it should be. Personally, I agree with you and we should leave it to locale.

Any change like this needs a solution which takes into account the locale of the operating system as @mbalfour-amzn mentioned
The [QLocale](https://doc.qt.io/qt-5/qlocale.html#decimalPoint) instance associated with the QSpinBox widget should be using the locale to determine the decimal separator which is used

**Comment by amzn-jillich** [comment]
Unreal, Unity and Blender all take both, ',' and '.' as decimal separators in value fields. Additionally, this has been a customer pain point reported by multiple users back in the days where EMotion FX was middleware.

**Comment by amzn-leenguy** [comment]
@amzn-jillich I think we should take human readable language over other competitors do. If a regular human reads 100,000 as one hundred thousand, i feel like we should align to that. (this is from a UX POV)

**Comment by lumberyard-employee-dm** [comment]
> Unreal, Unity and Blender all take both, ',' and '.' as decimal separators in value fields. Additionally, this has been a customer pain point reported by multiple users back in the days where EMotion FX was middleware.

It looks like unreal and unity accepts both because they don't use [localized settings](https://answers.unrealengine.com/questions/31977/how-do-i-make-comma-the-decimal-sign.html)
Unity does take into account the locale when [displaying](https://forum.unity.com/threads/decimal-separator-randomly-becoming-something-that-looks-like-a-comma.257708/) the decimal separator.

The issue is that the decimal separator in one locale is the thousand's separator in another locale.
That is why the value should take the locale into account if possible.
While `1,000,000` might be invalid in the [de_DE](https://www.localeplanet.com/icu/de-DE/index.html)`, locale, it is valid in the [en_GB](https://www.localeplanet.com/icu/en-GB/index.html) locale.

That being said @amzn-leenguy, how the number "100,000" is interpreted vs how the words "one-hundred thousand" is not different between cultures and we should take that into account.
In Germany normally, "100,000" would be interpreted as "one-hundred" and England it would be interpreted as "one-hundred thousand".

That is why we need to take the locale into account for the decimal separator

**Comment by mbalfour-amzn** [comment]
@amzn-jillich There are tons of examples of programs that aren't localized 100% correctly, o3de included.  But locales exist _precisely_ to solve localization issues.  I would rather move o3de _towards_ a place in which localization works correctly than _away_ from it.

With proper locale support, I'm having a hard time seeing how this would be a customer pain point.  The number entry ought to correctly support either commas or periods as the decimal separator, it would just _only_ support the one that's correct for the currently-selected locale.  The case it _wouldn't_ support is a single customer switching between them indiscriminately regardless of their chosen locale, but IMO that's a good thing, since it's impossible to know the customer's intent.

**Comment by rainbj** [comment]
Question. Is there any downside with this particular change going in now and then making a new ticket that tracks the localization work needed? Will this harm customers using the product as of now?

**Comment by amzn-jillich** [comment]
I set everything to English (US) so that the screenshots for documentation, meeting invites etc. are in the same language and locale as for US based people, while I use a non-US keyboard with a ',' as comma separator on the numblock. So if we read and adapt to the locale, this already won't work for me and there are many more folks in non-US countries in the same situation.

I imagine this is also the reason why our competitors as well as applications like Blender went that way and why we got customer complains about it back in the days. I don't have more extensive data from user studies.

"If a regular human reads 100,000 as one hundred thousand, i feel like we should align to that."
There are regular humans in other regions that interpret this as 100 ;).

I weight in efficiency to use the tool more than having proper locale support and hope I can still convince you.

**Comment by amzn-jillich** [comment]
Can't we just use the most right comma separator as the actual separator and remove the versions on the left? That way you can copy paste 1.000,000; 1,000.000; 1000; 1000,0; 1000.0 all result in 1000. So when copy pasting from the web it will always be able to handle it unless the format is broken like 1.000,000.000.

**Comment by mbalfour-amzn** [comment]
> Can't we just use the most right comma separator as the actual separator and remove the versions on the left?

In some cases, theoretically yes, but "123,456" simply can't be interpreted from context alone.  We _could_ write logic that only handles separators that can be clearly deduced from context, and falls back on locale when it can't, but we're going to get non-intuitive hard-to-explain behavior when a finger slips and presses the wrong key between comma and period.   For everyone who _isn't_ familiar with the different locale standards, it will look like a bug that it didn't generate an error.

> Question. Is there any downside with this particular change going in now and then making a new ticket that tracks the localization work needed?

If I understand this PR correctly, we would be switching from correct localization behavior to less correct localization behavior, and then making a ticket to at some point switch it back to the correct behavior.  We could get to the goal quicker by not submitting the PR. :)

 > I set everything to English (US) so that the screenshots for documentation, meeting invites etc. are in the same language and locale as for US based people, while I use a non-US keyboard with a ',' as comma separator on the numblock. So if we read and adapt to the locale, this already won't work for me and there are many more folks in non-US countries in the same situation.

Thanks for explaining the scenario, it definitely helps explain the motivation behind the change.  It's an interesting case - wanting to use a default locale that doesn't match the keyboard, but optionally be able to type data in a way that matches the keyboard layout anyways.  Would this scenario be better served by having Editor preferences that let you override the locale just for the application?  Or even set up a Windows hotkey to rapidly switch locales?

**Comment by lumberyard-employee-dm** [comment]
> 
> 
> Question. Is there any downside with this particular change going in now and then making a new ticket that tracks the localization work needed? Will this harm customers using the product as of now?

@rainbj Yes, this will go against expectations of customers using the product with an English locale that were accustomed to the `,` being used as group separator in the Editor
GroupSeparator

It a customer is using a locale where the [group separator](https://doc.qt.io/archives/qt-4.8/qlocale.html#groupSeparator) is ',' previously when they typed a number such as `124,788`m they received a result value of `124788.0`.
With this change, if they typed in a number as `124,788`, they would see the result value as `124.788`

**Comment by jjjoness** [comment]
Is there any way we can get a decision on this, one way or the other? Personally, I feel we should respect the locale even though it is against the way all the other engines currently work.

**Comment by lumberyard-employee-dm** [comment]
> 
> 
> Is there any way we can get a decision on this, one way or the other? Personally, I feel we should respect the locale even though it is against the way all the other engines currently work.

Honestly, this seem like something that is can be put behind a Settings Registry value within the editorpreferences.setreg file 

I am thinking that perhaps adding a decimal separator setting underneath a key of `/Amazon/Preferences/Editor/DecimalSeparatorOverride` would allow users who want to change the decimal separator of the current locale to a different value.
If we do that, we should as expose a setting for overriding the group separator for the thousands place. Perhaps with a key of `/Amazon/Preferences/Editor/GroupSeparatorOverride`

You can look at the [EditorViewportSettings.cpp](https://github.com/o3de/o3de/blob/development/Code/Editor/EditorViewportSettings.cpp) for an example of overriding UI settings using the Settings Registry.
I know @hultonha exposed that. So either @hultonha or I can provide insight on how to expose those UI settings.

**Comment by amznestebanpapp** [comment]
My vote goes to respect the locale and not have this behavior. 
Issues I see:
- this would have to be implemented across ALL UI in the tool. Just implementing it in DoubleSpinBox will make it really confusing because other widgets are not going to have this behavior. We also have tools that don't use AZ widgets, those will also need to implement this.
- creates unexpected behavior for some group of users
- creates input values that are not possible to enter, e.g. if US-locale wants to input "123,456" it will result in "123.456" which is NOT what the user entered. 
- it may make it consistent/easier with some tools, but not every tool does this, e.g. spreadsheets don't do this
- creates unexpected behavior. There is no easy way to tell the user that this is intended. When inputting some values and seeing others in the UI, it will look like a bug.

**Comment by jjjoness** [comment]
It seems the editor settings is the way to go. It covers both opinions and the default respects the locale. If there are no objections, I'll implement this tomorrow.

**Comment by amznestebanpapp** [comment]
> It seems the editor settings is the way to go. It covers both opinions and the default respects the locale. If there are no objections, I'll implement this tomorrow.

If its added as an option, you will have to do a full pass on all the UI elements across the application. Just implementing it in one widget will leave this inconsistent within the tool. Did you get `sig-ui-ux` involved?

@yuyihsu FYI

**Comment by mbalfour-amzn** [comment]
> It seems the editor settings is the way to go. It covers both opinions and the default respects the locale. If there are no objections, I'll implement this tomorrow.

Would this be an Editor setting that sets the default locale for the application (I guess through QLocale::setDefault?) , or individual settings to override decimalPoint, groupSeparator, and potentially other locale settings over time, or both?
https://doc.qt.io/qt-5/qml-qtqml-locale.html

It seems like if we're going the route of overriding locale settings, this should affect _all_ Qt locale usage, and not just the double spinbox.

**Comment by amzn-leenguy** [comment]
After discussing with the UX team: Our final decision here is that we should respect the local, but there's some middleware conversations that need to happen: when does commas (,) and decimals (.) change and how.

Please paused the submission of this ticket to mainline, until UX has dived deeper on this.

CC @yuyihsu @rainbj

**Review by amzn-leenguy — COMMENTED** [review]
.

**Comment by yuyihsu** [comment]
Hi All, after discussing with @amzn-jillich and @amznestebanpapp , we will go with the following behavior-
- The QT widget should read the system locale settings. If user is in a locale that recognize "," as decimal point, then the qt widget should behave that way.
- There shouldn't be any additional settings required in the O3DE preference page. O3DE should read the system locale settings by default.

So please hold off the PR until we can fix this issue the correct way, and resubmit. Thanks.

**Comment by jjjoness** [comment]
This is the way it works at the moment. So we should just close this PR ?

**Pull request closed without merging**
