### PR TITLE
AssetBrowser SearchFilteringTest: Added delay when inserting a string to the search file.

### PR DESCRIPTION
**Pull request by AMZN-Igarri**
Added a delay when entering a string in the search bar in order to catch issues such as #5832

https://user-images.githubusercontent.com/82394219/144096421-5986d56c-1f1a-4413-b5b5-0466ac5e8f24.mp4

image

Signed-off-by: AMZN-Igarri <82394219+AMZN-Igarri@users.noreply.github.com>

### CODE REVIEW

**Review by hultonha — APPROVED** [review]
Looks good! Might be worth adding a comment around this block just to describe why it's there and what it's trying to catch.

Also did you verify the test failed with your other fix removed? Thanks!

**Comment by AMZN-Igarri** [comment]
> Looks good! Might be worth adding a comment around this block just to describe why it's there and what it's trying to catch.
> 
> Also did you verify the test failed with your other fix removed? Thanks!

Sure! I can add a comment.
Yes I verified that the test fails with the fix removed.

**Comment by hultonha** [comment]
> > Looks good! Might be worth adding a comment around this block just to describe why it's there and what it's trying to catch.
> > Also did you verify the test failed with your other fix removed? Thanks!
> 
> Sure! I can add a comment. Yes I verified that the test fails with the fix removed.

Awesome stuff! 😄 Thanks!

**Review by jckand-amzn — COMMENTED** [review]
Is there some sort of event we can wait_for_condition on instead of adding general waits?

**Review by lawsonamzn — APPROVED** [review]
LGTM.  Assuming a 0.5 wait is long enough and catches this kind of bug and its a tiny change.

**Comment by AMZN-Igarri** [comment]
> Is there some sort of event we can wait_for_condition on instead of adding general waits?

Looked into this and I couldn't find a proper event to wait for this case

**Review by jckand-amzn — APPROVED** [review]

**Pull request merged**
