### PR TITLE
Clear search filter when closing dialog

### PR DESCRIPTION
**Pull request by sphrose**
Signed-off-by: sphrose <82213493+sphrose@users.noreply.github.com>

## What does this PR do?
This PR fixes https://github.com/o3de/o3de/issues/12270. The crash only happens with a valid filter term, i.e. one that matches one or more items. Clearing the filter when the dialog is closing solves the problem.

## How was this PR tested?

Multiple runs with the filter in various states.

### CODE REVIEW

**Review by gadams3 — APPROVED** [review]

**Comment by pollend** [comment]
Could you look at how the tree view is getting cleaned up. There is probably a better fix.

**Review by pollend — CHANGES_REQUESTED** [review]
@sphrose something is really weird about this CTreeItem its attached itself to the invisiteRootItem for m_model but its also managed with a unique_ptr. There is some really strange ownership happening here. I think that is probably why it crashing its been freed by m_model but its also getting deleted by the unique_ptr. 

https://doc.qt.io/qt-6/qstandarditem.html#dtor.QStandardItem

**Comment by sphrose** [comment]
> @sphrose something is really funny about CTreeItem its attached itself to the invisiteRootItem for m_model but its also managed with a unique_ptr. There is some really strange ownership happening here. I think that is probably why it crashing its been freed by m_model but its also getting deleted by the unique_ptr.
> 
> https://doc.qt.io/qt-6/qstandarditem.html#dtor.QStandardItem

@pollend That looks like exactly the problem, but it only happens when items are selected by the filter, which is all hidden away inside a QSortFilterProxyModel. A filter with no hits doesn't break, and no filter at all is fine. This leads me to believe that Qt is keeping a reference somewhere internally, although why, and why it should be deleting it is beyond me. I;ll add a comment explaining it.

**Comment by pollend** [comment]
> > @sphrose something is really funny about CTreeItem its attached itself to the invisiteRootItem for m_model but its also managed with a unique_ptr. There is some really strange ownership happening here. I think that is probably why it crashing its been freed by m_model but its also getting deleted by the unique_ptr.
> > https://doc.qt.io/qt-6/qstandarditem.html#dtor.QStandardItem
> 
> @pollend That looks like exactly the problem, but it only happens when items are selected by the filter, which is all hidden away inside a QSortFilterProxyModel. A filter with no hits doesn't break, and no filter at all is fine. This leads me to believe that Qt is keeping a reference somewhere internally, although why, and why it should be deleting it is beyond me. I;ll add a comment explaining it.

I think it makes more sense to fix CTreeItem. might be sufficient to remove the unique_ptr since the root item is already owned under the invisible item in the model.

**Review by pollend — APPROVED** [review]

**Comment by sphrose** [comment]
> > > @sphrose something is really funny about CTreeItem its attached itself to the invisiteRootItem for m_model but its also managed with a unique_ptr. There is some really strange ownership happening here. I think that is probably why it crashing its been freed by m_model but its also getting deleted by the unique_ptr.
> > > https://doc.qt.io/qt-6/qstandarditem.html#dtor.QStandardItem
> > 
> > 
> > @pollend That looks like exactly the problem, but it only happens when items are selected by the filter, which is all hidden away inside a QSortFilterProxyModel. A filter with no hits doesn't break, and no filter at all is fine. This leads me to believe that Qt is keeping a reference somewhere internally, although why, and why it should be deleting it is beyond me. I;ll add a comment explaining it.
> 
> I think it makes more sense to fix CTreeItem. might be sufficient to remove the unique_ptr since the root item is already owned under the invisible item in the model. clearing the filter might just mask the problem. Is this the only place this control is used?

Yes, it does seem to be the only place it's used. Your suggestion makes sense, I'll have a look.

**Comment by pollend** [comment]
> > > > @sphrose something is really funny about CTreeItem its attached itself to the invisiteRootItem for m_model but its also managed with a unique_ptr. There is some really strange ownership happening here. I think that is probably why it crashing its been freed by m_model but its also getting deleted by the unique_ptr.
> > > > https://doc.qt.io/qt-6/qstandarditem.html#dtor.QStandardItem
> > > 
> > > 
> > > @pollend That looks like exactly the problem, but it only happens when items are selected by the filter, which is all hidden away inside a QSortFilterProxyModel. A filter with no hits doesn't break, and no filter at all is fine. This leads me to believe that Qt is keeping a reference somewhere internally, although why, and why it should be deleting it is beyond me. I;ll add a comment explaining it.
> > 
> > 
> > I think it makes more sense to fix CTreeItem. might be sufficient to remove the unique_ptr since the root item is already owned under the invisible item in the model. clearing the filter might just mask the problem. Is this the only place this control is used?
> 
> Yes, it does seem to be the only place it's used. Your suggestion makes sense, I'll have a look.

do you plan to work on a more permanent fix? I think this is good for now, will probably find another situation where this crashes.

**Pull request merged**
