### PR TITLE
Editor code: tidy up BOOLs,NULLs and overrides

### PR DESCRIPTION
**Pull request by nemerle**
A few 'typedefs' replaced by 'using's 

This shouldn't have any functional changes at all, just c++17 modernization

Parts of this PR come from #2252

Signed-off-by: nemerle <96597+nemerle@users.noreply.github.com>

### CODE REVIEW

**Comment by hultonha** [comment]
Oh wow I didn't quite realize just how many files were going to have been modified 😅

Even with mechanical style conversions like this, having 100+ files in a PR is still a big ask for reviewers 😬 Is there any way to potentially split up this change into separate PRs (say by doing a collection of directories at a time?).

I'll have a look through now but it might be easier to have maybe 2-3 separate PRs that have these changes in. Sorry to push back, I have to admit I wasn't expecting you to have fixed so much (which is great! 😄) we just want to make the review process as smooth as possible and it might be hard to get more eyes on this in its current form.

**Comment by nemerle** [comment]
I can split this into multiple PRs, sure. I wonder if there's some sane number of changed files we all should aim at in our PR :smile:

**Comment by hultonha** [comment]
Amazing thank you! 🙂

Haha that's a really great question, it gets really tricky as often file count isn't a good metric for change density (if loads of code in three massive files has happened that could possibly be too much...). I think for something like this where there are minimal changes per file and they're all quite simple modifications maybe 40-50 files in a PR is manageable.

For a functional change with code that really needs to be read and understood, an ideal change is likely 10 or less files to be honest (perfect world) though this often isn't the case. Maybe 250-300 lines modified to have the reviewer actually be effective. We'll try and communicate some better guidance about this soon as it's really hard for you to know what to aim for (apologies for that!).

Appreciate you taking the time to split it and I'll get to it asap (and hopefully more engineers will then find the time to look at individual PRs too! 🙂).

**Comment by nemerle** [comment]
Following @hultonha request, this PR has been split into:
#2872 #2873 #2874 #2875 #2876 #2877
Note to reviewers the split PR is meant to ease reviewing, but sadly I cannot say if any part will compile correctly in isolation.
Sadly, building the editor takes quite a long time on the machine I'm using at the moment, and doing it 6 times would likely take the rest of the day :frowning_face:

**Comment by nemerle** [comment]
sig-content ? I'm unsure how is that sig related to this? :thinking:

**Comment by hultonha** [comment]
Oh sorry I just mean that group has reviewers in who have oversight of these files (sig-content covers Editor related things)

**Comment by hultonha** [comment]
Hi @nemerle, I've looked at the first three and left feedback on Pt 2 (1 and 3 are merged) - most likely will get to 3-6 on Monday but I've shared the links around so there might be some other eyes on the changes.

Thanks!

**Pull request closed without merging**
