### PR TITLE
Update the AWSNativeSDK version and hash for Mac

### PR DESCRIPTION
**Pull request by junbo75**
Signed-off-by: junbo <junbo@amazon.com>

- Changes for the package has been reviewed at: https://reviewboard.agscollab.com/r/80308/
- Verified the package on Jenkins: https://jenkins-pipeline.agscollab.com/job/O3DE-LY-FORK/job/LYN-4981/4/
- Package has been promoted to dev: https://jira.agscollab.com/browse/SPEC-4680

### CODE REVIEW

**Review by lumberyard-employee-dm — APPROVED** [review]

**Comment by lumberyard-employee-dm** [comment]
Why is this a draft PR?

**Comment by junbo75** [comment]
> Why is this a draft PR?

I'm running it on Jenkins and also wait for the package becomes available in prod before change the PR for review.

**Comment by junbo75** [comment]
PR is ready for review now.

**Review by onecent1101 — APPROVED** [review]

**Review by lmbr-pip — APPROVED** [review]
LG

**Review by rgba16f — APPROVED** [review]

**Pull request merged**
