### PR TITLE
Fix: Tube spline

### PR DESCRIPTION
**Pull request by tjmgd**
The shape of tube component looks different because of the lack of judgement for the closed state of spline in running state

Signed-off-by: T.J. McGrath-Daly <tj.mcgrath.daly@huawei.com>

### CODE REVIEW

**Review by cgalvan — APPROVED** [review]

**Review by mbalfour-amzn — APPROVED** [review]

**Review by hultonha — APPROVED** [review]
Nice fix! Thanks @tjmgd! 👍 Just kicking off a build now

**Comment by hultonha** [comment]
(Bonus points if you add a screen shot of what it looks like now too 🙂) That's always super helpful, cheers!

**Comment by hultonha** [comment]
@tjmgd Could you please merge latest development into your branch and I'll try another build, ping me when it's done if you can and I'll keep an eye on it. Thanks!

**Comment by tjmgd** [comment]
> @tjmgd Could you please merge latest development into your branch and I'll try another build, ping me when it's done if you can and I'll keep an eye on it. Thanks!

Just updated. Thanks. I'll try get a before and after screenshot when I can.

**Comment by hultonha** [comment]
I've kicked off another build, it potentially looks like a network failure issue with the build machines (I've reached out for more info). Will update if I hear more 👍

**Pull request merged**
