### PR TITLE
Fixed unused variable warning in Release configuration in Linux.

### PR DESCRIPTION
**Pull request by moraaar**
Signed-off-by: moraaar <moraaar@amazon.com>

### CODE REVIEW

**Review by amzn-sean — APPROVED** [review]
lgtm

**Review by hultonha — APPROVED** [review]
Looks good thanks! :+1:

**Comment by Mobs1024** [comment]
stabilization/2110 error

```[ 39%] Built target AtomLyIntegration_CommonFeatures.Static
[ 39%] Built target Vegetation.Static
[ 39%] Building CXX object o3de/Code/Framework/AzToolsFramework/CMakeFiles/AzToolsFramework.dir/Platform/Linux/AzToolsFramework/API/PythonLoader_Linux.cpp.o
/home/xxx/o3de/Code/Framework/AzToolsFramework/Platform/Linux/AzToolsFramework/API/PythonLoader_Linux.cpp:21:19: error: unused variable 'err' [-Werror,-Wunused-variable]
            char* err = dlerror();
                  ^
1 error generated.
gmake[3]: *** [o3de/Code/Framework/AzToolsFramework/CMakeFiles/AzToolsFramework.dir/build.make:4801: o3de/Code/Framework/AzToolsFramework/CMakeFiles/AzToolsFramework.dir/Platform/Linux/AzToolsFramework/API/PythonLoader_Linux.cpp.o] Error 1
gmake[2]: *** [CMakeFiles/Makefile2:6326: o3de/Code/Framework/AzToolsFramework/CMakeFiles/AzToolsFramework.dir/all] Error 2
gmake[2]: *** Waiting for unfinished jobs....
[ 45%] Built target EMotionFXStaticLib
gmake[1]: *** [CMakeFiles/Makefile2:7334: o3de/Code/Editor/CMakeFiles/Editor.dir/rule] Error 2
gmake: *** [Makefile:969: Editor] Error 2
```
what about cherry-pick ?

**Comment by spham-amzn** [comment]
> stabilization/2110 error
> 
> ```
> [ 39%] Built target Vegetation.Static
> [ 39%] Building CXX object o3de/Code/Framework/AzToolsFramework/CMakeFiles/AzToolsFramework.dir/Platform/Linux/AzToolsFramework/API/PythonLoader_Linux.cpp.o
> /home/xxx/o3de/Code/Framework/AzToolsFramework/Platform/Linux/AzToolsFramework/API/PythonLoader_Linux.cpp:21:19: error: unused variable 'err' [-Werror,-Wunused-variable]
>             char* err = dlerror();
>                   ^
> 1 error generated.
> gmake[3]: *** [o3de/Code/Framework/AzToolsFramework/CMakeFiles/AzToolsFramework.dir/build.make:4801: o3de/Code/Framework/AzToolsFramework/CMakeFiles/AzToolsFramework.dir/Platform/Linux/AzToolsFramework/API/PythonLoader_Linux.cpp.o] Error 1
> gmake[2]: *** [CMakeFiles/Makefile2:6326: o3de/Code/Framework/AzToolsFramework/CMakeFiles/AzToolsFramework.dir/all] Error 2
> gmake[2]: *** Waiting for unfinished jobs....
> [ 45%] Built target EMotionFXStaticLib
> gmake[1]: *** [CMakeFiles/Makefile2:7334: o3de/Code/Editor/CMakeFiles/Editor.dir/rule] Error 2
> gmake: *** [Makefile:969: Editor] Error 2
> ```
> 
> what about cherry-pick ?

We are going to merge fixes for stabilization back to development soon

**Comment by moraaar** [comment]
> > stabilization/2110 error
> > ```
> > [ 39%] Built target Vegetation.Static
> > [ 39%] Building CXX object o3de/Code/Framework/AzToolsFramework/CMakeFiles/AzToolsFramework.dir/Platform/Linux/AzToolsFramework/API/PythonLoader_Linux.cpp.o
> > /home/xxx/o3de/Code/Framework/AzToolsFramework/Platform/Linux/AzToolsFramework/API/PythonLoader_Linux.cpp:21:19: error: unused variable 'err' [-Werror,-Wunused-variable]
> >             char* err = dlerror();
> >                   ^
> > 1 error generated.
> > gmake[3]: *** [o3de/Code/Framework/AzToolsFramework/CMakeFiles/AzToolsFramework.dir/build.make:4801: o3de/Code/Framework/AzToolsFramework/CMakeFiles/AzToolsFramework.dir/Platform/Linux/AzToolsFramework/API/PythonLoader_Linux.cpp.o] Error 1
> > gmake[2]: *** [CMakeFiles/Makefile2:6326: o3de/Code/Framework/AzToolsFramework/CMakeFiles/AzToolsFramework.dir/all] Error 2
> > gmake[2]: *** Waiting for unfinished jobs....
> > [ 45%] Built target EMotionFXStaticLib
> > gmake[1]: *** [CMakeFiles/Makefile2:7334: o3de/Code/Editor/CMakeFiles/Editor.dir/rule] Error 2
> > gmake: *** [Makefile:969: Editor] Error 2
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > what about cherry-pick ?
> 
> We are going to merge fixes for stabilization back to development soon

It's the other way around this time, the fix is in development and it would be needed to be brought to stabilization/2110.

**Pull request merged**
