### PR TITLE
Update the folder structure for the AWSMetrics gem following the latest O3DE guidline

### PR DESCRIPTION
**Pull request by junbo75**
Signed-off-by: Junbo Liang <68558268+junbo75@users.noreply.github.com>

- Passed unit tests and end-to-end tests on Windows
- Tested with the AutomatedTesting project on Linux

### CODE REVIEW

**Comment by junbo75** [comment]
> please break it into three PRs and merge it one by one, as we don't need to merge it for GA, we can do it smoothly with following order to reduce the potential impact:
> 
> 1. metrics
> 2. client auth
> 3. core

Talked offline. Will separate this PR into three to reduce the scope.

**Comment by junbo75** [comment]
> Plus we are doing it for public doc, so we may also need to update header comment to make sure they can get generated on doc correctly

Sounds like that work should be addressed in a separate PR other than the current one to fix the folder structure. Feel free to cut new Jira tasks if you find any incorrect header comment.

**Comment by junbo75** [comment]
Broke the PR into three separate PRs based on the discussion with @onecent1101 .

**Review by onecent1101 — APPROVED** [review]

**Review by allisaurus — APPROVED** [review]

**Comment by junbo75** [comment]
Merged from the latest dev and resolved conflict on Gems\AWSCore\Code\CMakeLists.txt.

**Pull request merged**
