### PR TITLE
Multiplayer Auto-Components Using NetworkInput Now Require MultiplayerInputDriver Service

### LINKED ISSUE #3155: Multiplayer NetworkInput Silently Fails Unless LocalPredictionPlayerInputComponent is Attached
**Describe the bug**
Multiplayer components use NetworkInputs, but unless the LocalPredictionPlayerInputComponent is also attached to the entity CreateInput and ProcessInput won't ever get called.  
Basically causing the network inputs to do nothing.  There are no errors or warning in editor to tell the player why input isn't being created or processed.

**Expected behavior**
There should be a warning or restriction which requires components which use network input to also make sure the LocalPredictionPlayerInputComponent is attached.

### PR DESCRIPTION
**Pull request by AMZN-Gene**
Multiplayer Auto-Components now require MultiplayerInputDriver service if they use NetworkInputs.  The only service provider currently is LocalPredictionPlayerInputComponent, but devs can create new MPInputDrivers.  The reason to require the new service is that without adding LocalPredictionPlayerInputComponent CreateInput and ProcessInput will never be called

Fixes #3155

Signed-off-by: Gene Walters <genewalt@amazon.com>

### CODE REVIEW

**Comment by kberg-amzn** [comment]
Definitely like that you made this dependent on actually having network inputs, but this does somewhat prevent a customer from making a non-local prediction player controller that just calls create input on the client and process input on the server, thereby avoiding any local prediction. This is probably a good change regardless to avoid confusion around why things aren't working.

**Comment by AMZN-Gene** [comment]
I thought about customers wanting their own custom controllers as well.  Instead of locking them into LocalPredictionPlayerInputComponent, the LocalPredictionPlayerInputComponent also provide a generic service called something else which any component responsible for creating/processing input would provide.  CRC"NetworkInputHandler" service, ha!

**Comment by kberg-amzn** [comment]
Yeah, right now just due to how we cache components we're not doing the whole generic component service thing, but that is inflexible.. we should probably switch that to component services throughout.

**Comment by AMZN-Gene** [comment]
Sorry, I'm not following... did the way we Provide/Depend/Require/Incompatible service change?

**Comment by AMZN-Gene** [comment]
As an example I updated this use a generic "MutliplayerInputDriver" service.  This way a customer can develop their own class (such as  NonLocalPredictionPlayer) and everything will work if their component provides the  "MutliplayerInputDriver" service.

**Review by kberg-amzn — APPROVED** [review]
Actually this is a decent solution.. Right now when you declare a component relation in autocomponent xml it autogenerates all the required/incompatible services based on the exact component name, not some abstract service name, because it also autogenerates accessors so you can simply call Get<ComponentName>() to access a component related to your multiplayer component. This dramatically reduces all the ebus cross-talk between multiplayer components, but it's not well adapted for the abstract component service architecture due to its usage of exact component names.

I quite like your solution here though, where the responsibility for such abstractions lies strictly outside the realm of autogen.

**Review by AMZN-puvvadar — APPROVED** [review]

**Comment by AMZN-Olex** [comment]
Heads up, I believe this will break Hierarchical Network Entities design. Unless we plan to force Local Player Prediction Input component on, potentially, all entities within a hierarchy? I don't think that would work at all.

**Comment by AMZN-Gene** [comment]
To be specific, this would require any entity **which has a component that uses NetInput** to have a Local Player Prediction Input component on.

**Review by AMZN-Olex — APPROVED** [review]

**Pull request merged**
