### PR TITLE
Fixed the Color Picker color space for materials and lights.

### PR DESCRIPTION
**Pull request by santorac**
## What does this PR do?

Originally the color picker was set to be in sRGB, and configure a Linear sRGB property. This PR https://github.com/o3de/o3de/pull/6812 changed that so the color picker and the property were both treated as sRGB, to make the numbers match. It's understandable that the developer thought this was an improvement, but this change was not actually the correct thing to do. The most common and natural workflow is for artists to work in a sRGB color space, while the material and lighting systems store color values as Linear sRGB. That is why the color picker needs to be configured as it was originally. This should address https://github.com/o3de/o3de/issues/12227 and https://github.com/o3de/o3de/issues/11166

In the long term, we would like to expand the color picker to allow users to select what color space they want to operate in. It may be sRGB by default, but the user could put the color picker in any mode they want. And the output property value will always be linear. In the short term, we plan to make some minor additions that would hopefully alleviate some of the confusion cause by the differing values (see https://github.com/o3de/o3de/pull/12292).

Signed-off-by: santorac <55155825+santorac@users.noreply.github.com>

## How was this PR tested?

I tested the color picker before and after in each of the affected locations: Material Editor's property inspector, Material Editor's viewport settings, Material Component's property inspector, directional light, and an area light (disk).
I used https://ajalt.github.io/colormath/converter/ to check that the conversion from sRGB in the color picker to Linear in the property widget looks correct.

### CODE REVIEW

**Review by gadams3 — APPROVED** [review]

**Review by hultonha — APPROVED** [review]

**Review by cgalvan — APPROVED** [review]

**Review by HogJonny-AMZN — APPROVED** [review]
Well written synopsis, great for tracking the history.

**Comment by hultonha** [comment]
Tagging @sptramer for visibility too, might be worth them and @santorac syncing up briefly on the change and the reasons why it's needed too

**Comment by cgalvan** [comment]
> Tagging @sphrose for visibility too, might be worth them and @santorac syncing up briefly on the change and the reasons why it's needed too

I discussed it in an Editor related meeting earlier. We are also planning to release some sort of user guide or blog post or tutorial in regards to color authoring in the Editor to clear up any confusion and fix up the various touch points of color data authoring in the Editor to have a consistent experience.

**Comment by santorac** [comment]
> > Tagging @sphrose for visibility too, might be worth them and @santorac syncing up briefly on the change and the reasons why it's needed too
> 
> I discussed it in an Editor related meeting earlier. We are also planning to release some sort of user guide or blog post or tutorial in regards to color authoring in the Editor to clear up any confusion and fix up the various touch points of color data authoring in the Editor to have a consistent experience.

Also see this followup PR that should hopefully address the original concern: https://github.com/o3de/o3de/pull/12292

**Comment by hultonha** [comment]
> > > Tagging @sphrose for visibility too, might be worth them and @santorac syncing up briefly on the change and the reasons why it's needed too
> > 
> > 
> > I discussed it in an Editor related meeting earlier. We are also planning to release some sort of user guide or blog post or tutorial in regards to color authoring in the Editor to clear up any confusion and fix up the various touch points of color data authoring in the Editor to have a consistent experience.
> 
> Also see this followup PR that should hopefully address the original concern: #12292

Thanks for the update @santorac and @cgalvan, I just wanted to check @sphrose was in the loop. Cheers!

**Pull request merged**
