### PR TITLE
Fix being able to uninstall gems that have AWS set as the origin

### PR DESCRIPTION
**Pull request by AMZN-Phil**
Any gem that had Amazon Web Services set as the origin was set as a local gem and so not able to be uninstalled. This change does not affect any known existing gems.

Signed-off-by: AMZN-Phil <pconroy@amazon.com>

### CODE REVIEW

**Review by AMZN-alexpete — APPROVED** [review]
Does this still allow AWS gems to be enabled in the Gem Catalog - or does it think they have to be downloaded?

**Comment by AMZN-Phil** [comment]
The existing AWS gems that are part of the o3de install are not affected by this change since they have o3de.org as their origin, the same as all of the other gems currently shipped with o3de. If their origin was changed to AWS or a new gem is created with this set as the origin then that gem would act the same as any other gem, it should work correctly as long as it's registered with the current engine whether downloaded through Project Manager or added from locally on disk.

**Review by lumberyard-employee-dm — COMMENTED** [review]
The logic for determining whether a gem is local to the user machine is quite ad-hoc.
It is not grounded in any data that would indicate that the gem comes with the engine, project or o3de manifest.

It is checking for an "origin" field for specific text which is quite flaky an nothing in the o3de CLI enforces using origin for anything meaningful.

**Comment by Ulrick28** [comment]
@lumberyard-employee-dm, myself and @AMZN-Phil agree, however a solution is going to take a bit to implement and we will need to schedule time for this. This is a middle ground fix until we can design the correct data driven solution. With that being said we need to remove the AWS specific call out asap, therefore this PR cannot wait for the final solution.

**Review by Ulrick28 — APPROVED** [review]
Approved as a temporary measure, but make sure we create a GHI that requests a more complete solution to this issue.

**Review by allisaurus — APPROVED** [review]

**Comment by AMZN-Phil** [comment]
Opened GHI #11159

**Review by AMZN-puvvadar — APPROVED** [review]

**Pull request merged**
