### PR TITLE
Running PhysX python tests in batched mode to avoid parallelization issues to gain stability.

### PR DESCRIPTION
**Pull request by moraaar**
Also ignore a recurrent error when running pytests, which is that it reports `UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 3711: character maps to <undefined>`, which can happen depending on the content of `user` or `TestResult` folders.

Signed-off-by: moraaar <moraaar@amazon.com>

### CODE REVIEW

**Review by spham-amzn — APPROVED** [review]

**Comment by hultonha** [comment]
Is it worth @greerdv syncing this branch locally on their other machine to run the tests over and over to see if the same rate of failures occur?

Were you able to run the tests over and over repeatedly and saw no issues @moraaar?

**Comment by evanchia-ly-sdets** [comment]
I'm also curious on the duration run increase for science purposes :)

**Comment by greerdv** [comment]
Do we have a way of measuring whether this makes things better? Otherwise it just feels like throwing the dice.

**Review by smurly — APPROVED** [review]

**Comment by evanchia-ly-sdets** [comment]
> Do we have a way of measuring whether this makes things better? Otherwise it just feels like throwing the dice.

We have metrics that can monitor for long term data, but as far as local testing I think just running both types multiple times and comparing results would suffice

**Comment by moraaar** [comment]
> Is it worth @greerdv syncing this branch locally on their other machine to run the tests over and over to see if the same rate of failures occur?

Good suggestion. @greerdv do you mind syncing to this change and run it in your setup overnight?

> Were you able to run the tests over and over repeatedly and saw no issues @moraaar?

I run it 5 times locally. All of them passed.

**Comment by moraaar** [comment]
> I'm also curious on the duration run increase for science purposes :)

I'll get that data for you.

**Comment by moraaar** [comment]
> Do we have a way of measuring whether this makes things better? Otherwise it just feels like throwing the dice.

I think that this bug (https://github.com/o3de/o3de/issues/9295) already proves that there is something flaky about running tests in parallel. Also in the discussions with sdets team their recommendation is to use batched mode. Plus we keep seeing totally random physics tests failing, which is similar to the data from the bug. I see this change more as an educated guess rather than throwing the dice. If after this submission there are no more flaky physics tests for many days, that's good. 

Bug I still think it'd be great if you could run it in your cool setup.

**Comment by moraaar** [comment]
> > I'm also curious on the duration run increase for science purposes :)
> 
> I'll get that data for you.

Here you go @evanchia-ly-sdets 

````
In Parallel:
        Start 163: AutomatedTesting::PhysicsTests_Main.main::TEST_RUN
127/136 Test #163: AutomatedTesting::PhysicsTests_Main.main::TEST_RUN .......................   Passed  185.69 sec

In Batch:        
        Start 163: AutomatedTesting::PhysicsTests_Main.main::TEST_RUN
127/136 Test #163: AutomatedTesting::PhysicsTests_Main.main::TEST_RUN .......................   Passed  478.75 sec
````

**Review by hultonha — APPROVED** [review]
We discussed this at some length (@moraaar, @FuzzyCarterAWS, @SergeyAMZN and @michleza) and decided that this change makes sense to merge to help isolate and fix the remaining flaky physics tests. Once they are all stable (being worked on by @FuzzyCarterAWS), we can gradually move tests back to parallel, and help debug that issue in isolation without worrying about the other flaky failures.

If we do still see crashes, then we know the parallel tests are not contributing to the crashes and we can simply revert this change.

**Pull request merged**
