### PR TITLE
Always display all gems in Gem Catalog

### PR DESCRIPTION
**Pull request by AMZN-alexpete**
Fixes an issue where a newly created Gem would not be visible in the Gem Catalog when creating a new project.
See GitHub Issue https://github.com/o3de/o3de/issues/1965 for details.

**Testing**
Created a gem and verified it was visible when creating a new project in the configure gems page:
NewGemAvailableInNewProjectFlow

Signed-off-by: AMZN-alexpete <26804013+AMZN-alexpete@users.noreply.github.com>

### CODE REVIEW

**Comment by amzn-jillich** [comment]
Wouldn't this change reintroduce the issue that when going back to the edit/new project page and then back into the gem catalog, users will loose their selection?

**Comment by AMZN-alexpete** [comment]
> Wouldn't this change reintroduce the issue that when going back to the edit/new project page and then back into the gem catalog, users will loose their selection?

If you're referring to [this change](https://github.com/o3de/o3de/pull/1359/files),  the issue where you lose your selected gems does not occur.  I can select or unselect any gems on the gem catalog page, press back, then go back to gem catalog and the selection is maintained.

6q4akvh6BL

**Comment by amzn-jillich** [comment]
> > Wouldn't this change reintroduce the issue that when going back to the edit/new project page and then back into the gem catalog, users will loose their selection?
> 
> If you're referring to [this change](https://github.com/o3de/o3de/pull/1359/files), the issue where you lose your selected gems does not occur. I can select or unselect any gems on the gem catalog page, press back, then go back to gem catalog and the selection is maintained.
> 
> 6q4akvh6BL

Great, that was what i meant, thanks :).

**Review by amzn-jillich — APPROVED** [review]

**Review by AMZN-Phil — APPROVED** [review]

**Review by AMZN-nggieber — APPROVED** [review]

**Review by fabioanderegg — APPROVED** [review]

**Review by lumberyard-employee-dm — APPROVED** [review]
Pinging in order to get this fix in

**Pull request merged**
