### PR TITLE
[MacOS] Launching Editor from ProjectManager and other misc. fixes

### PR DESCRIPTION
**Pull request by amzn-sj**
1. Fix "Open Editor" button not launching Editor on Mac.
2. Update LaunchAssetProcessor() paths on Mac.
3. LaunchAssetProcessor() uses ProcessWatcher wrappers.
4. SDK Launcher registers the engine when launching.

Signed-off-by: amzn-sj <srikkant@amazon.com>

NOTE: Mac doesn't support running AP in tethered mode yet. Linux uses `prctl()` which isn't an option on MacOS. MacOS does support process termination notifications through kqueues/kevents or Grand Central Dispatch. But those options are callback based and would require modifying the child process's(in our case AP) source. This needs more investigation on Mac.

### CODE REVIEW

**Review by AMZN-nggieber — APPROVED** [review]

**Review by AMZN-ScottR — APPROVED** [review]

**Review by AMZN-alexpete — APPROVED** [review]

**Comment by AMZN-alexpete** [comment]
Is this already in stabilization?

**Comment by amzn-sj** [comment]
> Is this already in stabilization?

No. It's only in development. Do you want me to merge to stabilization first?

**Comment by AMZN-alexpete** [comment]
> > Is this already in stabilization?
> 
> No. Do you want me to merge to stabilization first?

It can be in any order, but I think we want this fix in stabilization also for the release.

**Comment by amzn-sj** [comment]
> > > Is this already in stabilization?
> > 
> > 
> > No. Do you want me to merge to stabilization first?
> 
> It can be in any order, but I think we want this fix in stabilization also for the release.

Ok. I'll make make another one for stabilization as well.

**Review by AMZN-Phil — APPROVED** [review]

**Pull request merged**
