### PR TITLE
Initial pass at SIG-Network code ownership

### PR DESCRIPTION
**Pull request by lmbr-pip**
First round of adding SIG-network code ownership data

Signed-off-by: Pip Potter <61438964+lmbr-pip@users.noreply.github.com>

### CODE REVIEW

**Comment by junbo75** [comment]
A few more files owned by us as well:
- https://github.com/o3de/o3de/blob/development/scripts/build/Platform/Windows/deploy_cdk_applications.cmd
- https://github.com/o3de/o3de/blob/development/scripts/build/Platform/Windows/destroy_cdk_applications.cmd
- https://github.com/o3de/o3de/blob/development/scripts/build/Platform/Linux/deploy_cdk_applications.sh
- https://github.com/o3de/o3de/blob/development/scripts/build/Platform/Linux/destroy_cdk_applications.sh
- https://github.com/o3de/o3de/tree/development/AutomatedTesting/Gem/PythonTests/AWS
- https://github.com/o3de/o3de/tree/development/AutomatedTesting/Levels/AWS
- We may also own the HttpRequester gem as well? I'm not sure. https://github.com/o3de/o3de/tree/development/Gems/HttpRequestor

**Comment by Kadino** [comment]
SIG-Testing does not own the implementation for RemoteConsole (which I believe is a deprecated interface?) but do maintain some Python code that interfaces with it.

**Comment by AMZN-puvvadar** [comment]
If the Twitch Gem is under sig-network I believe it's worth asking if Metastream and HTTPRequestor are as well.

**Comment by AMZN-puvvadar** [comment]
On the subject of Remote Console, sig-network has never had any interaction with it to my knowledge. Maybe sig-platform owns it?

**Comment by lmbr-pip** [comment]
Added all folders suggested

Did not add individual files as we currently are only tracking folders.

**Review by junbo75 — APPROVED** [review]

**Review by lumberyard-employee-dm — COMMENTED** [review]
This is still missing the [AWSNativeSDKInit](https://github.com/o3de/o3de/tree/development/Code/Tools/AWSNativeSDKInit) directory.

**Comment by lmbr-pip** [comment]
Added AWSNativeSDKInit

**Review by lumberyard-employee-dm — APPROVED** [review]

**Review by AMZN-puvvadar — APPROVED** [review]

**Pull request merged**
