### PR TITLE
Updated OpenImageIO to use new rev3 package on windows

### PR DESCRIPTION
**Pull request by cgalvan**
Recently the OpenImageIO package needed to be updated on windows to disable the boost stacktrace usage:

https://github.com/o3de/3p-package-source/pull/120

This PR updates to use the new package on windows.

Signed-off-by: Chris Galvan <chgalvan@amazon.com>

### CODE REVIEW

**Review by lawsonamzn — APPROVED** [review]

**Review by moraaar — APPROVED** [review]
does the new version also fix the compilation issue on windows (debug) as well?

````
[2022-06-30T05:38:17.560Z] D:\workspace\3rdParty\packages\openimageio-opencolorio-2.3.12.0-rev2-windows\OpenImageIO\include\OpenImageIO/fmath.h(2384,5): error C4777: 'fprintf' : format string '%zd' requires an argument of type 'unsigned __int64', but variadic argument 5 has type 'OpenImageIO_v2_3::span_strided<const float,-1>::size_type' [D:\workspace\o3de\build\windows\External\GradientSignal-2eb7fe95\Code\GradientSignal.Editor.Static.vcxproj]
````

https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE_periodic-incremental-daily/detail/development/24/pipeline/1188

**Comment by cgalvan** [comment]
>

**Comment by cgalvan** [comment]
> does the new version also fix the compilation issue on windows (debug) as well?
> 
> ```
> [2022-06-30T05:38:17.560Z] D:\workspace\3rdParty\packages\openimageio-opencolorio-2.3.12.0-rev2-windows\OpenImageIO\include\OpenImageIO/fmath.h(2384,5): error C4777: 'fprintf' : format string '%zd' requires an argument of type 'unsigned __int64', but variadic argument 5 has type 'OpenImageIO_v2_3::span_strided<const float,-1>::size_type' [D:\workspace\o3de\build\windows\External\GradientSignal-2eb7fe95\Code\GradientSignal.Editor.Static.vcxproj]
> ```
> 
> https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE_periodic-incremental-daily/detail/development/24/pipeline/1188

Unfortunately no, the new pacakge is to fix a `dbgeng.dll` dependency on Windows. That error is in an `OpenImageIO` header itself, for which we don't modify the source. I think I could resolve that though by wrapping the include with an `AZ_PUSH_DISABLE_WARNING`. Is it a warning as error or a true error? I wasn't able to reproduce it locally.

**Comment by lawsonamzn** [comment]
> > does the new version also fix the compilation issue on windows (debug) as well?
> > ```
> > [2022-06-30T05:38:17.560Z] D:\workspace\3rdParty\packages\openimageio-opencolorio-2.3.12.0-rev2-windows\OpenImageIO\include\OpenImageIO/fmath.h(2384,5): error C4777: 'fprintf' : format string '%zd' requires an argument of type 'unsigned __int64', but variadic argument 5 has type 'OpenImageIO_v2_3::span_strided<const float,-1>::size_type' [D:\workspace\o3de\build\windows\External\GradientSignal-2eb7fe95\Code\GradientSignal.Editor.Static.vcxproj]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE_periodic-incremental-daily/detail/development/24/pipeline/1188
> 
> Unfortunately no, the new pacakge is to fix a `dbgeng.dll` dependency on Windows. That error is in an `OpenImageIO` header itself, for which we don't modify the source. I think I could resolve that though by wrapping the include with an `AZ_PUSH_DISABLE_WARNING`. Is it a warning as error or a true error? I wasn't able to reproduce it locally.

That shouldn't cause a warning - these libraries are supposed to be ingested as system libraries, which is not supposed to trigger a warning as error..  Weird.

**Pull request merged**
