### PR TITLE
Replace temp folder creation with solid solution

### PR DESCRIPTION
**Pull request by onecent1101**
## Details
As we see intermittent unit test failure because of temp folder creation failed, replace it with more solid solution.
Refer to https://github.com/o3de/o3de/issues/4340

More related test improvements tracked here https://github.com/o3de/o3de/issues/6783

## Testing
Run unit test locally and pass

### CODE REVIEW

**Review by junbo75 — APPROVED** [review]

**Comment by allisaurus** [comment]
change LGTM, but can you add mention of what testing was done? e.g., unit test run and succeed with new dependency

**Review by lumberyard-employee-dm — DISMISSED** [review]

**Comment by onecent1101** [comment]
> change LGTM, but can you add mention of what testing was done? e.g., unit test run and succeed with new dependency

done

**Comment by onecent1101** [comment]
Seeing android build is failing
```
[2022-01-10T20:12:24.711Z] lib/profile/libAzFrameworkTestShared.a(unity_0_cxx.cxx.o): In function `std::__ndk1::__fs::filesystem::temp_directory_path()':

[2022-01-10T20:12:24.711Z] C:/ly\3rdParty\android-ndk\r21d\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\c++\v1/filesystem:1927: undefined reference to `std::__ndk1::__fs::filesystem::__temp_directory_path(std::__ndk1::error_code*)'

[2022-01-10T20:12:24.711Z] lib/profile/libAzFrameworkTestShared.a(unity_0_cxx.cxx.o): In function `std::__ndk1::__fs::filesystem::path::has_root_directory() const':

[2022-01-10T20:12:24.711Z] C:/ly\3rdParty\android-ndk\r21d\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\c++\v1/filesystem:1084: undefined reference to `std::__ndk1::__fs::filesystem::path::__root_directory() const'

[2022-01-10T20:12:24.711Z] lib/profile/libAzFrameworkTestShared.a(unity_0_cxx.cxx.o): In function `std::__ndk1::__fs::filesystem::path::has_filename() const':

[2022-01-10T20:12:24.711Z] C:/ly\3rdParty\android-ndk\r21d\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\c++\v1/filesystem:1096: undefined reference to `std::__ndk1::__fs::filesystem::path::__filename() const'

[2022-01-10T20:12:24.711Z] clang++: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Comment by onecent1101** [comment]
https://github.com/o3de/o3de/pull/6789

**Pull request closed without merging**
