### PR TITLE
Remove vegetation dynamic slice support

### PR DESCRIPTION
**Pull request by mbalfour-amzn**
Dynamic slices are deprecated in the engine at this point, so supporting them in the vegetation system was just leading to confusion. This removes all support for them from vegetation.

### CODE REVIEW

**Review by cgalvan — APPROVED** [review]
Does this end up fixing https://github.com/o3de/o3de/issues/8930 ? Since it gets rid of the Dynamic Slice spawner type, does that result in prefab being the new default?

**Comment by mbalfour-amzn** [comment]
> Does this end up fixing #8930 ? Since it gets rid of the Dynamic Slice spawner type, does that result in prefab being the new default?

It fixes it in Development, but not in Stabilization.

**Review by srikappa-amzn — APPROVED** [review]
Dynamic slices are not fully deprecated in the engine yet. The defaults are spawnables. But there can still be customers who have data using slices and dynamic slices. If vegetation team wants to stop supporting dynamic slices, it is totally their call. I'm just cautioning about the backwards compatibility problems that may arise.

**Review by gadams3 — APPROVED** [review]

**Comment by mbalfour-amzn** [comment]
> Dynamic slices are not fully deprecated in the engine yet. The defaults are spawnables. But there can still be customers who have data using slices and dynamic slices. If vegetation team wants to stop supporting dynamic slices, it is totally their call. I'm just cautioning about the backwards compatibility problems that may arise.

The dynamic slice support was only kept around this long because some automated tests relied on it. Those tests have since been switched to prefabs, so there isn't a need to keep the slice support in this system any longer. It's just causing confusion. There shouldn't be any customers using the vegetation system yet, since Atom still needs to add support for optimized instancing.

**Pull request merged**
