### PR TITLE
Changed minimum value - a value less than 1.0 will cause the program to consume large amounts of CPU.

### PR DESCRIPTION
**Pull request by jjjoness**
Signed-off-by: John Jones-Steele <82226755+jjjoness@users.noreply.github.com>

### CODE REVIEW

**Review by moraaar — APPROVED** [review]

**Comment by invertednormal** [comment]
I don't think it's a good idea to just put a hard cap on the query resolution. For instance 128x128 meter world would be fine with a 0.1 query resolution because the total number of samples isn't that high. I'm not sure if any hard caps are a good idea here because people may be ok with a long processing time to get the results they want. Maybe we could have a warning message when the combination of world size * query resolution equate to a large number of samples? Thoughts @mbalfour-amzn ?

**Comment by jjjoness** [comment]
@invertednormal Should we do a calculation dependant on the workd size?

**Comment by invertednormal** [comment]
> @invertednormal Should we do a calculation dependent on the world size?

I'd recommend putting a temporary hard-cap of 8192x8192 samples (worldSize / queryResolution). If possible we should also warn when the number of samples goes over some amount, maybe like 4 million?

**Comment by jjjoness** [comment]
@invertednormal I'll get that done with those constraints. Do we need to ask UX about the warning?

**Comment by invertednormal** [comment]
> @invertednormal I'll get that done with those constraints. Do we need to ask UX about the warning?

Yeah, that's a good idea... I'm not sure the best way to handle this since it'll vary by computer. We also need to make a lot of the work async and work on performance which will help a lot and may change the need for the warning in the future

**Comment by jjjoness** [comment]
Broken commit - will close and recreate.

**Pull request closed without merging**
