### PR TITLE
Updating Pillow to 9.1.0

### PR DESCRIPTION
**Pull request by evanchia-ly-sdets**
Tested by running get python script to fetch new version.

Signed-off-by: evanchia-ly-sdets <evanchia@amazon.com>

### CODE REVIEW

**Review by amzn-changml — APPROVED** [review]

**Review by Ulrick28 — APPROVED** [review]
Approved from sig-release

**Review by AMZN-Dk — APPROVED** [review]
Approved from the Testing SIG

**Comment by amzn-changml** [comment]
Left approval on behalf of SIG-Build

**Review by lumberyard-employee-dm — APPROVED** [review]

**Comment by lumberyard-employee-dm** [comment]
Approved on behalf of SIG-Core

**Comment by yuyihsu** [comment]
approved from UI-UX sig

**Review by lmbr-pip — APPROVED** [review]

**Comment by lmbr-pip** [comment]
Approved on behalf of sig-security

**Comment by tonybalandiuk** [comment]
**Exception Tracking**

- [ ] 1.    Owning SIG requests the exception, by a Sig Representative (Chair/co-chair) adding the PR to the exception requests queue board.
- [ ] 2.    Owning SIG comments on the PR explaining impact if this code does not go into stabilization.
- [ ] 3.	Unrelated SIG representative (chair/cochair) approves the exception, adding a comment indicating approval and the SIG they represent.
- [ ] 4.	UX SIG representative (chair/cochair) approves the exception, adding a comment indicating approval and the SIG they represent.
- [ ] 5.	Testing SIG representative (chair/cochair) approves the exception, adding a comment indicating approval and the SIG they represent.
- [ ] 6.	If all approvals are accepted exception PR is merged
- [ ] 7.	Merged PR is verified successful via testing. If Merged PR verification testing failed, consult reps from step 3-5 and discussion occurs on fixing the failure vs backing out change
- [ ] 8.	Exception is complete

**Comment by tonybalandiuk** [comment]
filling in step 2  (copied from #8995 ) If this is not fixed then customers will nee to "to update their local python dependencies by executing <path\to\o3de\python\pip.cmd/sh> install --upgrade pillow

https://packaging.python.org/en/latest/tutorials/installing-packages/#use-pip-for-installing"

**Comment by Ulrick28** [comment]
Owning sig mentioned in the previous PR, if this does not go in, users will need to use a workaround to upgrade their version of Pillow, when installing and setting up O3DE to avoid high risk security issues.

**Comment by evanchia-ly-sdets** [comment]
This has failed AR due to an intermittent test failure that is already being tracked in our internal ticket system. Since this is a high priority issue, I can override the pull request pr status check with SIG approval.

**Comment by Ulrick28** [comment]
I have been following the threads about the failure and you have sig-release approval. I suggest getting approval from @AMZN-Dk

**Comment by AMZN-Dk** [comment]
Agreed with @Ulrick28 and @evanchia-ly-sdets above that this can bypass the check to avoid the flaky test as the change is higher priority.

**Pull request merged**
