### PR TITLE
Updated Visual Studio Version to 16.11 and 17.0

### LINKED ISSUE #7665: Upgrade VS version to 16.11 and higher.
**Is your feature request related to a problem? Please describe.**
According to [Support ends for older versions of Visual Studio](https://devblogs.microsoft.com/visualstudio/support-ends-for-older-versions-of-visual-studio-feb2022/).
>Visual Studio 2019 version 16.7: [support ends April 12, 2022](https://docs.microsoft.com/lifecycle/products/visual-studio-2019). We recommend users move to the version 16.11 supported baseline, or to Visual Studio 2022.

**Describe the solution you'd like**
Project Manager should move to 16.11 and 17, to build projects.

**Describe alternatives you've considered**
NA

**Additional context**
NA

### PR DESCRIPTION
**Pull request by mattiascibien**
Fixes #7665

### CODE REVIEW

**Review by lumberyard-employee-dm — CHANGES_REQUESTED** [review]
An RFC should be created and added to the sig-build agenda in order to upgrade the minimum compiler versions for VS.
This is Impactful change and will require an announcement detailing that users have to upgrade to Visual Studio 2019 to 16.11.
Furthermore the Jenkins machines that run continuous integration builds will need to have their versions of Visual Studio 2019 upgraded to the 16.11.x

As a side change, I would remove the maximum cap for VS 2022, as new minor versions(the 'x' digit in 17.x.y) are still being released.
If anything I would have it be `[16.11,18)` so that the project manager can use all upcoming VS2022 versions.

The Issue tab in the sig-build repo can be used to create an RFC detailing the change.

That being said I am good with the change to upgrade the minimum version for VS2019 to 16.11 as that is the long term support version that will receive support until 2027, while the 16.9 series is end of life in October of this year.

**Review by jackalbe — APPROVED** [review]

**Comment by mattiascibien** [comment]
I have updated the code to include all the VS2022 versions. I will now looking into opening the RFC

**Comment by mattiascibien** [comment]
RFC is now open: https://github.com/o3de/sig-build/issues/23

**Comment by rgba16f** [comment]
@lumberyard-employee-dm what's the path forward here?

**Comment by lumberyard-employee-dm** [comment]
> @lumberyard-employee-dm what's the path forward here?

I believe this change is good as it stands to allow Project Manager to configure using VS2022 as long as the Windows Jenkins nodes don't go through Project Manager in order to build a project.
@AMZN-alexpete @o3de/sig-build Do you know if there are any automated test or pipeline steps that builds through Project Manager?

If there are none, then this change is safe to go in and will not break CI builds.
Otherwise the Windows Jenkins nodes will need to have their VS2019 versions upgraded to to 16.11.x series.

I am kicking off this change in AR to see if this build.

I am good with the RFC as posted in the sig-build repo: https://github.com/o3de/sig-build/issues/23.
Does @o3de/sig-build have any thoughts?

**Review by lumberyard-employee-dm — APPROVED** [review]
Approved pending @o3de/sig-build  feedback

**Review by AMZN-alexpete — APPROVED** [review]
> I believe this change is good as it stands to allow Project Manager to configure using VS2022 as long as the Windows Jenkins nodes don't go through Project Manager in order to build a project. @AMZN-alexpete @o3de/sig-build Do you know if there are any automated test or pipeline steps that builds through Project Manager?
> 
> If there are none, then this change is safe to go in and will not break CI builds. Otherwise the Windows Jenkins nodes will need to have their VS2019 versions upgraded to to 16.11.x series.
> 
> I am good with the RFC as posted in the sig-build repo: [o3de/sig-build#23](https://github.com/o3de/sig-build/issues/23). Does @o3de/sig-build have any thoughts?

I am not aware of any jobs building on Jenkins using the Project Manager to build, adding @AMZN-Phil and @amzn-changml to confirm.

**Comment by lumberyard-employee-dm** [comment]
@mattiascibien It looks Jenkins has failed with a gradle error, which I believe @spham-amzn address in the time since this PR as put up.
Can you try pulling the latest o3de/development into your branch?

We can kick off another Jenkins build afterward
https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/PR-7714/1/pipeline/345

**Comment by mattiascibien** [comment]
I tried but made a mistake on my part since it seems that github when working with the web interface only does merge commits. I will try to fix this as soon as i get to my work PC where I downloaded the source code


Sorry for the incovenience.

**Comment by mattiascibien** [comment]
@lumberyard-employee-dm I was finally able to do the rebase on my side so I have pushed everything up. Now the PR only has one commit.

**Review by hultonha — APPROVED** [review]
Nice! 😄

**Pull request merged**
