### PR TITLE
Atom/dccsi_Lsprint_collab

### PR DESCRIPTION
**Pull request by HogJonny-AMZN**
This replaces: https://github.com/o3de/o3de/pull/6790

With commit [953b29f](953b29feec22cfa2baaa5a9c4f27cd0ca25c4d8b)

There was some concerns and feedback that ...
1. The DCCsi config and bootstrapping might contribute to slow boot times for editors (like the Material Editor)
2. The default windows .bat launchers and env for tech art development (like WingIDE or PyCharm) default to debug mode (verbose logging), and enable a developer mode (easy early attach debugger).

Let's explore these things.

The complaints specifically were that this was:
1. A lot of verbose spam another dev would have to parse through
2. That this verbosity doesn't relate to their code/tool, their tool/code logging is hard to find
3. And some of it runs each and every time (why can't you cache data?)

So some changes:
1. IDE launchers no longer force debug and dev settings (they are opt in): "C:\Depot\o3de-dev\Gems\AtomLyIntegration\TechnicalArt\DccScriptingInterface\Tools\Dev\Windows\IDE\Launch_WingIDE-7-1.bat"
2. Devs can opt-in by creating this file and overriding envars and propagating the environment: "C:\Depot\o3de-dev\Gems\AtomLyIntegration\TechnicalArt\DccScriptingInterface\Tools\Dev\Windows\Env_Dev.bat"
3. config.py can now stash: settings.local.json (last settings file to load though, which is proper design.)
4. custom settings in settings.local.json will persist, they will not be wiped if settings are updated and re-cached (dev will have to remove them, or clean/flush the file and re-gen. To Do: we could add a cli flush option.)
5. settings.local.json is restricted from commit to git (it is in fact local only)

Some notes: 
1. debug mode performs as intended (breadcrumbs and verbose, debug is debug)
2. dev mode slows things down because it's attempting to attach debugger (debugger is a feture)
3. you want debug when it's needed, you can't just debug only your code when your code interfaces with other APIs
4. if the logging system is in debug, debug logging statements will fire (this is a feature)
5. I didn't design the logging system (maybe there are still ways for us to make better use of it)
6. it is often desirable to execute code every run during development, specifically debug logging and verbosity are are a feature (important in testing and troubleshooting.)
7. stashed local settings provide flexibility, can be used to optimize speed, they also introduce risks (could become stale and thus error prone)
8. To Do: future work should introduce config and settings versioning, there is a conundrum if we want custom settings to be defined and thus also persist in local settings, while also having the local settings load last (which is proper design). The module and settings will need to be versioned and compared/updated prior to a new write upon settings updates. This is slightly complex, could be error prone, and could balloon code that needs to validate versioned settings (the speed benefits of cached settings, could later be eroded by validation and updates - but probably only once on the first new run?)

When running from a IDE in full debug (these things may contribute to slow timing):
1. debug mode and verbose logging
2. ^ significant speed impact, but to be expected
3. some envars may perform search mechanisms to be synthetically discovered/derived (local data)
4. ^ moderate slow down
5. initializing all of the config sections: dccsi core, o3de python, o3de pyside2(Qt)
6. ^ negligible
7. generating cached settings.local.json
8. ^ negligible
9. reading existing settings.local.json
10. ^ negligible

Let's move on, here is some data related to the first set of changes (stash and load local settings):

Running within Wing IDE:
1. in debug (verbose)
2. 1st Run DCCsi: config.py TOTAL: 2.65625 sec, and it generated the settings.local.json
3. 2nd run DCCsi: config.py TOTAL: 2.703125 sec (so no big savings here, slightly longer probably because it's now parsing local settings, or just variance in runtime.)
4. Results: this is not so bad.

When running standalone from cli, no local settings (primarily synthetic):
C:\Depot\o3de-dev\python>`python.cmd "C:\Depot\o3de-dev\Gems\AtomLyIntegration\TechnicalArt\DccScriptingInterface\config.py"`

1. debug off by default (no verbose logging)
2. no dev mode (no automatic attempt to attach debugger)
3. init only the core config:
4. doesn't generate/stash: settings.local.json
5. 1st run: DCCsi: config.py TOTAL: 1.0625 sec
6. 2nd run: DCCsi: config.py TOTAL: 1.046875 sec
Results: this is fine.

When running standalone from cli, export local settings (synthetic, stash settings):
C:\Depot\o3de-dev\python>`python.cmd "C:\Depot\o3de-dev\Gems\AtomLyIntegration\TechnicalArt\DccScriptingInterface\config.py" -es=True`

1. debug off by default (no verbose logging)
2. no dev mode (no automatic attempt to attach debugger)
3. init only the core config:
4. generates settings.local.json (which will afterwards affect the 2nd run as it is now also parsed)
5. 1st run: DCCsi: config.py TOTAL: 1.09375 sec (not significantly longer to generate)
6. 2nd run: do not need to stash, this time run but utilize the cached settings:
`python.cmd "C:\Depot\o3de-dev\Gems\AtomLyIntegration\TechnicalArt\DccScriptingInterface\config.py"`
DCCsi: config.py TOTAL: 1.046875 sec (no significant slow down)
Results: this is fine.

Run standalone from cli and init all settings groups (core, py, qt) with previously ^ generated settings.local.json
C:\Depot\o3de-dev\python>python.cmd `"C:\Depot\o3de-dev\Gems\AtomLyIntegration\TechnicalArt\DccScriptingInterface\config.py" -py=True -qt=True`
1. debug off by default (no verbose logging)
2. no dev mode (no automatic attempt to attach debugger)
3. init all segments of the config:
4. 1st run: DCCsi: config.py TOTAL: 1.046875 sec (not significantly longer when doing all of the work)
5. 2nd DCCsi: config.py TOTAL: 1.140625 sec
6. 3rd DCCsi: config.py TOTAL: 1.03125 sec
Results: a little bit more variance, but this is fine.

Conclusions:
Running debug in IDE is the slowdown (but you can now opt-in/out)

### CODE REVIEW

**Comment by HogJonny-AMZN** [comment]
This PR also removes QtDarkStyle because that brings in qtpy (bindings abstraction layer)  as a dependency which we don't want.  If customers want to create their own tools using qtpy they can perform and manage that install themselves.

**Comment by HogJonny-AMZN** [comment]
This PR now includes the merge of the 'Blender Scene Exporter V1' by @shawstar 
PR (CR approved): https://github.com/aws-lumberyard-dev/o3de/pull/284
Wiki with basic instructions:  https://github.com/o3de/o3de/wiki/%5BDCCsi%5D-Blender-Scene-Exporter
Readme: DccScriptingInterface/Tools/DCC/Blender/AddOns/SceneExporter/README.md

**Review by HogJonny-AMZN — COMMENTED** [review]
reviewed merge up

**Comment by HogJonny-AMZN** [comment]
running config.py standalone from cmd
image

**Comment by HogJonny-AMZN** [comment]
Running standalone (testing) with o3de access to python/qt locations and run the PySide2 test:
C:\Depot\o3de-dev\python>`python.cmd "C:\Depot\o3de-dev\Gems\AtomLyIntegration\TechnicalArt\DccScriptingInterface\config.py" -py=true -qt=true -tp=true`
Results: pop's up this button if it's working correctly...
image

image

notes:
the cli operates variables for internal methods (those variables can be passed, and methods can be run from script)
1. don't use -py=true, if you are using dccsi\config.py in a DCC app that has it's own python!
^ example: using in maya will cause boot to fail (it will look for the wrong python files, incompatibilities result) 
2. don't use -qt=true, if you are using dccsi\config.py in a DCC app with it's own Qt implementation!
^ example: maya and o3de Qt .dlls will have conflicts (maya should use it's own, in most cases your code should still work.)
^^ experiment: should be fun to play with various ways that maybe o3de Qt can be run in sub-process within Blender?

**Comment by HogJonny-AMZN** [comment]
This commits is a v1.1 update to @shawstar Blender Scene Exporter AddOn:
https://github.com/o3de/o3de/pull/6868/commits/815845d80188f4cd3ffa4c761dfda389c1662407

**Comment by HogJonny-AMZN** [comment]
With the latest changes:
https://github.com/o3de/o3de/pull/6868/commits/d8af1f71608b43461a1b94d67beb561896e47e8e
https://github.com/o3de/o3de/pull/6868/commits/0715f8e311e0d9bfaea308a8a27cbba2b1bc9ff1

- stubbed out the dcc api (with changes, dcc tool apis are gated at import, this is experimental)
- the <DCCsi>\Tools location is now treated like a package, the __init__.py has a simple cli to test access
- the azpy.__init__.py also has a simple cli for testing that api
- small changes: stubbed a logger class which isn't implemented yet (so we can reduce boilerplate and unify logging more across code)

With tests on (by default) in the cli, it tests recursive imports (this should surface cyclical import chain issues that can become common). Here is an example of the log output for the azpy cli

image

**Review by HogJonny-AMZN — COMMENTED** [review]
I've reviewed all of the recent changes, I can not however approve the PR because I started it.

**Comment by HogJonny-AMZN** [comment]
Here are the basic manual steps to setup and configure Maya 2020 w/ Python2.7
Note: other versions of Maya are similar (you just need to update some of the commands, so I will document those.)

image

**Comment by HogJonny-AMZN** [comment]
Maya 2022 w/ py3 boots now with what I committed (still some changes to make)

If you are in a IDE with a debugger attached, there are some odd exceptions that will be caught; you have to step through them (about 24 I think), they are related to plugin loading and pyside2 somehow (I think) - they don't seem to be related to our stuff.

They are benign when not debugging


They look like "builtins.ModuleNotFoundError: No module named 'vnn_load'"

Maya continues to boot fine, and I can verify that functionally by the fact the DCCsi menu appears

**Comment by AMZN-alexpete** [comment]
There are a fairly number of C++ files changed in this PR, were those intentional or is it possible there were some merge errors?

**Comment by HogJonny-AMZN** [comment]
replaced with: https://github.com/o3de/o3de/pull/7867

**Pull request closed without merging**
