### PR TITLE
Renamed folder physics -> Physics

### PR DESCRIPTION
**Pull request by AMZN-AlexOteiza**
Tested locally switching between development and this branch and the file case gets renamed properly.
Git shouldn't have issues with renaming casing of files since it works with unix paths

### CODE REVIEW

**Comment by AMZN-AlexOteiza** [comment]
After testing, even if the folder doesn't get properly updated. CMake does not care about casing in windows

**Review by moraaar — APPROVED** [review]
LGTM

**Comment by greerdv** [comment]
I think there was some discussion over how much these are specifically PhysX tests versus physics (i.e. if another physics backend were added, where would its tests go?) and whether it would be better for the naming structure to map more closely to SIGs. Was there any resolution to those discussions?

**Review by jonawals — APPROVED** [review]

**Review by moraaar — APPROVED** [review]
LGTM

**Comment by AMZN-AlexOteiza** [comment]
> I think there was some discussion over how much these are specifically PhysX tests versus physics (i.e. if another physics backend were added, where would its tests go?) and whether it would be better for the naming structure to map more closely to SIGs. Was there any resolution to those discussions?

We are a bit inconsistent on the folders, originally physics was selected because the tests could use generic physics ebuses and would englobe more. We have "scripting" which englobes Script canvas, and may also cover Lua? "largeworlds" also englobes different features aswell.
In any case, we can still rename this to PhysX in the future if needed.

**Comment by greerdv** [comment]
> > I think there was some discussion over how much these are specifically PhysX tests versus physics (i.e. if another physics backend were added, where would its tests go?) and whether it would be better for the naming structure to map more closely to SIGs. Was there any resolution to those discussions?
> 
> We are a bit inconsistent on the folders, originally physics was selected because the tests could use generic physics ebuses and would englobe more. We have "scripting" which englobes Script canvas, and may also cover Lua? "largeworlds" also englobes different features aswell.
> In any case, we can still rename this to PhysX in the future if needed.
> 
> IMO, I think using sig for naming the folder structure would make the tests more difficult to find, as sigs are super generic

Yeah, plus sigs can change over time. I imagine at some point there will be a sig-physics.

**Pull request merged**
