### PR TITLE
Windows 10 SDK update

### PR DESCRIPTION
**Pull request by amzn-changml**
## What does this PR do?

Updates the Windows 10 SDK from 18362 to 20348 (latest). Addresses lack of `D3D12_INDIRECT_ARGUMENT_TYPE_DISPATCH_RAYS` in the header files for https://github.com/o3de/o3de/pull/12009

## How was this PR tested?

Tested on a sandbox Jenkins against the PR

### CODE REVIEW

**Review by brianherrera — APPROVED** [review]

**Review by lumberyard-employee-dm — APPROVED** [review]

**Review by nick-l-o3de — APPROVED** [review]
Do any doc updates need to go along with this, such as min req?

**Comment by lumberyard-employee-dm** [comment]
> Do any doc updates need to go along with this, such as min req?

Yeah we would need to update this page to mention 20H2: https://www.docs.o3de.org/docs/welcome-guide/requirements/#microsoft-windows

**Comment by amzn-changml** [comment]
Yes, I've already updated the Windows minver the docs in Development: https://github.com/o3de/o3de.org/pull/2432 to reflect this. I'll update the docs for the SDK version, however

**Comment by amzn-changml** [comment]
https://github.com/o3de/o3de.org/pull/2442 for the doc update

**Review by byrcolin — APPROVED** [review]

**Review by Jackie9527 — APPROVED** [review]

**Pull request merged**
