### PR TITLE
Fix error message in StreamingImage::CreateFromCpuData

### PR DESCRIPTION
**Pull request by martinwinter-huawei**
## What does this PR do?

The error message in `StreamingImage::CreateFromCpuData` previously stated `StreamingImage::CreateFromCpuData found an existing entry in the instance database for the provided id.`, when the `Data::InstanceDatabase<StreamingImage>::Instance().Find()` call returned a `nullptr`, which is the opposite of what the error actually is, i.e., a `nullptr` signifies that **no entry** was found with this id.

## How was this PR tested?

This PR only changes the text of an error message.

### CODE REVIEW

**Review by gadams3 — CHANGES_REQUESTED** [review]
Thank you for your PR, which calls attention to something I've been meaning look at. I think the error message is correct and the problem is that the instance is not being added to the database with the correct id after changes that I merged a couple of weeks ago. I think the message is supposed to indicate that an image with a corresponding id was already registered but we are attempting to register another image with the same id. The problem is at the end of the function where it's calling FindOrCreate using the unique asset ID, which may not match the input id because of sub IDs, instead of the id that was passed in. There was a similar problem with the buffer system. Instead, we need to create the instance using the UUID that was passed in and not the asset ID.

These changes should take care of it https://github.com/o3de/o3de/pull/17055

**Comment by gadams3** [comment]
I submitted a fix for this

**Comment by martinwinter-huawei** [comment]
> Thank you for your PR, which calls attention to something I've been meaning look at. I think the error message is correct and the problem is that the instance is not being added to the database with the correct id after changes that I merged a couple of weeks ago. I think the message is supposed to indicate that an image with a corresponding id was already registered but we are attempting to register another image with the same id. The problem is at the end of the function where it's calling FindOrCreate using the unique asset ID, which may not match the input id because of sub IDs, instead of the id that was passed in. There was a similar problem with the buffer system. Instead, we need to create the instance using the UUID that was passed in and not the asset ID.
> 
> These changes should take care of it #17055

Thanks for the explanation! Makes sense why this error showed up.
Though I would still argue that if a call to `Data::InstanceDatabase<StreamingImage>::Instance().Find()` does **not find** anything (and returns a `nullptr`), the error message still should reflect that, so even with the changes, it should say `StreamingImage::CreateFromCpuData found no existing entry in the instance database for the provided id.` or am I not following something?

**Comment by martinwinter-huawei** [comment]
Ah, I get it now, I interpreted the condition in `AZ_Error` the wrong way round.

**Pull request closed without merging**
