### PR TITLE
Moves LmbrCentral Test targets into a different folder to prevent MSB8028

### LINKED ISSUE #6241: A warning is printed to the Command Line during Prebuilt SDK build on certain PCs
**Describe the bug**
Configuring and building the engine following the Prebuilt SDK instruction set causes a warning to display on certain PCs. It should be noted that the build itself goes through successfully, and the engine does not have any apparent issues caused by this.

Warning displayed:
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(5
13,5): warning MSB8028: The intermediate directory (x64\profile\) contains files shared from another project (LmbrCentr
al.API.vcxproj).  This can lead to incorrect clean and rebuild behavior. [C:\Builds\o3de\build\windows_vs2019\External\
LmbrCentral-dfc60e35\Code\LmbrCentral.Mocks.vcxproj]
```

**Steps to reproduce**
1. Configure and build the engine following the Prebuilt SDK instruction set.

**Expected behavior**
Build goes through without any issues.

**Actual behavior**
A warning is displayed during the build.

**Command Line log and dxdiags**
Command Line log:
```
C:\Builds\o3de>cmake --build build/windows_vs2019 --target INSTALL --config profile -- /m
Microsoft (R) Build Engine version 16.10.2+857e5a733 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule C:/Builds/o3de/Code/Framework/AzCore/CMakeLists.txt
  Building Custom Rule C:/Builds/o3de/Gems/AtomLyIntegration/CommonFeatures/Code/CMakeLists.txt
  Building Custom Rule C:/Builds/o3de/Gems/Atom/Bootstrap/Code/CMakeLists.txt
  Building Custom Rule C:/Builds/o3de/Gems/Atom/Asset/ImageProcessingAtom/Code/CMakeLists.txt
  Building Custom Rule C:/Builds/o3de/Code/Editor/Plugins/EditorCommon/CMakeLists.txt
  Building Custom Rule C:/Builds/o3de/Code/Editor/CMakeLists.txt
  unity_28_cxx.cxx
  unity_25_cxx.cxx
  unity_24_cxx.cxx
  unity_27_cxx.cxx
  unity_26_cxx.cxx
  unity_22_cxx.cxx
  unity_29_cxx.cxx
  unity_21_cxx.cxx
  unity_18_cxx.cxx
  unity_20_cxx.cxx
  unity_23_cxx.cxx
  unity_19_cxx.cxx
  unity_15_cxx.cxx
  unity_16_cxx.cxx
  unity_17_cxx.cxx
  unity_14_cxx.cxx
  unity_13_cxx.cxx
  unity_12_cxx.cxx
  unity_11_cxx.cxx
  unity_10_cxx.cxx
  unity_9_cxx.cxx
  unity_8_cxx.cxx
  unity_7_cxx.cxx
  unity_6_cxx.cxx
  unity_5_cxx.cxx
  unity_4_cxx.cxx
  unity_3_cxx.cxx
  unity_2_cxx.cxx
  unity_1_cxx.cxx
  unity_0_cxx.cxx
  HeapSchema.cpp
  Building Custom Rule C:/Builds/o3de/Code/Legacy/CryCommon/CMakeLists.txt
  Building Custom Rule C:/Builds/o3de/Gems/GameStateSamples/Code/CMakeLists.txt
  Building Custom Rule C:/Builds/o3de/Gems/GradientSignal/Code/CMakeLists.txt
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(5
13,5): warning MSB8028: The intermediate directory (x64\profile\) contains files shared from another project (LmbrCentr
al.API.vcxproj).  This can lead to incorrect clean and rebuild behavior. [C:\Builds\o3de\build\windows_vs2019\External\
LmbrCentral-dfc60e35\Code\LmbrCentral.Mocks.vcxproj]
  Building Custom Rule C:/Builds/o3de/Gems/LmbrCentral/Code/CMakeLists.txt
  Building Custom Rule C:/Builds/o3de/Gems/LmbrCentral/Code/CMakeLists.txt
  Building Custom Rule C:/Builds/o3de/Gems/Presence/Code/CMakeLists.txt
  Building Custom Rule C:/Builds/o3de/Gems/PhysX/Code/CMakeLists.txt
  Building Custom Rule C:/Builds/o3de/Gems/ScriptCanvas/Code/CMakeLists.txt
  Building Custom Rule C:/Builds/o3de/Gems/Terrain/Code/CMakeLists.txt
  AzCore.vcxproj -> C:\Builds\o3de\build\windows_vs2019\lib\profile\AzCore.lib
  Building Custom Rule C:/Builds/o3de/Gems/GameState/Code/CMakeLists.txt
  Copying CustomAssetExample runtime dependencies to output...
  Running AutoGen for AzNetworking
  Building Custom Rule C:/Builds/o3de/Code/Framework/AtomCore/CMakeLists.txt
  Copying ImGui.imguilib runtime dependencies to output...
  Building Custom Rule C:/Builds/o3de/Gems/PhysX/Code/NumericalMethods/CMakeLists.txt
  Building Custom Rule C:/Builds/o3de/Code/Framework/AzTest/CMakeLists.txt
  Building Custom Rule C:/Builds/o3de/Gems/ScriptedEntityTweener/Code/CMakeLists.txt
  Building Custom Rule C:/Builds/o3de/Code/Tools/CrashHandler/Support/CMakeLists.txt
  Building Custom Rule C:/Builds/o3de/Gems/CustomAssetExample/Code/CMakeLists.txt
  Building Custom Rule C:/Builds/o3de/Gems/ImGui/Code/CMakeLists.txt
  Copying GraphCanvas runtime dependencies to output...
  Building Custom Rule C:/Builds/o3de/Gems/GraphCanvas/Code/CMakeLists.txt
  Copying SceneProcessing runtime dependencies to output...
  Building Custom Rule C:/Builds/o3de/Gems/SceneProcessing/Code/CMakeLists.txt
```
Dxdiag files:
PCs which reproduced the issue:
[DxDiag_GPC-464.txt](https://github.com/o3de/o3de/files/7674809/DxDiag_GPC-464.txt)
[DxDiag_GPC-602.txt](https://github.com/o3de/o3de/files/7674795/DxDiag_GPC-602.txt)
[DxDiag_GPC-610.txt](https://github.com/o3de/o3de/files/7674816/DxDiag_GPC-610.txt)

PC which did not reproduce the issue:
[DxDiag-GPC-462.txt](https://github.com/o3de/o3de/files/7674790/DxDiag-GPC-462.txt)

**Found in Branch**
Development (a8ef23e)

**Desktop**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600 6-Core Processor, 3600 MHz, 6 Core(s), 12 Logical Processor(s)
GPU NVIDIA GeForce RTX 2060 SUPER
Memory 16GB

### PR DESCRIPTION
**Pull request by amznestebanpapp**
Closes #6241

### CODE REVIEW

**Review by lumberyard-employee-dm — APPROVED** [review]
So this is an issue with using two INTERFACE targets within the same directory?

**Comment by amznestebanpapp** [comment]
> So this is an issue with using two INTERFACE targets within the same directory?

Its actually a mix of things... at the end of the day looks like a CMake bug (https://gitlab.kitware.com/cmake/cmake/-/issues/23043)
In CMake 3.19, when an INTERFACE target has source files, a generator MAY choose to generate a target (e.g. VS generator will generate a project). The project that gets generated in VS is "incomplete", it doesnt have the "IntDir" configured, so it takes the default. The default path is within where the project is defined, which happens to be based on the CMAKE_CURRENT_LIST_DIR.
In LmbrCentral, there were two targets with these conditions, so it ends up generating two projects on the same folder, that because IntDir  is not configured, end up having the same IntDir (and hence the warning").

An easier fix to this would be to remove the header files from the `.Header` target (or the files from the `.Mock` target, but seems better to remove the ones from the Header one). Would that be preferred?

**Comment by lumberyard-employee-dm** [comment]
> > So this is an issue with using two INTERFACE targets within the same directory?
> 
> Its actually a mix of things... at the end of the day looks like a CMake bug (https://gitlab.kitware.com/cmake/cmake/-/issues/23043) In CMake 3.19, when an INTERFACE target has source files, a generator MAY choose to generate a target (e.g. VS generator will generate a project). The project that gets generated in VS is "incomplete", it doesnt have the "IntDir" configured, so it takes the default. The default path is within where the project is defined, which happens to be based on the CMAKE_CURRENT_LIST_DIR. In LmbrCentral, there were two targets with these conditions, so it ends up generating two projects on the same folder, that because IntDir is not configured, end up having the same IntDir (and hence the warning).
> 
> An easier fix to this would be to remove the header files from the `.Header` target (or the files from the `.Mock` target, but seems better to remove the ones from the Header one). Would that be preferred?

Well as long as the files are associated with at one least target, they would be searchable within Visual Studio.

Though I do like the paradigm your currentchange provides, where the Test targets are defined in "Tests" subdirectory and therefore silos the non-Test build script logic from the Test build script logic.

If I were to change anything with what you currently have, it would be to protect the `add_subdirectory(test)` call with `if(PAL_TRAIT_BUILD_TESTS_SUPPORTED)`.

Now does this work in the install layout?

I don't believe the logic to include the CMake file that defines the `LmbrCentral.Editor.Tests` and `LmbrCentral.Tests` target would be added to the `<install-root>/Gems/LmbrCentral/Code/Platform/Windows/Default/permuation.cmake` file.

```cmake
set(configs debug;profile;release)
foreach(config ${configs})
    include("Platform/Windows/Default/LmbrCentral.Editor.Tests_${config}.cmake" OPTIONAL)
endforeach()
``

**Comment by amznestebanpapp** [comment]
> Well as long as the files are associated with at one least target, they would be searchable within Visual Studio.

The `lmbrcentral_headers_files.cmake` file used by `LmbrCentral.API` is also included by the `LmbrCentral.Static` target, so removing the files from `LmbrCentral.API` would still leave those files visible in the `LmbrCentral.Static` target. `LmbrCentral.API` then just becomes an include path.
An upside is that currently a file that is in those two projects shows twice (e.g. in searching). Downside is that `LmbrCentral.API` is then an empty project, and the VS will not generate a project, so its a harder to discover target.

> Though I do like the paradigm your currentchange provides, where the Test targets are defined in "Tests" subdirectory and therefore silos the non-Test build script logic from the Test build script logic.

Yeah, I liked that too, it reduced the size of the `CMakeLIsts.txt`, it also puts the test targets inside a `Tests` folder in the `Gems/LmbrCentral/Code` VS filter.

> If I were to change anything with what you currently have, it would be to protect the `add_subdirectory(test)` call with `if(PAL_TRAIT_BUILD_TESTS_SUPPORTED)`

I thought it was easier to read on the Test side. E.g. if it happened that there was a trait disabling the test, I would expect that to be in the Test `CMakeLists.txt`
I can make it a bit easier to read by doing an `if -> return` at the beginning of the test `CMakeLists.txt`

> Now does this work in the install layout?

I will give it a test, I think it should because it will be seen as yet another `CMakeLists.txt` that needs to be included from the engine root (it wont be included from the LmbrCentral `CMakeLists.txt`).
I wasn't concerned by it because it should be disabled in the SDK (we disable tests). Will give it a try.

**Comment by amznestebanpapp** [comment]
Yes, `install` works well, basically, the generated file `o3de_subdirectories_windows.cmake` ends up having:
```
add_subdirectory(Gems/LmbrCentral/Code)
add_subdirectory(Gems/LmbrCentral/Code/Tests)
```
And that adds those two subdirectories. Then there are two different `CMakeLists.txt` files in those that import the proper targets.

**Review by lumberyard-employee-dm — APPROVED** [review]

**Review by AMZN-alexpete — APPROVED** [review]

**Pull request merged**
