### PR TITLE
LightingChannelConfiguration Reflection

### LINKED ISSUE #17413: Lights Missing from App Launchers
Lighting configuration is missing from game launchers. The level loads appears to load, but the screen is solid-black.

**Steps to reproduce**
1. Open editor and add a light to your level
2. Open level from a game launcher

**Expected behavior**
Level loads and looks the same as it does in Editor

**Actual behavior**
Level loads (maybe) but the scene is solid-black
The lighting configuration(7FFD6D01-BABE-FE35-612F-63A30925E5F7) cannot be loaded.

```
<13:40:24> (LevelSystem) - Level system is loading 'Levels/NewStarbase/NewStarbase.spawnable'

<13:40:24> [Warning] (AssetContainer) - Asset levels/newstarbase/newstarbase.spawnable ({67155E6B-0365-5033-8A95-C193C1334F5B}:cd45fd06) references/depends on asset {3447EBF6-AE6A-58B9-AFA6-315A77582CFF}:0 which does not exist in the catalog and cannot be loaded.
<13:40:24> [Warning] (AssetContainer) - Asset levels/newstarbase/newstarbase.spawnable ({67155E6B-0365-5033-8A95-C193C1334F5B}:cd45fd06) references/depends on asset {81580698-E3EE-5CCB-B290-3FF34F008972}:0 which does not exist in the catalog and cannot be loaded.
<13:40:24> [Warning] (AssetContainer) - Asset levels/newstarbase/newstarbase.spawnable ({67155E6B-0365-5033-8A95-C193C1334F5B}:cd45fd06) references/depends on asset {3D8299AD-A859-514C-8D68-725EEAA453F6}:0 which does not exist in the catalog and cannot be loaded.
<13:40:24> [Warning] (AssetContainer) - Asset levels/newstarbase/newstarbase.spawnable ({67155E6B-0365-5033-8A95-C193C1334F5B}:cd45fd06) references/depends on asset {86F8BBDF-A23B-5CAD-BFDE-86F0DA63993C}:0 which does not exist in the catalog and cannot be loaded.
<13:40:24> [Warning] (AssetContainer) - Asset levels/newstarbase/newstarbase.spawnable ({67155E6B-0365-5033-8A95-C193C1334F5B}:cd45fd06) references/depends on asset {0301BA38-42A3-517B-8663-A6CA6685F16C}:0 which does not exist in the catalog and cannot be loaded.
<13:40:24> [Warning] (AssetContainer) - Asset levels/newstarbase/newstarbase.spawnable ({67155E6B-0365-5033-8A95-C193C1334F5B}:cd45fd06) references/depends on asset {6D4F57E9-E3C4-5850-AE99-40898170A2C3}:0 which does not exist in the catalog and cannot be loaded.
<13:40:24> [Error] (Serialize) - Element 'NULL'(0x408a55cd) with class ID '{7FFD6D01-BABE-FE35-612F-63A30925E5F7}' found in 'AZ::Render::MeshComponentConfig' is not registered with the serializer!
If this class was removed, consider using serializeContext->ClassDeprecate(...) to register classes as having been deprecated to avoid this error.  File levels/newstarbase/newstarbase.network.spawnable
```

**Found in Branch**
development
commit 0b7216e8110ba64602c00dbb3005cbd3306d13f8
Mon Jan 22 12:44:52 2024

### PR DESCRIPTION
**Pull request by AMZN-Gene**
LightingChannelConfiguration needs to be reflected at game runtime, not just in Editor time
Fixes #17413

### CODE REVIEW

**Review by moudgils — APPROVED** [review]

**Review by tkothadev — APPROVED** [review]

**Comment by moudgils** [comment]
Tagging @hosea1008 for visibility. Lets try and do more thorough testing before merging.

**Review by VickyAtAZ — APPROVED** [review]

**Review by gadams3 — APPROVED** [review]

**Review by spham-amzn — APPROVED** [review]

**Comment by hosea1008** [comment]
> Tagging @hosea1008 for visibility. Lets try and do more thorough testing before merging.

Oh, I see. In that PR, the original version of lighting channel is well tested in several of my local projects and game launchers before, but when merging to the community, I refactored the cpp implementation following the review comments and the refactored version is not being able to test thoroughly... I will do it more carefully when my PRs are asked to be refactored or updated a lot.

**Comment by hosea1008** [comment]
Would it be better if we have rendering result comparison test of both Editor, Game mode and Game launcher to prevent further impacts to the visually effect?

**Comment by moudgils** [comment]
> Would it be better if we have rendering result comparison test of both Editor, Game mode and Game launcher to prevent further impacts to the visually effect?

Atom Sample Viewer is suppose to have screenshot comparison testing suite that can be used to ensure we are not introducing a bug. We had also done some work to bring over parts of that testing framework to AutomatedTesting as well but it wasn't fully ported.

**Comment by AMZN-Gene** [comment]
> > Would it be better if we have rendering result comparison test of both Editor, Game mode and Game launcher to prevent further impacts to the visually effect?
> 
> Atom Sample Viewer is suppose to have screenshot comparison testing suite that can be used to ensure we are not introducing a bug. We had also done some work to bring over parts of that testing framework to AutomatedTesting as well but it wasn't fully ported.

Does Atom Sample Viewer use launchers or editor?

**Comment by gadams3** [comment]
> > > Would it be better if we have rendering result comparison test of both Editor, Game mode and Game launcher to prevent further impacts to the visually effect?
> > 
> > 
> > Atom Sample Viewer is suppose to have screenshot comparison testing suite that can be used to ensure we are not introducing a bug. We had also done some work to bring over parts of that testing framework to AutomatedTesting as well but it wasn't fully ported.
> 
> Does Atom Sample Viewer use launchers or editor?

No. It is a separate project with a standalone executable and is completely independent of editor and game components in LY integration and other gems. There was once an effort to migrate all of the atom sample viewer tests to standard automated testing levels using the editor and launcher.

The most common kinds of validation that can be done are unit tests, python tests, lua tests, test levels. We generally avoid screenshot comparisons outside of ASV so that we don't have to store the “golden images” in git. I don't think there would be a problem with doing screen captures within a test to compare before and after or entering and exiting game mode as long as they're cleaned up when the test is finished.

**Comment by AMZN-Gene** [comment]
> > > > Would it be better if we have rendering result comparison test of both Editor, Game mode and Game launcher to prevent further impacts to the visually effect?
> > > 
> > > 
> > > Atom Sample Viewer is suppose to have screenshot comparison testing suite that can be used to ensure we are not introducing a bug. We had also done some work to bring over parts of that testing framework to AutomatedTesting as well but it wasn't fully ported.
> > 
> > 
> > Does Atom Sample Viewer use launchers or editor?
> 
> No. It is a separate project with a standalone executable and is completely independent of editor and game components in LY integration and other gems. There was once an effort to migrate all of the atom sample viewer tests to standard automated testing levels using the editor and launcher.
> 
> The most common kinds of validation that can be done are unit tests, python tests, lua tests, test levels. We generally avoid screenshot comparisons outside of ASV so that we don't have to store the “golden images” in git. I don't think there would be a problem with doing screen captures within a test to compare before and after or entering and exiting game mode as long as they're cleaned up when the test is finished.

As long as the Atom tests are an O3DE application loading in .spawnables, this bug would have been caught. AutomatedTesting levels only dont use a launcher, and the test python scripts are only exposed to Editor.

**Comment by gadams3** [comment]
> > > > > Would it be better if we have rendering result comparison test of both Editor, Game mode and Game launcher to prevent further impacts to the visually effect?
> > > > 
> > > > 
> > > > Atom Sample Viewer is suppose to have screenshot comparison testing suite that can be used to ensure we are not introducing a bug. We had also done some work to bring over parts of that testing framework to AutomatedTesting as well but it wasn't fully ported.
> > > 
> > > 
> > > Does Atom Sample Viewer use launchers or editor?
> > 
> > 
> > No. It is a separate project with a standalone executable and is completely independent of editor and game components in LY integration and other gems. There was once an effort to migrate all of the atom sample viewer tests to standard automated testing levels using the editor and launcher.
> > The most common kinds of validation that can be done are unit tests, python tests, lua tests, test levels. We generally avoid screenshot comparisons outside of ASV so that we don't have to store the “golden images” in git. I don't think there would be a problem with doing screen captures within a test to compare before and after or entering and exiting game mode as long as they're cleaned up when the test is finished.
> 
> As long as the Atom tests are an O3DE application loading in .spawnables, this bug would have been caught. AutomatedTesting levels only dont use a launcher, and the test python scripts are only exposed to Editor.

Python automated test scripts can create or load the level in the editor. Then the script can tell the editor to enter and exit simulation or game mode. From game mode, additional runtime behavior could be controlled via Lua or script canvas. I'm not sure if game mode re-reflects everything to a new context that only includes game/non-editor reflection.

**Comment by moudgils** [comment]
> > > > > > Would it be better if we have rendering result comparison test of both Editor, Game mode and Game launcher to prevent further impacts to the visually effect?
> > > > > 
> > > > > 
> > > > > Atom Sample Viewer is suppose to have screenshot comparison testing suite that can be used to ensure we are not introducing a bug. We had also done some work to bring over parts of that testing framework to AutomatedTesting as well but it wasn't fully ported.
> > > > 
> > > > 
> > > > Does Atom Sample Viewer use launchers or editor?
> > > 
> > > 
> > > No. It is a separate project with a standalone executable and is completely independent of editor and game components in LY integration and other gems. There was once an effort to migrate all of the atom sample viewer tests to standard automated testing levels using the editor and launcher.
> > > The most common kinds of validation that can be done are unit tests, python tests, lua tests, test levels. We generally avoid screenshot comparisons outside of ASV so that we don't have to store the “golden images” in git. I don't think there would be a problem with doing screen captures within a test to compare before and after or entering and exiting game mode as long as they're cleaned up when the test is finished.
> > 
> > 
> > As long as the Atom tests are an O3DE application loading in .spawnables, this bug would have been caught. AutomatedTesting levels only dont use a launcher, and the test python scripts are only exposed to Editor.
> 
> Python automated test scripts can create or load the level in the editor. Then the script can tell the editor to enter and exit simulation or game mode. From game mode, additional runtime behavior could be controlled via Lua or script canvas. I'm not sure if game mode re-reflects everything to a new context that only includes game/non-editor reflection.

My recommendation is to expand and use the testing framework we had started porting from ASV to AutomatedTesting as it will mean less friction for testing purposes and easy to expand and maintain. Take a look at some levels that were already built to help with this
Level for testing Area lights - /Users/moudgils/GitHub/o3de/AutomatedTesting/Levels/AtomScreenshotTests/Feature/AreaLight

Scripts/Screenshots for testing related to that level - /Users/moudgils/GitHub/o3de/AutomatedTesting/AutomationScripts/ExpectedScreenshots/MainRenderPipeline/windows

**Pull request merged**
