### PR TITLE
Change all usages of AZ_CRC with constexpr arguments to AZ_CRC_CE

### PR DESCRIPTION
**Pull request by mprettner-huawei**
## What does this PR do?

This PR changes all usages of the `AZ_CRC` macro which use constexpr arguments to use `AZ_CRC_CE`. Also I updated the docstrings in `Crc.h` to discourage usage of the two-parameter version of `AZ_CRC`. I also intentionally updated usages within commented out code.
Although there are some open issues about crc value and string value not matching (#10233 #10234 #10235), but this does no longer seem to be the case.

I know this is a very large PR; but even though this was mostly achieved with regex operations, I checked all changes fairly thoroughly, so I am fairly confident that no unintended side-effects were introduced.

A further objective would be to completely remove the `AZ_CRC` macro version with 2 parameters, since it should no longer be necessary (but might still be used by external gems, o3de-extras, and so on).

## How was this PR tested?

Compile on Windows + AR. Since the `CrcValidator` for PRs would detect a mismatch between string value and crc value in the two-parameter version, I dont think that any string-crc-mismatches are still in the code, so this should not change any behaviour.

### CODE REVIEW

**Comment by pollend** [comment]
I think there is some concern with inflated compile times because this logic is getting resolved in a constexpr. Remember discussing this with @nick-l-o3de

**Review by gadams3 — APPROVED** [review]
I reviewed the first half of the files and most of the ones that did not auto expand. I can't be 100% sure that I did not miss any. This should be a good change. It should prevent potential issues from creeping in when the string in this CRC changes but the injected value is not updated. Curious how this affects compile times.  It would be useful to have a script crawl the code base to create a file with mappings between the string and crc value to look up for debugging.

**Comment by nick-l-o3de** [comment]
> I think there is some concern with inflated compile times because this logic is getting resolved in a constexpr. Remember discussing this with @nick-l-o3de

Its not wrong to use `AZ_CRC_CE` - I just kept using the old one because I knew I could compute it once, with something like https://emn178.github.io/online-tools/crc32.html and it output the same results as `AZ::Crc32` does, (as long as you lowercase the input).    Compute it once, as in, when I do it, manually, using a website or something, as opposed to automatically by the compiler, but every single time that header file is ever included in any other compile or include chain, burning CPU time to compute it over and over in every compile unit every time its compiled.  I have a potato computer so any compile time or memory saving is important to me.

 I can't currently prove or measure how much time it takes, and it could be very small or very large, but I know that using the AZ_CRC(...) with a crc parameter definitely costs no significant compile time at all (since its basically no op) and also leaves the CRC value in the code so you can search it if you see an error like `Error, component needs service 0x2131312!` whereas its not searchable with AZ_CRC_CE.

I can't object to this though.  Its an opinion thing, and both the CE and regular versions work and have their pros and cons (for example, the non-CE version is easier to mess up and copy and paste without remembering to change the code).

Its going to make tools like the crc-scanner (I think its somewhere in scripts or validation?).  IIRC it scans the code for AZ_CRC and AZ_CRC_CE and outputs a rainbow table for it, so if you are debugging one of those horrible error messages with a CRC you can use it to reverse look up.

On the other hand, I believe that architecturally, the use of CRC32 and GUIDS all over the place, instead of AZ::Name or even just... literally keeping things as strings... is probably a case of overcomplication and premature optimization anyway.    Longer term we might be able to use AZ_CRC_CE to eventually dig ourselves out of this hole since its possible to replace that macro with something else that preserves the strings or uses AZ::Name under the hood.

Either way... nothing wrong IMO with changing it all over.   It will make its eventual eradication easier.

**Comment by nick-l-o3de** [comment]
Its going to take a long time to scroll thru this and review it tho.  Give us time.

**Comment by mprettner-huawei** [comment]
I did some primitive testing of the compile times:
* Add `set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE "${CMAKE_COMMAND} -E time")` to the root cmake, this gives a time in seconds for each cpp target
* Run the compile for 7a569a84 (old version) and for 766ef3b7 (new version) with one thread
* Get the compile output and clean it up with some regexes
* Import to Excel ([compiletimes.xlsx](https://github.com/user-attachments/files/16245516/compiletimes.xlsx))

The result is as follows:
* Total compile time increased from 13084 to 13165 seconds (+81 seconds, +0.62%)
* For 535 files the compile times went down, for 847 compile time went up

Remarks:
* I removed the PhysX files from the comparison, since there was a version mismatch and not the same files were used; not sure how this happened; the PhysX files in total compile 6.5 seconds (0.76%) slower
* Measuring time like this is not the most accurate; but nonetheless it shows that no enormous, unexpected compile time degradation has happened; so I am somewhat confident that these changes do not negatively impact the developer experience

**Review by nick-l-o3de — APPROVED** [review]
I used automation to review this, I found that the only lines changed that did NOT contain changes specifically from AZ_CRC to AZ_CRC_CE were 
1. comments changed in AzCore/AzCore/Math/Crc.h
2. A couple extra blank lines added to AzCore/Serialization/EditContextConstants.inl for readability
3. constexpr additions in Tools/AssetProcessor/native/Assetprocessor.h
4. blank lines added to Tools/LuiIDE/Source/LUA/LUAEditorContext.cpp (for readability)
5. constexpr added to Code/Tools/SceneAPI/SceneData/Behaviors/Skingroup.h
6. Gems/LyShine/Code/Source/UiTransform2dComponent.cpp constexpr and variable name change 
7. Gems/TextureAtlas/Code/Source/TextureAtlasImpl.cpp got constexpr
Looks fine to me

**Pull request merged**
