### PR TITLE
Physx main optimized tests prefab conversion

### PR DESCRIPTION
**Pull request by FuzzyCarterAWS**
Tests converted:

TestSuite_Main:

- test_Tick_CharacterGameplayComponentMotionIsSmooth
- test_Tick_InterpolatedRigidBodyMotionIsSmooth
- test_Joints_HingeLeadFollowerCollide
- test_Collider_DiffCollisionGroupDiffCollidingLayersNotCollide
- test_ShapeCollider_CylinderShapeCollides
- test_ScriptCanvas_MultipleRaycastNode
- test_Collider_SameCollisionGroupDiffLayersCollide
- test_Material_DynamicFriction
- test_ForceRegion_LocalSpaceForceOnRigidBodies
- test_RigidBody_EnablingGravityWorksUsingNotificationsPoC

TestSuite_Main_Optimized:

- C4976195_RigidBodies_InitialLinearVelocity
- C4976206_RigidBodies_GravityEnabledActive
- C4976207_PhysXRigidBodies_KinematicBehavior
- C5932042_PhysXForceRegion_LinearDamping
- C5932043_ForceRegion_SimpleDragOnRigidBodies
- C5959760_PhysXForceRegion_PointForceExertion
- C5959764_ForceRegion_ForceRegionImpulsesCapsule
- C5340400_RigidBody_ManualMomentOfInertia
- C4976210_COM_ManualSetting
- C4976194_RigidBody_PhysXComponentIsValid
- C5932045_ForceRegion_Spline
- C4982797_Collider_ColliderOffset
- C4976200_RigidBody_AngularDampingObjectRotation
- C5689529_Verify_Terrain_RigidBody_Collider_Mesh
- C5959810_ForceRegion_ForceRegionCombinesForces
- C5959765_ForceRegion_AssetGetsImpulsed
- C6274125_ScriptCanvas_TriggerEvents
- C6090554_ForceRegion_PointForceNegative
- C6090550_ForceRegion_WorldSpaceForceNegative
- C6090552_ForceRegion_LinearDampingNegative
- C5968760_ForceRegion_CheckNetForceChange
- C12712452_ScriptCanvas_CollisionEvents
- C12868578_ForceRegion_DirectionHasNoAffectOnMagnitude
- C4976204_Verify_Start_Asleep_Condition
- C6090551_ForceRegion_LocalSpaceForceNegative
- C6090553_ForceRegion_SimpleDragForceOnRigidBodies
- C4976209_RigidBody_ComputesCOM
- C4976201_RigidBody_MassIsAssigned
- C5296614_PhysXMaterial_ColliderShape
- C4982595_Collider_TriggerDisablesCollision
- C14976307_Gravity_SetGravityWorks
- C4044694_Material_EmptyLibraryUsesDefault
- C15845879_ForceRegion_HighLinearDampingForce
- C4976218_RigidBodies_InertiaObjectsNotComputed
- C12868580_ForceRegion_SplineModifiedTransform
- C4976197_RigidBodies_InitialAngularVelocity
- C6090555_ForceRegion_SplineFollowOnRigidBodies
- C5959808_ForceRegion_PositionOffset
- C13895144_Ragdoll_ChangeLevel
- C5968759_ForceRegion_ExertsSeveralForcesOnRigidBody
- C4976202_RigidBody_StopsWhenBelowKineticThreshold
- C13351703_COM_NotIncludeTriggerShapes
- C14902098_ScriptCanvas_PostPhysicsUpdate
- C5959761_ForceRegion_PhysAssetExertsPointForce
- C13352089_RigidBodies_MaxAngularVelocity
- C18243584_Joints_HingeSoftLimitsConstrained
- C18243589_Joints_BallSoftLimitsConstrained
- C18243591_Joints_BallLeadFollowerCollide
- C5932040_ForceRegion_CubeExertsWorldForce
- C5932044_ForceRegion_PointForceOnRigidBody
- C5959759_RigidBody_ForceRegionSpherePointForce
- C5959809_ForceRegion_RotationalOffset
- C100000_RigidBody_EnablingGravityWorksPoC
- C4982798_Collider_ColliderRotationOffset
- C6090547_ForceRegion_ParentChildForceRegions

Unconverted due to test failing after conversion:
- Main: test_C15425929_Undo_Redo (Manual Conversion)
- Periodic: test_Physics_UndoRedoWorksOnEntityWithPhysComponents (Manual Conversion)
- Main_Optimized: C15425929_Undo_Redo (Manual Conversion)
- Main_Optimized: C12712455_ScriptCanvas_ShapeCastVerification (Manual Conversion)
- Periodic: test_ScriptCanvas_ShapeCast (Manual Conversion)
- C6090546_ForceRegion_SliceFileInstantiates (See: #7005)
- Periodic: test_ForceRegion_SliceFileInstantiates (See: #7005)

Tested with the following command:
`python\python.cmd -m pytest --build-directory e:/gws/o3de/build/physxconversion/bin/profile e:\gws\o3de\AutomatedTesting\Gem\PythonTests\Physics\TestSuite_Main.py`

### CODE REVIEW

**Review by chiyenteng — APPROVED** [review]

**Review by chiyenteng — CHANGES_REQUESTED** [review]
You haven't converted tests in **TestSuite_Main_Optimized.py**.

**Review by hultonha — APPROVED** [review]
This looks good to me as an incremental change, thanks for working on these 👍

**Review by greerdv — APPROVED** [review]

**Review by SergeyAMZN — APPROVED** [review]

**Comment by chiyenteng** [comment]
> > You haven't converted tests in **TestSuite_Main_Optimized.py**.
> 
> Is it not okay to do that in a separate PR?

It's fine to have a separate PR for that. If so, I would suggest to rename this PR to prevent confusion.

**Review by chiyenteng — APPROVED** [review]

**Review by chiyenteng — COMMENTED** [review]
Nit: You put 
```
class C15425929_Undo_Redo(EditorSharedTest):
        from .tests import Physics_UndoRedoWorksOnEntityWithPhysComponents as test_module
```
In TestSuite_Main_Optimized.py::TestAutomation twice.

**Comment by hultonha** [comment]
This is looking great! Looking forward to getting these changes in 🙂

**Review by chiyenteng — CHANGES_REQUESTED** [review]
Overall this looks good to me.
Just one thing. Can you revert your [commit about **ForceRegion_SliceFileInstantiates** test conversion](https://github.com/o3de/o3de/commit/4d11131566af23c0f64ce1a6b58cd0900c5023e6) since we already have a separate issue for it(#7005), and this test can't simply be converted by the converter tool only.

See #7005 for more details.

**Review by chiyenteng — APPROVED** [review]
LGTM.

**Pull request merged**
