### PR TITLE
Fixes the test_BasicLevelSetup_SetsUpLevel() test and adds proper asserts for screenshot comparisons.

### PR DESCRIPTION
**Pull request by jromnoa**
- The screenshot comparison result wasn't being asserted against anything after the hydra script ran. I re-added that. It used a `general.log()` string for `Screenshot failed` but since that no longer appears on AR it is not sufficient for testing failure. It now `asserts` against the golden image vs. screenshot comparisons after the hydra script runs.
- The screenshot comparisons failed due to the scene itself being setup improperly (wrong asset call order and wrong asset paths). Additionally, I had to add the `plane.fbx` asset to the Atom gem `TestData` assets. It will pass now and fail correctly when a screenshot comparison fails (no longer using log lines to test failure but asserts).
- ~~Lastly, this cannot be merged because it will fail immediately due to another bug. DM me for more info (do not want to post the link in a public repo).~~ It's been fixed in latest development branch.
- Passing results for all of the tests except the benchmark tests below (benchmark tests need filebeat info and I don't want to muddy the metrics with local results so I skipped running that one locally):
```
==== 4 passed in 310.16s (0:05:10) ====
```

### CODE REVIEW

**Review by smurly — APPROVED** [review]
seems more bullet proof to throw an exception, but would the error line for mismatch result in more match attempts? that is will this exit the test on the first mismatch vs the old system that would indicate all screenshots that failed if there were multiple screenshots? there's a small chance that multiple rounds of screenshot fixing may be needed to fix all failed screenshots; failures may be hidden.

**Comment by jromnoa** [comment]
@smurly We can't use `general.log()` any more on AR - it doesn't show up. That's why this test was silently failing without us knowing. Adding the asserts makes it fail appropriately and closer to the new model (return codes).

Additionally, all of the screenshots are uploaded to s3 on failure using a `.zip` file so it will include all of the screenshots and not just 1 that failed.

**Comment by jromnoa** [comment]
Ran my branch job using the `test_gpu_profile_vs2019` job target and it passed. If you want a link DM me:
```
Start 18: AutomatedTesting::Atom_TestSuite_Main_GPU.main::TEST_RUN
1/9 Test #18: AutomatedTesting::Atom_TestSuite_Main_GPU.main::TEST_RUN .............   Passed  356.66 sec
Start 19: AutomatedTesting::Atom_TestSuite_Main_GPU_Optimized.main::TEST_RUN
2/9 Test #19: AutomatedTesting::Atom_TestSuite_Main_GPU_Optimized.main::TEST_RUN ...   Passed   15.88 sec
```

**Review by NeilGitGud — APPROVED** [review]
Updates seem fine (don't see any formatting errors), and all the tests pass. Ship it!

**Pull request merged**
