### PR TITLE
Enable ragdoll manipulators feature by default, and update ragdoll viewport UI icons

### PR DESCRIPTION
**Pull request by greerdv**
## What does this PR do?
Changes CVAR enabling ragdoll manipulators to default on. Updates icons for joint limit viewport UI cluster.

## How was this PR tested?
Verified that feature was on by default and icons appeared as expected.

### CODE REVIEW

**Comment by greerdv** [comment]
ragdoll-viewport-ui

**Review by hultonha — APPROVED** [review]
LGTM! Great work @greerdv 👍

**Review by SergeyAMZN — APPROVED** [review]

**Review by moraaar — APPROVED** [review]
LGTM! Does this PR requires special approval process since it's submitting to stabilization branch directly?

**Comment by greerdv** [comment]
> LGTM! Does this PR requires special approval process since it's submitting to stabilization branch directly?

Yeah, will work with hultonha to do that.

**Comment by hultonha** [comment]
## Exception Tracking

* [ ] 1. Owning SIG requests the exception, by a Sig Representative (Chair/co-chair) adding the PR to the exception requests queue board.
* [ ] 2. Owning SIG comments on the PR explaining impact if this code does not go into stabilization.
* [ ] 3. Unrelated SIG representative (chair/cochair) approves the exception, adding a comment indicating approval and the SIG they represent.
* [ ] 4. UX SIG representative (chair/cochair) approves the exception, adding a comment indicating approval and the SIG they represent.
* [ ] 5. Testing SIG representative (chair/cochair) approves the exception, adding a comment indicating approval and the SIG they represent.
* [ ] (Must occur at some point before SIG-Release approval) Code has been approved for merging by maintainers
* [ ] 6. SIG-Release Release Manager or co-Release Manager approves the exception, adding a comment indicating approval and the SIG they represent.
* [ ] 7. If all approvals are accepted, then the exception PR may be merged
* [ ] 8. Merged PR is verified successful via testing. If Merged PR verification testing failed, consult reps from step 3-5 and discussion occurs on fixing the failure vs backing out change
* [ ] 9. Exception is complete

**Review by lgleim — APPROVED** [review]
Approved in behalf of sig-simulation.

## Impact if not merged
If not merged, the ragdoll manipulators feature will not be enabled by default and thus less accessible by users.

**Comment by galibzon** [comment]
Approved.

**Review by galibzon — APPROVED** [review]

**Review by Kadino — APPROVED** [review]
Approved on behalf of SIG-Testing. This is a low-risk and UI-specific change, which would be both difficult and inconsequential to write an automated test to cover.

**Comment by yuyihsu** [comment]
Approved on behave of SIG-UI-UX. Thanks Dave for the great work.

**Comment by vincent6767** [comment]
As SIG-Release co-chair, I approve PR. It's ok to merge.

**Pull request merged**
