### PR TITLE
Fix crash in LocalPredictionInputComponent desync debugging

### PR DESCRIPTION
**Pull request by AMZN-puvvadar**
This change addresses the crash described in https://github.com/o3de/o3de/issues/8463

It is possible for m_inputHistory to be length 0 and this was not properly accounted for.

Signed-off-by: puvvadar <puvvadar@amazon.com>

### CODE REVIEW

**Review by AMZN-Gene — APPROVED** [review]

**Review by AMZN-alexpete — APPROVED** [review]

**Comment by lmbr-pip** [comment]
Should this be a candidate for stabilization?
Should we cover this with automation test change?

**Comment by AMZN-puvvadar** [comment]
> Should this be a candidate for stabilization? Should we cover this with automation test change?

I'm not sure that there is test story around LocalPredictionInputComponent. Stabilization is a good question. I'm open to changing the destination of the merge.

**Comment by Kadino** [comment]
Unclear why changing the base branch added sig-testing

**Comment by AMZN-puvvadar** [comment]
Closing in favor of merge to stabilization/2205 in https://github.com/o3de/o3de/pull/9231

**Pull request closed without merging**
