### PR TITLE
Remove legacy Joint Outliner (#11311)

### LINKED ISSUE #11311: Remove Legacy Joint Outliner
[Migrated from JIRA LYN-14522]
The legacy "Joint Outliner" (EMStudio::NodeWindowPlugin) will be replaced with the "Skeletal Outliner" (EMotionFX::SkeletonOutlinerPlugin).

Remove the old joint outliner after the new skeletal outliner shows the character (done with [https://github.com/o3de/o3de/issues/10962)] and all the joint properties are shown correctly in the inspector (base joint properties, hit detection/ragdoll/cloth colliders as well as the simulated object colliders).

The Character layout has to be updated as well. Remove the Joint Outliner window by pressing the X of the dock widget, and use the menu to add the skeleton outliner to replace it. After that use the layouts menu item to overwrite the layout.

**Acceptance Criteria:**
 * The legacy joint outliner is not present anymore in all the available layouts.
 * The legacy joint outliner has been replaced with the new skeleton outliner in all available layouts.
 * NodeWindowPlugin.h/.cpp got removed from the codebase

### PR DESCRIPTION
**Pull request by aambrosano**
## What does this PR do?

Remove Joint Outliner from the Character layout in EmotionFX.

Resolves #11311

## How was this PR tested?

Manual testing (loading the layout and ensuring the Joint Outliner wasn't there), plus automated testing.

### CODE REVIEW

**Review by gadams3 — APPROVED** [review]

**Review by amzn-jillich — APPROVED** [review]

**Comment by amzn-jillich** [comment]
Code looks good. Just added the do-not-merge label as we need to merge https://github.com/o3de/o3de/pull/12060 before this.

**Review by amzn-rhhong — APPROVED** [review]

**Review by cgalvan — APPROVED** [review]

**Comment by hultonha** [comment]
@aambrosano Can you please see if you can fix the DCO issue. There should be instructions you can see in the `details` page. If you're still having issues please contact me directly or reach out to @amzn-changml

**Comment by aambrosano** [comment]
Sorry, thought I did that already on my first PR, will fix that right away.

**Comment by hultonha** [comment]
Awesome thank you @aambrosano, I'll kick off a build now :+1:

**Comment by hultonha** [comment]
We discussed this in the Wednesday meeting, it is likely another rebase to latest development will help (there has been some instability recently due to the stabilization branch split which should be fixed now afaik - if you still have issues let me know). I can kick off another build as soon as it's rebased.

**Comment by hultonha** [comment]
I've started a build now just in case, so only rebase if this has failed again @aambrosano. Thanks!

**Pull request merged**
