### PR TITLE
Added pass class

### PR DESCRIPTION
**Pull request by tjmgd**
Signed-off-by: T.J. McGrath-Daly <tj.mcgrath.daly@huawei.com>

### CODE REVIEW

**Comment by tjmgd** [comment]
This is a replacement PR for https://github.com/o3de/o3de/pull/5553

The original had a sign off issue that could not be easily resolved through rebase.

From Original:

This is the second of a pair of pull requests designed to allow unnecessary processes to be disabled when there is no DiffuseProbeGrid in the level. See the following issue:

github.com//issues/3755

**Review by rgba16f — APPROVED** [review]

**Review by mrieggeramzn — APPROVED** [review]

**Comment by amznestebanpapp** [comment]
triggered a new build since its being a while it was run

**Comment by HogJonny-AMZN** [comment]
@rgba16f and @amznestebanpapp we believe that this PR caused the following:
https://github.com/o3de/o3de/issues/6680

**Comment by rgba16f** [comment]
@tjmgd This change seems to have caused some rendering bugs on PC.

**Pull request merged**
