### PR TITLE
Remove Visual Components from Headless Spawnable Assets

### PR DESCRIPTION
**Pull request by AMZN-Gene**
- Create a new prefab processor (AssetPlatformComponentRemover) to remove components based on asset tag.
- AssetPlatformComponentRemover::Process will iterator over each entity component and remove unnecessary components based on _prefab.tools.setreg_
- Remove mesh and material from server spawnables.

Tested by building pc and server assets, opening pc and server spawnable and seeing that mesh/material components were removed.
Testing by running headless server with server assets and successfully connecting client to multiplayer simulation.

### CODE REVIEW

**Review by gadams3 — COMMENTED** [review]
Should this also remove components that depend on the ones being removed?

**Comment by AMZN-Gene** [comment]
> Should this also remove components that depend on the ones being removed?

Good call! I'd avoid implicitly deleting components. I'll make sure EvaluateDependencies is called at some point and the user should see an error that they are removing something that is depended upon. (They can then decide to also remove that extra component, or re-evaluate deleting the component in the first place if it's actually needed)

**Comment by AMZN-Gene** [comment]
Update prefab process to return unsuccessful if it removed a component that's required by another.
Logging errors for user to see.
Adding unit tests

**Review by gadams3 — APPROVED** [review]
Saw that error reporting was added for evaluating component dependencies upon removal

**Pull request merged**
