### PR TITLE
Marking script canvas failing tests as xfail until they can be reworked to make them pass.

### PR DESCRIPTION
**Pull request by moraaar**
Signed-off-by: moraaar <moraaar@amazon.com>

### CODE REVIEW

**Comment by AMZN-AlexOteiza** [comment]
Don't move the failing tests to Sandbox.
Sandbox is supposed to host only Flaky tests and be run with high frequency in order to make sure that they are not flaky anymore.

For failing tests, either mark them as xfail and/or create a ticket to get them fixed

**Comment by greerdv** [comment]
This seems like a lot of work to move tests between suites. It seems like it ought to be possible to structure the tests so that it's a much smaller change to move them to another suite.

**Comment by moraaar** [comment]
>Don't move the failing tests to Sandbox.
>Sandbox is supposed to host only Flaky tests and be run with high frequency in order to make sure that they are not flaky anymore.
>For failing tests, either mark them as xfail and/or create a ticket to get them fixed

That's a fair point. I'll revert my changes and add xfail instead + create the Jira task for it.

**Comment by moraaar** [comment]
>This seems like a lot of work to move tests between suites. It seems like it ought to be possible to structure the tests so that it's a much smaller change to move them to another suite.

That's how it's been arranged at the moment, 1 file per test suite, so to move one test from one test suite to another you have to modify both files. Not sure if you can mark one test to run in an specific test suite, but that'd still be counter intuitive because the test would still be inside a file that covers 1 test suite (for example marking one test for Sandbox but it's inside the TestSuite_Periodic file).

In any case, back to this specific PR, I think Alex is right and for tests that actually fail (not flaky ones) is better to use the `xfail` marker, because the test is in the right test suite, it's just that something is wrong with it and must be fixed. By marking it `xfail` it will still run in the same test suite, fail, but will not cause the Jenkins job to go red.

**Review by AMZN-AlexOteiza — APPROVED** [review]
LGTM, make sure there are tasks assigned to fixed these tests

**Pull request merged**
