### PR TITLE
[LYN-6838] Various Monolithic shutdown fixes for the GameLauncher

### PR DESCRIPTION
**Pull request by lemonade-dm**
- Added a stateless_allocator class for AZStd containers that doesn't require an AZ::AllocatorInstance. This allocator uses AZ_OS_MALLOC/AZ_OS_FREE and is available during static de-initialization, so types which uses it are able to deallocate without crashing.
- Changed the EBus EBusContainer [AddressStorage](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/EBus/Internal/StoragePolicies.h#L43-L106) types to use the internal EBusEnvironmentAllocator instead of the AZ::SystemAllocator. The AZ::SystemAllocator is not available when the EBus::Context is destroyed in static deinitialization, leading to another shutdown crash.
- Updated static variables to either use fixed size types that don't perform heap allocation or modified them to use the stateless_allocator so that they deallocate properly.
- Fixed various other shutdown crashes due to static variables being destructed after the allocator for it has been destroyed.

### CODE REVIEW

**Comment by hultonha** [comment]
@lumberyard-employee-dm I've discovered the change in `IMovieSystem` broke Track View

This line...

`AZStd::basic_string<char, AZStd::char_traits<char>, AZStd::stateless_allocator> m_name;` (instead of just `AZStd::string`)

This does not serialize correctly, so the `m_name` field is left blank and sequences don't play correctly, might have to back this out temporarily or think of a fix.

**Comment by lumberyard-employee-dm** [comment]
> @lumberyard-employee-dm I've discovered the change in `IMovieSystem` broke Track View
> 
> This line...
> 
> `AZStd::basic_string<char, AZStd::char_traits<char>, AZStd::stateless_allocator> m_name;` (instead of just `AZStd::string`)
> 
> This does not serialize correctly, so the `m_name` field is left blank and sequences don't play correctly, might have to back this out temporarily or think of a fix.

@hultonha This can be fixed with a version bump and a version converter [here](https://github.com/o3de/o3de/blob/development/Gems/Maestro/Code/Source/Cinematics/AnimSerializer.cpp#L20-L23)

The AnimSerializer::ReflectAnimTypes just needs to be updated with the following version converter

```
auto CAnimParamTypeVersionConverter = [](AZ::SerializeContext& context,
    AZ::SerializeContext::DataElementNode& rootElement) -> bool
{
    if (rootElement.GetVersion() < 2)
    {
        constexpr AZ::u32 NameCrc = AZ_CRC_CE("Name");
        AZStd::string oldName;
        if (!rootElement.GetChildData(NameCrc, oldName))
        {
            AZ_Error("AnimSerializer", false, R"(Unable to read "Name" field with type AZStd::string from instance of CAnimParamType)"
                " with version number %u", rootElement.GetVersion());
            return false;
        }

        decltype(CAnimParamType::m_name) newNameType(oldName);
        // Remove the "Name" field with AZStd::string type and re-add it with
        // the AZStd::basic_string<char, AZStd::char_traits<char>, AZStd::stateless_allocator> type
        rootElement.RemoveElementByName(NameCrc);
        rootElement.AddElementWithData(context, "Name", newNameType);
    }

    return true;
};
// Reflection for Maestro's AZ_TYPE_INFO'ed classes
serializeContext->Class<CAnimParamType>()
    ->Version(2, CAnimParamTypeVersionConverter)
    ->Field("Type", &CAnimParamType::m_type)
    ->Field("Name", &CAnimParamType::m_name);
```

**Comment by hultonha** [comment]
@lumberyard-employee-dm I don't think this is just a version converter issue though, as this happens for newly created sequences. I think it's potentially more likely something to do with `AZStd::basic_string<char, AZStd::char_traits<char>, AZStd::stateless_allocator> m_name;`. If we fix the global usages of `CAnimParamType` can we then switch this back to use a regular `AZStd::string`? It would likely be worth investigating why the string with a `stateless_allocator` cannot be serialized correctly too.

**Comment by amznestebanpapp** [comment]
> stateless_allocator

In that case, it should be fine to chagne it to AZStd::string, the `stateless_allocator` was likely created to bypass static initialization/deinitialization issues. I dont see that member being created/destroyed during static initialization/deinitialization.

Likely that member cannot serialize because there is no implementation of the serializer for that template specialization.

**Comment by lumberyard-employee-dm** [comment]
None of the allocators are serialized or attempt to be serialized.
There types are only used in the Aggregation of `AZ::TypeId` when creating the complete type.
The `stateless_allocator` implements `AZ_TYPE_INFO` which is all that is needed to form the proper string type.

**Comment by hultonha** [comment]
> > stateless_allocator
> 
> In that case, it should be fine to chagne it to AZStd::string, the `stateless_allocator` was likely created to bypass static initialization/deinitialization issues. I dont see that member being created/destroyed during static initialization/deinitialization.
> 
> Likely that member cannot serialize because there is no implementation of the serializer for that template specialization.

If there are no more global usages of `CAnimParamType` that's awesome and I can just create a PR switching back the string type to a standard `AZStd::string` (I take it I'd still need something similar to @lumberyard-employee-dm's suggested converter though to be safe? It might not be necessary as this change went in so recently, and it's not going to work right now anyway).

> None of the allocators are serialized or attempt to be serialized. There types are only used in the Aggregation of `AZ::TypeId` when creating the complete type. The `stateless_allocator` implements `AZ_TYPE_INFO` which is all that is needed to form the proper string type.

There must still be something odd going on then with the string value not being persisted, I wonder if it might be possible to setup a test case to reproduce the issue from a unit test. It might be simpler to try and debug it there if we can repro it.

**Pull request merged**
