### PR TITLE
Focus Mode | Show helpers even when they're not selectable, but keep the current behavior for icons.

### PR DESCRIPTION
**Pull request by AMZN-daimini**
Restores previous behavior for editor helpers - makes them always visible, while the current editor hides them if they're owned by entities in a closed prefab. Behavior for icons stay the same (icons are only shown for entities that are actually directly selectable).

Before
shapeVisibility_before

After
shapeVisibility_after

Will discuss the change with UX before this is submitted.

FYI @rainbj @amzn-leenguy

### CODE REVIEW

**Review by srikappa-amzn — APPROVED** [review]
Looks good to go after ux approval!

**Review by NicholasVanSickle — APPROVED** [review]

**Review by gadams3 — APPROVED** [review]

**Review by hultonha — APPROVED** [review]
Change looks good, though with viewport we are trying really hard to maintain test coverage when we make behavior changes like this (there are some added for when icons should/shouldn't draw). I'd really appreciate if we catch-up briefly about how to test this as I don't think it would be that hard (I'll have a little look into it today). This can be merged but please open a separate issue that is to add a test to verify this behavior (we want to encode it in a test so we get alerted if the behavior changes inadvertently in future).

**Review by cgalvan — APPROVED** [review]

**Comment by AMZN-daimini** [comment]
> Change looks good, though with viewport we are trying really hard to maintain test coverage when we make behavior changes like this (there are some added for when icons should/shouldn't draw). I'd really appreciate if we catch-up briefly about how to test this as I don't think it would be that hard (I'll have a little look into it today). This can be merged but please open a separate issue that is to add a test to verify this behavior (we want to encode it in a test so we get alerted if the behavior changes inadvertently in future).

Sounds good. We have a short meeting with UX today to verify this is the correct behavior, once this goes in I will add a task to add unit tests :)

**Comment by hultonha** [comment]
> > Change looks good, though with viewport we are trying really hard to maintain test coverage when we make behavior changes like this (there are some added for when icons should/shouldn't draw). I'd really appreciate if we catch-up briefly about how to test this as I don't think it would be that hard (I'll have a little look into it today). This can be merged but please open a separate issue that is to add a test to verify this behavior (we want to encode it in a test so we get alerted if the behavior changes inadvertently in future).
> 
> Sounds good. We have a short meeting with UX today to verify this is the correct behavior, once this goes in I will add a task to add unit tests :)

Awesome! Happy to help with them, can discuss once you get confirmation 👍

**Comment by amzn-leenguy** [comment]
> > Change looks good, though with viewport we are trying really hard to maintain test coverage when we make behavior changes like this (there are some added for when icons should/shouldn't draw). I'd really appreciate if we catch-up briefly about how to test this as I don't think it would be that hard (I'll have a little look into it today). This can be merged but please open a separate issue that is to add a test to verify this behavior (we want to encode it in a test so we get alerted if the behavior changes inadvertently in future).
> 
> Sounds good. We have a short meeting with UX today to verify this is the correct behavior, once this goes in I will add a task to add unit tests :)

please loop me in on the conclusion thanks!

**Comment by AMZN-daimini** [comment]
> > > Change looks good, though with viewport we are trying really hard to maintain test coverage when we make behavior changes like this (there are some added for when icons should/shouldn't draw). I'd really appreciate if we catch-up briefly about how to test this as I don't think it would be that hard (I'll have a little look into it today). This can be merged but please open a separate issue that is to add a test to verify this behavior (we want to encode it in a test so we get alerted if the behavior changes inadvertently in future).
> > 
> > 
> > Sounds good. We have a short meeting with UX today to verify this is the correct behavior, once this goes in I will add a task to add unit tests :)
> 
> please loop me in on the conclusion thanks!

We determined this is the correct behavior. Conversation resulted in a couple other minor issues that I'm going to log now.
I will also add a task for unit tests :D

**Comment by hultonha** [comment]
Sounds great thanks! If you can tag me or forward me the issues once they're created I'd appreciate it, cheers!

**Pull request merged**
