### PR TITLE
bugfix: resolve block comment selection

### PR DESCRIPTION
**Pull request by pollend**
https://user-images.githubusercontent.com/854359/145703656-237b4f8b-183c-4894-ab6e-83f4114d7086.mp4

ref: https://github.com/o3de/o3de/issues/6364

Signed-off-by: Michael Pollind <mpollind@gmail.com>

### CODE REVIEW

**Comment by pollend** [comment]
its so strange that the comment command doesn't also uncomment the line.

**Review by cgalvan — APPROVED** [review]

**Review by hultonha — APPROVED** [review]
I would love a test for this 😅 but this PR as is looks good! 🙂

**Comment by pollend** [comment]
> I would love a test for this sweat_smile but this PR as is looks good! slightly_smiling_face

would like to rework it so its not soo weird XD. comment and uncomment are different keybinds. would like to have a single keybind that comments/uncomments code. The cursor gets moved to beginning last line regardless of where it was already etc ...

this just addresses the problem but maybe a ticket to rework it a little bit so its not as awkward would be a good direction.

**Comment by hultonha** [comment]
> > I would love a test for this sweat_smile but this PR as is looks good! slightly_smiling_face
> 
> would like to rework it so its not soo weird XD. comment and uncomment are different keybinds. would like to have a single keybind that comments/uncomments code. The cursor gets moved to beginning last line regardless of where it was already its kind of jarring that it does that. etc ...
> 
> this just addresses the problem but maybe a ticket to rework it a little bit so its not as awkward would be a good direction.

Understood, sounds like a good plan :+1:

**Comment by hultonha** [comment]
Just kicked off a build

**Comment by amznestebanpapp** [comment]
@pollend this will need a merge to solve conflicts

**Comment by pollend** [comment]
looks  like it was resolved here: https://github.com/o3de/o3de/pull/6210

**Pull request closed without merging**
