### PR TITLE
remove legacy camera from EmotionFX

### PR DESCRIPTION
**Pull request by pollend**
## What does this PR do?

removes the the legacy EmotionFX camera and all the variants. 

ref: https://github.com/o3de/o3de/pull/10296

### CODE REVIEW

**Comment by pollend** [comment]
waiting on the other PR that removes the manipulator to be merged before I open this PR.

**Review by amzn-jillich — APPROVED** [review]

**Review by amzn-rhhong — APPROVED** [review]

**Comment by pollend** [comment]
looks like an unreleated test failed ...

**Comment by amzn-rhhong** [comment]
> looks like an unreleated test failed ...

That does happen time to time recently. I triggered another build.

**Review by moraaar — APPROVED** [review]
Nice clean up!

**Comment by pollend** [comment]
> We seem to get some unrelated test failures here. Can you merge in the latest from development please? After that we can trigger another build and that should solve it.

rebased it back onto develop

**Comment by amzn-jillich** [comment]
Thanks @pollend , just kicked off another build.

**Review by cgalvan — APPROVED** [review]

**Pull request merged**
