### PR TITLE
Fix remain copyright header issues for .in files

### PR DESCRIPTION
**Pull request by spham-amzn**
Signed-off-by: Steve Pham <spham@amazon.com>

### CODE REVIEW

**Review by AMZN-ScottR — APPROVED** [review]

**Comment by amznestebanpapp** [comment]
Can we add the extension to the validator?

**Comment by spham-amzn** [comment]
> 
> 
> Can we add the extension to the validator?

I did add it and tested, but .in is not always a source file. There were a lot of json files that uses .in for templates, and they cannot add headers

**Review by lumberyard-employee-dm — APPROVED** [review]

**Comment by amznestebanpapp** [comment]
> > Can we add the extension to the validator?
> 
> I did add it and tested, but .in is not always a source file. There were a lot of json files that uses .in for templates, and they cannot add headers

Is just json files the problem? we could exclude them with `EXCLUDED_VALIDATION_PATTERNS`

**Comment by spham-amzn** [comment]
> 
> 
> > > Can we add the extension to the validator?
> > 
> > 
> > I did add it and tested, but .in is not always a source file. There were a lot of json files that uses .in for templates, and they cannot add headers
> 
> Is just json files the problem? we could exclude them with `EXCLUDED_VALIDATION_PATTERNS`

The problem is that not all files have json in the name, even though they are json files (See the TestImpactFramework as an example).

**Review by amznestebanpapp — APPROVED** [review]

**Pull request merged**
