### PR TITLE
feat: when right clicking create entity under cursor

### PR DESCRIPTION
**Pull request by pollend**
## What does this PR do?

ref: https://github.com/o3de/o3de/issues/17618

when right clicking create entity under user cursor from the viewport.

## How was this PR tested?

follow steps in linked ticket

### CODE REVIEW

**Comment by pollend** [comment]
PopulateEditorGlobalContextMenu looks like this logic is deprecated?

**Comment by AMZN-daimini** [comment]
> PopulateEditorGlobalContextMenu does not seem to be called anywhere is this logic is deprecated?

It is, it was only used in Slice mode which is being removed in `development`.

**Review by AMZN-daimini — APPROVED** [review]

**Review by nick-l-o3de — APPROVED** [review]

**Comment by pollend** [comment]
I was trying to see if there is an easier to way to approach this?

**Review by AMZN-daimini — APPROVED** [review]

**Comment by AMZN-daimini** [comment]
> I was trying to see if there is an easier to way to approach this?

Looks good to me, maybe the viewport portion could be put into a function if it needs to be reused but it's fine for now.

**Comment by AMZN-daimini** [comment]
I actually have an issue with this implementation - the entity will be created at the cursor position, not at the position where the user right-clicked to trigger the context menu. As such the entity will actually be offset a little bit.

I am implementing a similar feature for prefab instantiation, so I'm thinking of just reusing the same code for both. Will update asap.

**Comment by pollend** [comment]
> I actually have an issue with this implementation - the entity will be created at the cursor position, not at the position where the user right-clicked to trigger the context menu. As such the entity will actually be offset a little bit.
> 
> I am implementing a similar feature for prefab instantiation, so I'm thinking of just reusing the same code for both. Will update asap.

sounds good.

**Comment by AMZN-daimini** [comment]
I have just published the PR that implements this for both entity creation and prefab instantiation.

https://github.com/o3de/o3de/pull/17768

Many thanks for your work, though, since it saved me a lot of time on the viewport detection/raycast generation side of things :)

**Pull request closed without merging**
