### PR TITLE
Update OpenMesh for Windows and prepare for Linux and Mac

### PR DESCRIPTION
**Pull request by spham-amzn**
- Update to OpenMesh-8.1-rev3 for Windows
- Add OpenMesh-8.1-rev3 for Linux but not enabled
- Add OpenMesh-8.1-rev3 for Mac but not enabled

Dependent on https://github.com/o3de/3p-package-source/pull/63 

Signed-off-by: Steve Pham <82231385+spham-amzn@users.noreply.github.com>

### CODE REVIEW

**Review by hultonha — APPROVED** [review]
Change looks good, I think there might be one more thing to add to ensure we actually enable the White Box Gem for Linux (tagging @moraaar who looked at something very similar recently - I believe this was the PR - https://github.com/o3de/o3de/pull/5165). I think we need `set(PAL_TRAIT_WHITEBOX_TESTS_SUPPORTED TRUE)` - but maybe this should be in the PR that's currently open by @pollend.

**Comment by spham-amzn** [comment]
> 
> 
> Change looks good, I think there might be one more thing to add to ensure we actually enable the White Box Gem for Linux (tagging @moraaar who looked at something very similar recently - I believe this was the PR - #5165). I think we need `set(PAL_TRAIT_WHITEBOX_TESTS_SUPPORTED TRUE)` - but maybe this should be in the PR that's currently open by @pollend.

I agree, it should be part of that PR

**Review by moraaar — COMMENTED** [review]
This PR is adding the 3rd party package to linux and mac, but it's missing to turn the TRAIT macro to true for the whitebox gem and its tests under AutomatedTesting:

- Gems\WhiteBox\Code\Source\Platform\Mac\PAL_mac.cmake:
- Gems\WhiteBox\Code\Source\Platform\Linux\PAL_linux.cmake:
set(PAL_TRAIT_WHITEBOX_SUPPORTED TRUE)

- AutomatedTesting\Gem\PythonTests\WhiteBox\Platform\Mac\PAL_mac.cmake:
- AutomatedTesting\Gem\PythonTests\WhiteBox\Platform\Linux\PAL_linux.cmake:
set(PAL_TRAIT_WHITEBOX_TEST_SUPPORTED TRUE)

**Comment by spham-amzn** [comment]
> 
> 
> This PR is adding the 3rd party package to linux and mac, but it's missing to turn the TRAIT macro to true for the whitebox gem and its tests under AutomatedTesting:
> 
>     * Gems\WhiteBox\Code\Source\Platform\Mac\PAL_mac.cmake:
>       set(PAL_TRAIT_WHITEBOX_SUPPORTED TRUE)
> 
>     * Gems\WhiteBox\Code\Source\Platform\Linux\PAL_linux.cmake:
>       set(PAL_TRAIT_WHITEBOX_SUPPORTED TRUE)
> 
>     * AutomatedTesting\Gem\PythonTests\WhiteBox\Platform\Mac\PAL_mac.cmake:
>       set(PAL_TRAIT_WHITEBOX_TEST_SUPPORTED TRUE)
> 
>     * AutomatedTesting\Gem\PythonTests\WhiteBox\Platform\Linux\PAL_linux.cmake:
>       set(PAL_TRAIT_WHITEBOX_TEST_SUPPORTED TRUE)

This is on purpose, the updated OpenMesh libraries were needed to unblock a PR (https://github.com/o3de/o3de/pull/5075 )  from @pollend , as there are several compilation issues that need to be fixed for Linux before they can be enabled.

**Review by moraaar — APPROVED** [review]
Got it! Thanks! Approved.

**Review by pollend — APPROVED** [review]

**Pull request merged**
