### PR TITLE
Change developer preview tag

### PR DESCRIPTION
**Pull request by AMZN-Phil**
Changed [Developer Preview] to [Stable] for Windows installer. This will take effect for all installer builds after this change is merged.

Signed-off-by: AMZN-Phil <pconroy@amazon.com>

### CODE REVIEW

**Comment by AMZN-Phil** [comment]
We would also want to make sure that this change does not get merged back to Development.

**Review by Ulrick28 — APPROVED** [review]

**Comment by AMZN-alexpete** [comment]
Is this something that the Jenkins job can "stamp" in when it makes the installer instead of us modifying the source code - that way we wouldn't have to worry about developers merging it back to dev?

**Comment by amznestebanpapp** [comment]
> We would also want to make sure that this change does not get merged back to Development.

please notify to the deverlopers doing the merges.... this will be merged otherwise

**Comment by amznestebanpapp** [comment]
> Is this something that the Jenkins job can "stamp" in when it makes the installer instead of us modifying the source code - that way we wouldn't have to worry about developers merging it back to dev?

yes, this can be generated by Jenkins+CMake, that file can be configured by CMake (through configure_file) and generated based on the version that jenkins passes. But we need to build all that up, so I think this is an OK short-term fix.

**Review by amznestebanpapp — APPROVED** [review]

**Review by AMZN-alexpete — APPROVED** [review]

**Pull request merged**
