### PR TITLE
chore: simplify logic for handling expanding entries in Outliner (#5219)

### PR DESCRIPTION
**Pull request by pollend**
the `dataChanged` event is driven from the model so the current expand state is also updated from this signal when changing the open state for items in the outliner. removes the extra book keeping of queuing up changes and ensuring they correctly update the tree view.   just need to make sure the dataChange signal is emitted after making a change to the expand state for the model. This should happen when updating the rows already. 

issue: https://github.com/o3de/o3de/issues/5219

Signed-off-by: Michael Pollind <mpollind@gmail.com>

### CODE REVIEW

**Comment by pollend** [comment]
umm not quite the right fix the expand state is not correctly updated so that is why the entries get clipped.

**Comment by pollend** [comment]
https://user-images.githubusercontent.com/854359/140622932-3594d585-06ba-49ef-add0-7b8f43a42f7d.mp4

**Review by lsemp3d — CHANGES_REQUESTED** [review]
Looks good to me, just a couple small change requests, thanks!

**Comment by pollend** [comment]
I haven't looked too deeply but what does invalidating FilterEntity do exactly. I reverted my changes where I replaced the logic `QueueEntityToExpand` with  `onEntityExpand/Collapsed` seems like I changed how this works exactly. was thinking how I could simplify the API a little bit with two method calls instead of a handler + some internal queue method.

**Review by lsemp3d — APPROVED** [review]

**Comment by amznestebanpapp** [comment]
@o3de/sig-content @AMZN-daimini would you mind taking a look to this PR?

**Comment by hultonha** [comment]
Poking @AMZN-daimini again as you're probably the best person to review this PR 🙂

**Comment by monroegm** [comment]
@o3de/sig-content Is anybody willing to take a look at this PR?

**Comment by hultonha** [comment]
Poking @AMZN-daimini about this again 😛 and also letting @cgalvan know it might be worth having a look at?

**Review by AMZN-daimini — APPROVED** [review]
Sorry it took me forever to review this, I had a look at the code and it looked fine a while ago, but really wanted to test this out on the build before giving it my approval.

I have manually tested the changes locally and ran through some edge cases, behavior is exactly what I expect. You have my axe :D

**Comment by hultonha** [comment]
Merged 🎉

**Pull request merged**
