### PR TITLE
When processing PNG files with alpha channel, AP failed to choose the right preset file.

### PR DESCRIPTION
**Pull request by tjmgd**
Signed-off-by: T.J. McGrath-Daly <tj.mcgrath.daly@huawei.com>

### CODE REVIEW

**Review by VickyAtAZ — CHANGES_REQUESTED** [review]
The preset issue should be already resolved without your change. 

If it's not, do you have repro steps of your issue? 

Your change may have problem if GetSuggestedPreset uses the default input 'nullptr' of the image object, then it won't check image content which returns different result.

**Comment by wintermute-motherbrain** [comment]
@thefranke @tjmgd can you check Vicky's comments?

**Comment by cgalvan** [comment]
I can confirm https://github.com/o3de/o3de/pull/6412 fixed the alpha issue with png's, so I'm going to close this PR.

**Comment by Jackie9527** [comment]
The main difference is in [Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/ImageConvert.cpp](https://github.com/o3de/o3de/pull/6504/files#diff-1e94079bd536962c43b7f4c9ef315d7c186c38d669f47e5c6e0acdc536b06998).

Check whether the image can be opened properly in advance. If the image can be created properly, use the created image to avoid repeated operations in subsequent methods.

Add a new parameter `IImageObjectPtr image` to the following methods

* `TextureSettings::GetMultiplatformTextureSetting`
* `TextureSettings::GenerateDefaultMultiplatformTextureSettings`
* `BuilderSettingManager::GetSuggestedPreset`

Lack of the following line should be a mistake, because I fixed the problem based on the old code.
`|| image->GetAlphaContent() == EAlphaContent::eAlphaContent_OnlyWhite`

**Comment by Jackie9527** [comment]
@VickyAtAZ

**Comment by Jackie9527** [comment]
`ImageProcessingAtom::LoadImageFromFile` would return `nullptr` when processing unkown image file, then the following code from `https://github.com/o3de/o3de/blob/development/Gems/Atom/Asset/ImageProcessingAtom/Code/Source/BuilderSettings/BuilderSettingManager.cpp`

```
        if (outPreset == emptyPreset)
        {        
            auto image = IImageObjectPtr(LoadImageFromFile(imageFilePath));// image would be dereferenced as null pointer.
            if (image->GetAlphaContent() == EAlphaContent::eAlphaContent_Absent
                || image->GetAlphaContent() == EAlphaContent::eAlphaContent_OnlyWhite)
        }
```

**Pull request closed without merging**
