### PR TITLE
Disable Component Mode Switcher in Automated Testing project

### LINKED ISSUE #12253: [Linux] ./Atom/tests/hydra_AtomEditorComponents_ReflectionProbeAdded.py fails in undo/redo intermittently
**Describe the bug**
ReflectionProbeAdded test fails about 50% of the time on LInux Ubuntu

**Assets required**
[!Important!] Please provide sample assets needed to reproduce the issue, either as an [attachment](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) or as a link to a public asset in Github.

**Steps to reproduce**
1. build stabilization/2210
2. at the terminal run the following command from the o3de repository workspace folder
`./scripts/ctest/ctest_entrypoint.sh --build-path ./build/linux --suite main --ctest-executable /usr/bin/ctest --config profile --tests-regex "AutomatedTesting::Atom_Main_Null_Render_03" --generate-xml --repeat 10`

**Expected behavior**
this should pass 10/10

**Actual behavior**
seeing this fail in AR builds and on ubuntu 20.04 local build occassionally

**Found in Branch**
commit 0fd1b90dfbb406df878a24592fa44a76983b0632 (origin/stabilization/2210)

**Desktop/Device (please complete the following information):**
 - ec2 g4dn.2xlarge
 - ubuntu 20.04

**Additional context**

### PR DESCRIPTION
**Pull request by hultonha**
## What does this PR do?

Temporarily disables the Component Mode Switcher in the Automated Testing project.

To help resolve #12253 

## How was this PR tested?

Running AR to detect if this resolves the issue above

### CODE REVIEW

**Review by amzn-ahmadkrm — APPROVED** [review]
LGTM

**Review by galibzon — APPROVED** [review]

**Review by mbalfour-amzn — APPROVED** [review]
This works around the problem for one project which unblocks AR, but it will still leave things in a crashing state for Linux customers on other projects. Should this get disabled more globally?

**Review by cgalvan — APPROVED** [review]

**Comment by tonybalandiuk** [comment]
This makes sense to move this PR through. We can add a Known Issue to the release notes  for Linux issue and note the registry change as a workaround.  @chanmosq  FYI on Known Issue

**Comment by hultonha** [comment]
FYI I've added a release note here - https://github.com/o3de/o3de/discussions/12129#discussioncomment-3788539

**Review by lsemp3d — APPROVED** [review]
I approve on behalf of sig-content

**Comment by Kadino** [comment]
As @mbalfour-amzn mentioned, this is a pure workaround to disable encountering the underlying intermittent error. However the underlying fix remains important.

Signed off by SIG-Testing, as this will improve the health of the pipeline.

**Review by chanmosq — APPROVED** [review]

**Comment by chanmosq** [comment]
Approved from sig-docs-community!

**Comment by hultonha** [comment]
Closing in favor of https://github.com/o3de/o3de/pull/12367 which fixes the problem and doesn't just hide it.

Could sig-chairs please review and approve https://github.com/o3de/o3de/pull/12367 instead please. Thank you!

**Pull request closed without merging**
