### PR TITLE
Shortcut keys issue

### PR DESCRIPTION
**Pull request by tjmgd**
Fixed an issue where the default shortcut keys AnimGraph and Character under Edit->Preferences->Keyboard shortcuts->Layouts in the animation editor are repeated.

### CODE REVIEW

**Review by cgalvan — APPROVED** [review]

**Comment by hultonha** [comment]
Added some EMFX folks for visibility and will kick off a build now 👍

**Comment by cgalvan** [comment]
@tjmgd  There are some asset errors in the version of development this branch was created off of, please pull latest development in and re-push

**Comment by tjmgd** [comment]
> 

Can you try again now please. Let me know if the issues persist.

**Comment by cgalvan** [comment]
Thanks a new AR build has been kicked off

**Review by AMZN-daimini — APPROVED** [review]

**Pull request merged**
