### PR TITLE
[development] properly pal-ify Android utilities in AzCore

### PR DESCRIPTION
**Pull request by AMZN-ScottR**
Signed-off-by: AMZN-ScottR <24445312+AMZN-ScottR@users.noreply.github.com>

### CODE REVIEW

**Review by amznestebanpapp — APPROVED** [review]
love it!

**Review by spham-amzn — APPROVED** [review]

**Review by amzn-sj — APPROVED** [review]
It doesn't look like Signature_tests.cpp and shared_ref_tests.cpp are being built/referenced anywhere. Can they be removed? If they're useful and just need to be hooked up later, that's fine.

**Comment by AMZN-ScottR** [comment]
> It doesn't look like Signature_tests.cpp and shared_ref_tests.cpp are being built/referenced anywhere. Can they be removed? If they're useful and just need to be hooked up later, that's fine.

They never got hooked up since they were created prior to AzTest working on Android.  As for usefulness of the tests is hard to say without active development on the JNI utilities.  Would be nice to get them running again though.

**Review by lumberyard-employee-dm — APPROVED** [review]

**Review by bosnichd — APPROVED** [review]
Nice!

**Pull request merged**
