### PR TITLE
Removing actors from reflection cubemap images.

### LINKED ISSUE #14106: Reflection Probes: Remove Actors by Default
Character actors will appear in reflection probes when generated at editor time or runtime. This is undesirable since characters are moving/dynamic objects and their locations in world won't match the static reflection probes. They should be excluded from reflection probes.

image

**Describe the solution you'd like**
Update Actor Component so that actors cull themselves from the reflection probe pass using.

See _MeshFeatureProcessor::SetExcludeFromReflectionCubeMaps_ 

**Describe alternatives you've considered**
If it doesn't affect performance, maybe make this an Actor component flag "Appears In Reflection Probes" instead of hardcoding actors to always be culled? Maybe some cases it's okay, for example big statues which only rarely move, or NPCs that have subtle animations, maybe it's desirable for them to be in reflections?

### PR DESCRIPTION
**Pull request by invertednormal**
## What does this PR do?

This PR updates `AtomActorInstance` so that the meshes it uses aren't reflected in cubemaps (since they are dynamic) . This change also moves `m_excludeFromReflectionCubemaps` from the `ModelDataInstance` to the `MeshHandleDescriptor` so it can be set on `AcquireMesh()`.

Fixes #14106

This change also exposes `SetExcludeFromReflectionCubeMaps()` and `GetExcludeFromReflectionCubeMaps()` to the `MeshComponentBus` (thanks @CyaNinix for the idea)

## How was this PR tested?

Tested in Editor to ensure a generated cubmap no longer shows an actor in the reflection

image

### CODE REVIEW

**Review by amzn-tommy — APPROVED** [review]
Now that this is in the descriptor, you should set this in MeshComponentController.cpp before calling AcquireMesh, and remove the subsequent call to SetExcludeFromReflectionCubeMaps.

Same change should apply to IsAlwaysDynamic, while you're in there.

**Review by AMZN-alexpete — APPROVED** [review]

**Comment by AMZN-alexpete** [comment]
@CyaNinix @CyaSid @CyaMika will this change help exclude actors from your dynamic cubemaps?

**Review by AMZN-Gene — APPROVED** [review]

**Comment by qcouillard** [comment]
Hi @AMZN-alexpete 
Yes, totally, thank you.
We also made something in local to allow that, we have added a Bus method to set this boolean and add it to ActorComponents, with option in Editor component in case.
I think that both will complete each other and @CyaNinix will soon make a PR for it.

**Comment by CyaNinix** [comment]
Here's my PR: https://github.com/o3de/o3de/pull/14119

This allows to selectively exclude actors from cubemap reflections (and could be on by default).

**Review by AMZN-alexpete — APPROVED** [review]

**Comment by invertednormal** [comment]
@CyaNinix I like your additions to the mesh controller bus, that was definitely an oversight when this property was added. Mind if I bring those changes over to this PR?

I'm on the fence about adding the exclude from cubemap option to the actor component - It's hard to think of good use cases for that, and once we add an editor property it becomes very hard to change or remove it later (an upgrade path would need to be provided for the component which is doable, but a pain).

**Pull request merged**
