### PR TITLE
Force Region slice to prefab instantiates test conversion

### PR DESCRIPTION
**Pull request by FuzzyCarterAWS**
Manually converting the ForceRegion_SliceFileInstantiates test to ForceRegion_PrefabFileInstantiates.

First I created an entity with a ForceRegion & Box Collider before turning that into a Prefab. Then I created an entity with a Rigid Body and Sphere Collider and verified that all the starting values were correct.

Afterwards I renamed the ForceRegion_SliceFileInstantiates test file & references to the test to ForceRegion_PrefabFileInstantiates.

I have verified that the test passes 5 times in a row by executing the following command:

`
python\python.cmd -m pytest AutomatedTesting\Gem\PythonTests\Physics\TestSuite_Main.py::TestAutomation::ForceRegion_PrefabFileInstantiates --build-directory <build_dir_path>\bin\profile
`

### CODE REVIEW

**Review by chiyenteng — APPROVED** [review]

**Review by jckand-amzn — APPROVED** [review]
You can likely safely remove the tags.txt file for the new level. I don't believe is consumed by anything.

**Review by greerdv — APPROVED** [review]
LGTM, thanks for converting this!

**Review by Kadino — APPROVED** [review]
Nice and concise!

**Review by chiyenteng — CHANGES_REQUESTED** [review]
Sorry. I forgot to mention that you also need to update ForceRegion_SliceFileInstantiates test in TestSuite_Periodic.py:
```
@revert_physics_config
    def test_ForceRegion_SliceFileInstantiates(self, request, workspace, editor, launcher_platform):
        from .tests.force_region import ForceRegion_SliceFileInstantiates as test_module
        self._run_test(request, workspace, editor, test_module, enable_prefab_system=False)
```

**Review by chiyenteng — APPROVED** [review]
LGTM

**Pull request merged**
