### PR TITLE
Improve separator rendering in Breadcrumbs

### PR DESCRIPTION
**Pull request by MiKom**
SVG rendering in rich text QLabel doesn't use high-quality scaling. That causes the in-line SVG images used as separator to look really bad. Particularly in non-integer desktop scaling.

It seems that there's no way to get nice SVG rendering there without patching Qt. Qt doesn't expose any knobs for it.

Instead, let's use a Unicode character that looks similar. Font smoothing will take care of making it look nice.

Signed-off-by: Miłosz Kosobucki <milosz@kosobucki.pl>

We of course lose the ability to style the separator exactly as we want, but without re-doing how the Breadcrumbs widget is implemented (or patching Qt), we will always have hideous rendering.

## What does this PR do?

Before:
image

After:
image

## How was this PR tested?

Manually.

### CODE REVIEW

**Review by hultonha — APPROVED** [review]
Nice! 😄 Good spot 🙂

**Comment by MiKom** [comment]
@hultonha One question though. After this patch, the only use of the asset ` .\Code\Framework\AzQtComponents\AzQtComponents\Components\img\UI20\Breadcrumb\Next_level_arrow.svg` is gone. So the asset is left just sitting there.

What's the policy for such assets? Should I delete it and remove the reference in the qrc file? I thought about it, but then, If a developer needs it for something else, they won't know such asset exists. We don't have any separate repository for icons that are designed, but not necessarily used and it could be useful to have such "icon gallery".

**Comment by hultonha** [comment]
> @hultonha One question though. After this patch, the only use of the asset ` .\Code\Framework\AzQtComponents\AzQtComponents\Components\img\UI20\Breadcrumb\Next_level_arrow.svg` is gone. So the asset is left just sitting there.
> 
> What's the policy for such assets? Should I delete it and remove the reference in the qrc file? I thought about it, but then, If a developer needs it for something else, they won't know such asset exists. We don't have any separate repository for icons that are designed, but not necessarily used and it could be useful to have such "icon gallery".

Hmm good question @MiKom 🤔 My preference would just be to remove it and references to it if it's no longer used, but we should likely double check with the Editor team (tagging @cgalvan and @AMZN-daimini for visibility) in case we should maybe keep this around in the AzQtComponents preview window perhaps?

**Review by bhanuja-s — APPROVED** [review]
This is a brilliant find!

Thank you, @MiKom, I approve this on behalf of sig-ui-ux.

**Comment by AMZN-daimini** [comment]
> > @hultonha One question though. After this patch, the only use of the asset ` .\Code\Framework\AzQtComponents\AzQtComponents\Components\img\UI20\Breadcrumb\Next_level_arrow.svg` is gone. So the asset is left just sitting there.
> > What's the policy for such assets? Should I delete it and remove the reference in the qrc file? I thought about it, but then, If a developer needs it for something else, they won't know such asset exists. We don't have any separate repository for icons that are designed, but not necessarily used and it could be useful to have such "icon gallery".
> 
> Hmm good question @MiKom 🤔 My preference would just be to remove it and references to it if it's no longer used, but we should likely double check with the Editor team (tagging @cgalvan and @AMZN-daimini for visibility) in case we should maybe keep this around in the AzQtComponents preview window perhaps?

I agree that it can be removed, the gallery will just inherit this change.

**Review by AMZN-daimini — APPROVED** [review]

**Review by cgalvan — APPROVED** [review]

**Comment by cgalvan** [comment]
> > > @hultonha One question though. After this patch, the only use of the asset ` .\Code\Framework\AzQtComponents\AzQtComponents\Components\img\UI20\Breadcrumb\Next_level_arrow.svg` is gone. So the asset is left just sitting there.
> > > What's the policy for such assets? Should I delete it and remove the reference in the qrc file? I thought about it, but then, If a developer needs it for something else, they won't know such asset exists. We don't have any separate repository for icons that are designed, but not necessarily used and it could be useful to have such "icon gallery".
> > 
> > 
> > Hmm good question @MiKom 🤔 My preference would just be to remove it and references to it if it's no longer used, but we should likely double check with the Editor team (tagging @cgalvan and @AMZN-daimini for visibility) in case we should maybe keep this around in the AzQtComponents preview window perhaps?
> 
> I agree that it can be removed, the gallery will just inherit this change.

+1 to removing it, thank you @MiKom !

**Comment by MiKom** [comment]
References to the unused asset were removed.

**Comment by hultonha** [comment]
> References to the unused asset were removed.

Awesome thanks! I'll start a build now 👍

**Comment by cgalvan** [comment]
The build had an unrelated AP failure, so I've kicked off a new one.

**Comment by cgalvan** [comment]
@MiKom I keep getting the same AR error actually even after a clean build, but it doesn't seem to be related to your change (it's complaining about a network asset). I think you got unlucky and based your branch off a commit that had this asset failure.

Can you pull latest `development` into your branch and push when you get a chance?

**Comment by MiKom** [comment]
> Can you pull latest `development` into your branch and push when you get a chance?

Sure. I'll have to do it on Friday though.

**Comment by MiKom** [comment]
@cgalvan I rebased the branch on the latest development. You can kick off the build

**Pull request merged**
