### PR TITLE
Fixes a nightly build and a CMake warning

### PR DESCRIPTION
**Pull request by amznestebanpapp**
- removed timeouts that were the same as the default
- removed a timeout that was over the max allowed one
- made timeouts that are above the max allowed one to be an error (this is the 3rd time someone puts a timeout higher than the allowed one without realizing)
- fixed a warning issue in a nightly build

### CODE REVIEW

**Review by Kadino — APPROVED** [review]
I'm comfortable making the module timeout more strict and difficult to ignore.

**Review by sharmajs-amzn — APPROVED** [review]
Would recommend running the periodic suite on these changes to ensure that tests are not failing, i might suspect AssetBundler tests might timeout.

**Review by lumberyard-employee-dm — APPROVED** [review]

**Comment by amznestebanpapp** [comment]
> Would recommend running the periodic suite on these changes to ensure that tests are not failing, i might suspect AssetBundler tests might timeout.

sure, running

**Comment by amznestebanpapp** [comment]
> > Would recommend running the periodic suite on these changes to ensure that tests are not failing, i might suspect AssetBundler tests might timeout.

timedout, however, there are other 3 that are failing:
```
[2021-08-06T21:06:44.321Z] 	 10 - AssetPipelineTests.AssetBundler.periodic::TEST_RUN (Timeout)
[2021-08-06T21:06:44.321Z] 	 21 - AutomatedTesting::ScriptCanvasTests_Perodic.periodic::TEST_RUN (Failed)
[2021-08-06T21:06:44.321Z] 	 27 - AutomatedTesting::PythonAssetBuilder.periodic::TEST_RUN (Failed)
[2021-08-06T21:06:44.322Z] 	 48 - AutomatedTesting::AWSTests.periodic::TEST_RUN (Failed)
```
I can disable AssetPipelineTests.AssetBundler for the time being, FYI @sharmajs-amzn

**Comment by amznestebanpapp** [comment]
> I can disable AssetPipelineTests.AssetBundler for the time being, FYI @sharmajs-amzn

Disabling the tests, FYI @sharmajs-amzn

**Review by lumberyard-employee-dm — APPROVED** [review]

**Pull request merged**
