### PR TITLE
Update behavior reflection of EMotionFX's MotionEvent to use nullptr …

### PR DESCRIPTION
**Pull request by BytesOfPiDev**
…instead of empty lambdas.

Signed-off-by: Andre Mitchell <andre.mitchell@bytesofpi.com>

### CODE REVIEW

**Review by cgalvan — APPROVED** [review]

**Review by amzn-rhhong — APPROVED** [review]

**Comment by amzn-jillich** [comment]
The Jenkins built failed. @tjmgd can you try merging the latest from development, this doesn't look like it is related to your change? Then we can retry.

**Comment by tjmgd** [comment]
> The Jenkins built failed. @tjmgd can you try merging the latest from development, this doesn't look like it is related to your change? Then we can retry.

Hi @amzn-jillich, I don't think this PR was mine. @BytesOfPiDev I think this message was for you?

**Comment by BytesOfPiDev** [comment]
> > The Jenkins built failed. @tjmgd can you try merging the latest from development, this doesn't look like it is related to your change? Then we can retry.
> 
> Hi @amzn-jillich, I don't think this PR was mine. @BytesOfPiDev I think this message was for you?

Yeah, it's for me. Thank you. @amzn-jillich, I've merged the latest changes.

**Comment by amzn-jillich** [comment]
Sorry @BytesOfPiDev and @tjmgd, we were having a couple of similar PRs and I was copy & pasting the message. Build succeeded and I just merged it.

Thanks for your contribution @BytesOfPiDev.

**Pull request merged**
