### PR TITLE
Enable component mode switcher by default

### PR DESCRIPTION
**Pull request by amzn-ahmadkrm**
Signed-off-by: amzn-ahmadkrm <105638312+amzn-ahmadkrm@users.noreply.github.com>

## What does this PR do?

There is a registry setting that disables the component mode switcher by default to hide it while it was in development, the feature is ready for release so we are "flipping" the switch

## How was this PR tested?

This has been tested via the different PRs raised for this feature:

Initial PR for creating the component mode switcher:
https://github.com/o3de/o3de/pull/10399

Switcher speed improvement + Undo/Redo support:
https://github.com/o3de/o3de/pull/11203

Added support to change into a new component mode instead of ending and restarting:
https://github.com/o3de/o3de/pull/11436

Change Icon color to match UX design:
https://github.com/o3de/o3de/pull/11585

Fix interaction between the switcher and ImGui:
https://github.com/o3de/o3de/pull/11570

### CODE REVIEW

**Review by AMZN-daimini — APPROVED** [review]

**Review by hultonha — APPROVED** [review]

**Comment by hultonha** [comment]
## Exception Tracking

* [ ] 1. Owning SIG requests the exception, by a Sig Representative (Chair/co-chair) adding the PR to the exception requests queue board.
* [ ] 2. Owning SIG comments on the PR explaining impact if this code does not go into stabilization.
* [ ] 3. Unrelated SIG representative (chair/cochair) approves the exception, adding a comment indicating approval and the SIG they represent.
* [ ] 4. UX SIG representative (chair/cochair) approves the exception, adding a comment indicating approval and the SIG they represent.
* [ ] 5. Testing SIG representative (chair/cochair) approves the exception, adding a comment indicating approval and the SIG they represent.
* [ ] (Must occur at some point before SIG-Release approval) Code has been approved for merging by maintainers
* [ ] 6. SIG-Release Release Manager or co-Release Manager approves the exception, adding a comment indicating approval and the SIG they represent.
* [ ] 7. If all approvals are accepted, then the exception PR may be merged
* [ ] 8. Merged PR is verified successful via testing. If Merged PR verification testing failed, consult reps from step 3-5 and discussion occurs on fixing the failure vs backing out change
* [ ] 9. Exception is complete

**Comment by hultonha** [comment]
For attention of @tonybalandiuk (release manager), @monroegm (sig-content chair), @FiniteStateGit (sig-docs chair), @Kadino (sig-testing chair), @yuyihsu (sig-ui-ux chair). Please could you review and approve this when you have a moment. Thank you!

**Comment by hultonha** [comment]
For more info please see the description and linked tickets. Please also refer to this roadmap item - https://github.com/o3de/o3de/issues/10662.

The code is all in stabilization already, just disabled behind a feature flag. This just flips the default switch to on.

The feature itself is a new viewport ui element to allow users to quickly switch between available Component Modes.

**Review by Kadino — APPROVED** [review]
Approved by sig-testing

**Review by lsemp3d — APPROVED** [review]
I approve on behalf of sig-content

**Comment by FiniteStateGit** [comment]
I approve on behalf of SIG-docs-community.

**Review by FiniteStateGit — APPROVED** [review]

**Comment by vincent6767** [comment]
As a co-release manager, I approve the PR
CC: @tonybalandiuk

**Comment by rainbj** [comment]
SIG-UI-UX approved. Please let me know if there is any additional follow-up needed

**Comment by tonybalandiuk** [comment]
This has received all necessary approvals, ok to merge.

**Comment by hultonha** [comment]
So awesome this finally got merged! 🥳 Awesome work @amzn-ahmadkrm 👍

**Comment by FuzzyCarterAWS** [comment]
@hultonha tested this is stabilization, including in Linux with the fix from #12367

**Comment by hultonha** [comment]
> @hultonha tested this is stabilization, including in Linux with the fix from #12367

That's excellent thanks @FuzzyCarterAWS 👍

**Pull request merged**
