### PR TITLE
GetPixel BC1 color data support

### PR DESCRIPTION
**Pull request by mbalfour-amzn**
Added support for BC1 decompression to the GetPixel APIs. Since this was the first block format to get added, the internal APIs needed a bit of refactoring to allow for pairs of indices to get generated - one for the block, and one for the pixel index within the block. This change should also make it relatively easy to add other block formats into these APIs over time if desired.

Demonstration of usage:
image
image

### CODE REVIEW

**Review by cgalvan — APPROVED** [review]

**Review by VickyAtAZ — APPROVED** [review]

**Comment by jeremyong-az** [comment]
Question, at a high level, how is this used, outside of the image preview?

**Comment by mbalfour-amzn** [comment]
> Question, at a high level, how is this used, outside of the image preview?

There are a lot of different ways to answer this question.
* Because we're adding this support to a utility API, there's no way to answer all the ways in which it _might_ get used over time.
* The utility API is _currently_ only used by the Image Gradient component. The Image Gradient component currently uses it on a per-request basis, so as systems request values from the gradient, the pixels get looked up through the API. There's no limitations on the usage of the Image Gradient itself, so it could get hooked to other gradients, used for vegetation, used for terrain height or surface data, etc. Note that even though the Image Gradient can now read in images with a BC1 type, I wouldn't _necessarily_ expect anyone to use that type with gradients, as it's a lossy compression, and I'd expect folks to generally want lossless data for their gradients. However, for things like splat maps, there's a _chance_ that someone might find it useful.
* In my own personal experiments, I was using this from my own components as a way to get color data from terrain macro materials (which by default _are_ BC1-compressed on PC), which I would then turn into falloff gradient masks that I could use for mapping surface data.

**Comment by VickyAtAZ** [comment]
> Question, at a high level, how is this used, outside of the image preview?

The image preview of any compressed formats are already supported by ImagePorcessingAtom.Editor module which is not available for runtime. This function is mainly for runtime cpu decompress support used by Terrian.

**Comment by jeremyong-az** [comment]
> > Question, at a high level, how is this used, outside of the image preview?
> 
> The image preview of any compressed formats are already supported by ImagePorcessingAtom.Editor module which is not available for runtime. This function is mainly for runtime cpu decompress support used by Terrian.

Yea I understand the use case. Probably worth mentioning for posterity that the use case here probably should be GPU driven at some point.

**Comment by mbalfour-amzn** [comment]
> > > Question, at a high level, how is this used, outside of the image preview?
> > 
> > 
> > The image preview of any compressed formats are already supported by ImagePorcessingAtom.Editor module which is not available for runtime. This function is mainly for runtime cpu decompress support used by Terrian.
> 
> Yea I understand the use case. Probably worth mentioning for posterity that the use case here probably should be GPU driven at some point.

Yep 100%. Changing the Gradient system would require a pretty large rewrite, which is why we haven't tackled it yet, but ideally it would have both CPU and GPU versions that could be switched between. That would give us flexibility in situations (like server-side logic) where a GPU may not exist, but max performance when GPUs do exist.

**Pull request merged**
