### PR TITLE
EXCEPTION REQUEST: Adds the ability to generate UVs automatically during mesh import

### PR DESCRIPTION
**Pull request by lawsonamzn**
Note to reviewers, this PR is already in 'development branch' but this is a PR to get it into the Stabilization branch as an Exception.
I will be adding the exception checklist below.  Please see the original PR for a full brief including pictures of the difference it makes.

## ORIGINAL PR from Development
https://github.com/o3de/o3de/pull/15530 - solves https://github.com/o3de/o3de/issues/12795 issue.
Without this PR merged, the robotics stuff in o3de-extras will seem incomplete for the release as all models will appear as featureless gray shadeless objects.

The new modifier is implemented in the same UX as the existing modifiers.
https://user-images.githubusercontent.com/70027408/229643430-e28c85ae-4e56-4be2-872c-619650ca2220.png

This PR is a cherry-pick of that squash submission.

## Original PR text
* Adds the ability to generate UVs automatically during mesh import

This adds a new modifier to the available list of modifiers you can add to a mesh during its import in its import settings.

The new modifier lets you select how to generate UVs for a mesh. Currently, only 1 generator is supported (Spherical Positional projection) but all the hard work here is done to support additional unwrappers in the future by following the pattern.

This ability is crucial for workflows to do with importing robotic meshes as they often lack UVs, and the path to otherwise get something reasonable to render is painful

# Exception Checklist
- [x] 1. Owning SIG requests the exception, by a Sig Representative (Chair/co-chair) adding the PR to the exception requests queue board.
- [x] 2. (SIG-Content) Owning SIG comments on the PR explaining impact if this code does not go into stabilization.
- [x] 3. Unrelated SIG representative (chair/cochair) approves the exception, adding a comment indicating approval and the SIG they represent.
- [x] 4. UX SIG representative (chair/cochair) approves the exception, adding a comment indicating approval and the SIG they represent.
- [x] 5. Testing SIG representative (chair/cochair) approves the exception, adding a comment indicating approval and the SIG they represent.
 (Must occur at some point before SIG-Release approval) Code has been approved for merging by maintainers
- [x] 6. SIG-Release Release Manager or co-Release Manager approves the exception, adding a comment indicating approval and the SIG they represent.
- [ ] 7. If all approvals are accepted, then the exception PR may be merged
- [ ] 8. Merged PR is verified successful via testing. If Merged PR verification testing failed, consult reps from step 3-5 and discussion occurs on fixing the failure vs backing out change
- [ ] 9. Exception is complete

### CODE REVIEW

**Comment by lumberyard-employee-dm** [comment]
I am approving the exception as an unrelated SIG representative from SIG-Core as the need for mesh UV in the robotics models would really help with visually distinguishing the content.

**Comment by lawsonamzn** [comment]
To perform a manual test:
Unzip monkey_with_no_uvs.fbx to any assets folder (for example, AutomatedTesting/Assets)
[monkey_with_no_uvs.zip](https://github.com/o3de/o3de/files/11205083/monkey_with_no_uvs.zip)
view in O3DE editor.  notice it has no rendering and spews warning about missing UV sets.

right click the FBX Asset in asset browser -> "Add Modifier" -> UVs --> Save.  

See how it now works just fine in the viewport and no longer spews warnings.

Note that only things you explicitly add this modifier to are affected in any way, and even adding the modifier will not affect anything that already has UVs.

**Review by gadams3 — APPROVED** [review]

**Comment by gadams3** [comment]
Missed that this was an exception request but I previously reviewed the changes.

**Review by adamdbrw — APPROVED** [review]

**Comment by AMZN-Dk** [comment]
Approving this exception from SIG Testing, reviewed the changes and this looks like an impactful change that we should take.

**Comment by lsemp3d** [comment]
As chair of SIG-Content I approve this request, this improves quality when no UVs are present, it improves workflows & quality when it relates to bringing in assets into O3DE

**Comment by rainbj** [comment]
Spoke with Nicholas and talked about the UX use cases. No concerns at this point about UX pipeline

SIG-UI-UX approved.

**Review by kberg-amzn — APPROVED** [review]
I've read through the change and for the most part it looks really clean. I'll also approve as an unrelated sig representative, however I would really like to see a deeper review done by the asset team, as well as a plan for testing once merged, since this is going in without any associated unit tests and after the new feature cutoff.

**Comment by vincent6767** [comment]
As a SIG Co-chair, I approve this PR.

**Comment by tonybalandiuk** [comment]
Has this been tested post-merge @lawsonamzn ?

**Comment by lawsonamzn** [comment]
Yes, it works the same as it worked before merge.

**Pull request merged**
