### PR TITLE
Linux Pre-Built SDK CMake configure fix

### LINKED ISSUE #8732: SDK Build fails to configure due to missing add_library call for OpenSSL
**Describe the bug**
When configuring a project using from the SDK layout which includes installing the SDK from the Installer, OpenSSL fails to configure.
This is due to the 3rdParty::OpenSSL target not being declared within the SDK layout

**Steps to reproduce**
1. Create an SDK layout using the [Building for Linux](https://www.o3de.org/docs/welcome-guide/setup/setup-from-github/building-linux/#build-the-engine) instructions or install the [Debian package](https://www.o3de.org/download/#linux) for O3DE.
1. Register an O3De project with the installed Pre-built SDK layout
```bash
[user@host <o3de-pre-built-sdk-folder>]$ scripts/o3de.sh register -pp <project-path>
```
1. Change directory to the project path
1. Configure the project using CMake `cmake -B build/linux -S . -G"Ninja Multi-Config"`

**Expected behavior**
CMake configuration completes without error

**Actual behavior**
An O3DE Project fails to configure with the following error
```
CMake Error at /opt/O3DE/0.0.0.0/cmake/LYWrappers.cmake:174 (add_executable):
  Target "TestProject.GameLauncher" links to target "3rdParty::OpenSSL" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  /opt/O3DE/0.0.0.0/LauncherGenerator/launcher_generator.cmake:84 (ly_add_target)
  /opt/O3DE/0.0.0.0/cmake/FindLauncherGenerator.cmake:11 (include)
  /opt/O3DE/0.0.0.0/cmake/Findo3de.cmake:24 (find_package)
  /opt/O3DE/0.0.0.0/CMakeLists.txt:77 (ly_find_o3de_packages)


CMake Error at /opt/O3DE/0.0.0.0/cmake/LYWrappers.cmake:189 (add_library):
  Target "TestProject" links to target "3rdParty::OpenSSL" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  Gem/CMakeLists.txt:43 (ly_add_target)
```

**Assets required**
Provide sample assets needed to reproduce the issue.

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
This issue was caused by PR https://github.com/o3de/o3de/pull/8366

**Desktop/Device (please complete the following information):**
 - OS: Any Linux Distro

**Additional context**
So the issue is that the `find_package(OpenSSL)` and `add_library(3rdParty::OpenSSL)` commands are not run when using an SDK layout because the [OpenSSL_linux.cmake](https://github.com/o3de/o3de/blob/41f68d650796aace5b1b346cd7da969d73f77484/cmake/3rdParty/Platform/Linux/OpenSSL_linux.cmake#L9-L19) is copied over to the SDK layout.

Therefore no OpenSSL target gets created.

The SDK layout logic to copy over Find scripts for O3DE 3rdParty libraries only applies for 3rdParty libraries declared using the [ly_add_external_target_path](
https://github.com/o3de/o3de/blob/development/cmake/Platform/Common/Install_common.cmake#L493-L513) function.

**Solution**
To solve this issue we can add a call to `ly_install` inside of the OpenSSL_linux.cmake to copy itself over to the SDK layout and then add a hook to the Install_common.cmake at this [location](https://github.com/o3de/o3de/blob/development/cmake/Platform/Common/Install_common.cmake#L584) to allow injection of custom cmake scripts that would run when configuring CMake in an SDK layout.

We can then use that to inject an `include` to add the `OpenSSL_linux.cmake` script

First update the OpenSSL_linux.cmake to copy itself over to the SDK layout

[OpenSSL_linux.cmake](https://github.com/o3de/o3de/blob/development/cmake/3rdParty/Platform/Linux/OpenSSL_linux.cmake#L19)
---
```cmake
# include Install.cmake to get access to the ly_install function
include(cmake/Install.cmake)

# Copies over the OpenSSL_linux.cmake to the same location in the SDK layout.
cmake_path(RELATIVE_PATH CMAKE_CURRENT_LIST_DIR BASE_DIRECTORY ${LY_ROOT_FOLDER} OUTPUT_VARIABLE openssl_cmake_rel_directory)
ly_install(FILES "${CMAKE_CURRENT_LIST_FILE}"
    DESTINATION "${openssl_cmake_rel_directory}"
    COMPONENT ${CMAKE_INSTALL_DEFAULT_COMPONENT_NAME}
)
```

Next update the Install_common.cmake script to lookup a new property `O3DE_BUILTIN_PACKAGES_INSTALL_CODE` which will specify additional script logic to inject into the generated BuiltinPackages_linux.cmake file

[Install_common.cmake](https://github.com/o3de/o3de/blob/development/cmake/Platform/Common/Install_common.cmake#L584)
---
```cmake
# Allow the BuiltinPackages_<platform>.cmake script to propagate additional cmake code to be executed in the Install layout configure step
get_property(builtin_packages_inject_code GLOBAL PROPERTY O3DE_BUILTIN_PACKAGES_INSTALL_CODE)
if (builtin_packages_inject_code)
    string(APPEND builtinpackages "${builtin_packages_inject_code}\n")
endif()
```

[BuiltinPackages_linux.cmake](https://github.com/o3de/o3de/blob/development/cmake/3rdParty/Platform/Linux/BuiltInPackages_linux.cmake#L52-L53)
---
```cmake
set_property(GLOBAL APPEND PROPERTY O3DE_BUILTIN_PACKAGES_INSTALL_CODE [[
# Use system default OpenSSL library instead of maintaining an O3DE version for Linux
include(${CMAKE_CURRENT_LIST_DIR}/OpenSSL_linux.cmake)
]])
```

### PR DESCRIPTION
**Pull request by lumberyard-employee-dm**
The Pre-built SDK for Linux would fail to configure due to not including the `OpenSSL_linux.cmake` script.

The `OpenSSL_linux.cmake` script is included by the `BuiltInPackages_linux.cmake` script in the source engine build, but not in the SDK build because the `BuiltInPakcages_linux.cmake` file is [generated](https://github.com/o3de/o3de/blob/development/cmake/Platform/Common/Install_common.cmake#L585) in the when the install layout is created.

Updated the Clang compiler detection on Linux to check for a plain `clang` and `clang++` if `clang-<version>` executable isn't found.

fixes #8732

### CODE REVIEW

**Review by junbo75 — APPROVED** [review]

**Review by amzn-phist — APPROVED** [review]
LGTM

**Comment by lumberyard-employee-dm** [comment]
> I am getting clang detection issues (again or still?) on Arch. If this was fixed, there has been a regression as of 4/20 nightly build.
> 
> ```
> $ ls /usr/bin/clang*
> /usr/bin/clang
> /usr/bin/clang++
> /usr/bin/clang-13
> ```
> 
> New projects cannot be created with "Clang not found" error. After making a symlink at `/usr/bin/clang++-13` things work as expected.

@xaque 
Does the nightly have this version of the [CompilerSettings_linux.cmake](https://github.com/aws-lumberyard-dev/o3de/blob/82f571ce2c99a913c9648353ecb29c2e07fe954c/cmake/Platform/Linux/CompilerSettings_linux.cmake#L44) in it's package?

Because it delegates to detecting clang by looking for the executable of `clang` underneath the directories of
```
/bin
/usr/bin
/usr/local/bin
/sbin
/usr/sbin
/usr/local/sbin
```

Are you using an existing project?
Because for new projects, we have updated the [DefaultProject/MinimalProject](https://github.com/o3de/o3de/pull/8764/files#diff-05e731db2ed1a7a5bc26a6eb145b449bdbf567705c892a643a0c9cc76e1ca9ff) templates to delegate to the engine's CompilerSettings_linux.cmake which has received the clang detection updates.

For existing projects, they use a copy of the CompilerSettings_linux.cmake that was part of the old DefaultProject template and would therefore not have the newer linux clang detection code.

**Comment by xaque** [comment]
```
$ wget https://raw.githubusercontent.com/aws-lumberyard-dev/o3de/82f571ce2c99a913c9648353ecb29c2e07fe954c/cmake/Platform/Linux/CompilerSettings_linux.cmake
$ diff /opt/O3DE/0.0.0.0/cmake/Platform/Linux/CompilerSettings_linux.cmake CompilerSettings_linux.cmake
```
No differences with that file.

I am seeing this occur on creating new projects, either Default or Minimal template. I just tested it out again with a fully clean install (deleted /opt/O3DE/0.0.0.0, ~/.o3de, ~/O3DE just to be sure), and it is occurring on the latest builds for development and stabilization branches.

**Comment by lumberyard-employee-dm** [comment]
> ```
> $ wget https://raw.githubusercontent.com/aws-lumberyard-dev/o3de/82f571ce2c99a913c9648353ecb29c2e07fe954c/cmake/Platform/Linux/CompilerSettings_linux.cmake
> $ diff /opt/O3DE/0.0.0.0/cmake/Platform/Linux/CompilerSettings_linux.cmake CompilerSettings_linux.cmake
> ```
> 
> No differences with that file.
> 
> I am seeing this occur on creating new projects, either Default or Minimal template. I just tested it out again with a fully clean install (deleted /opt/O3DE/0.0.0.0, ~/.o3de, ~/O3DE just to be sure), and it is occurring on the latest builds for development and stabilization branches.

It looks like the Project Manager code has not been updated to detect clang without the version suffix(i.e `clang-<version>`)

**Pull request merged**
