### PR TITLE
Replace EBUS_EVENT style macros in LyShine

### PR DESCRIPTION
**Pull request by greerdv**
## What does this PR do?
Replaces EBUS_EVENT style macros with non-macro equivalents in LyShine gem. All but 4 of the replacements were done using the following find and replace regexes:

```
EBUS_EVENT_RESULT\((.*), (.*Bus), (.*)\)
$2::BroadcastResult($1, &$2::Events::$3)

EBUS_EVENT_ID_RESULT\((.*), (.*), (.*Bus), (.*)\)
$3::EventResult($1, $2, &$3::Events::$4)

EBUS_EVENT_ID\((.*), (.*Bus), (.*)\)
$2::Event($1, &$2::Events::$3)

EBUS_EVENT\((.*Bus), (.*)\)
$1::Broadcast(&$1::Events::$2)

EBUS_QUEUE_EVENT_ID\((.*), (.*Bus), (.*)\)
$2::QueueEvent($1, $2::Events::$3)
```

## How was this PR tested?
Ran LyShine tests and editor tests.

### CODE REVIEW

**Review by hultonha — COMMENTED** [review]
LGTM but would be great to have @michabr sign-off on these changes (it'd also be cool to start running this across more folders/gems to gradually remove the use of the old EBUS macros. Thanks for sharing the regex you used, super helpful! 🙂

**Comment by greerdv** [comment]
> LGTM but would be great to have @michabr sign-off on these changes (it'd also be cool to start running this across more folders/gems to gradually remove the use of the old EBUS macros. Thanks for sharing the regex you used, super helpful! 🙂

Yeah, that's the plan, hoping to eradicate the macros altogether eventually, but didn't want to put too much in one change and LyShine was where about 2/3 of the macros were.

**Comment by hultonha** [comment]
> > LGTM but would be great to have @michabr sign-off on these changes (it'd also be cool to start running this across more folders/gems to gradually remove the use of the old EBUS macros. Thanks for sharing the regex you used, super helpful! 🙂
> 
> Yeah, that's the plan, hoping to eradicate the macros altogether eventually, but didn't want to put too much in one change and LyShine was where about 2/3 of the macros were.

Fantastic, yes 100%, much nice to do in stages and have easier to digest PRs 😅 Thanks!

**Review by gadams3 — APPROVED** [review]

**Review by michabr — APPROVED** [review]
Thanks!!

**Pull request merged**
