### PR TITLE
Terminate AssetProcessor when spawned by the parent project process

### PR DESCRIPTION
**Pull request by jeremyong-az**
When the Asset Processor is launched via `LaunchAssetProcessor` from a parent project, this change will terminate it when the parent process terminates.

### CODE REVIEW

**Comment by jeremyong-az** [comment]
Per discussion, I will add a setting for this, and default this behavior to off

**Comment by AMZN-stankowi** [comment]
We had a discussion elsewhere on this, but I'm bringing my notes over here to keep them close to the pull request for the change.

- I would like to see this toggled via a parameter, and off by default before it goes in. 
- Ideally it would also have some automated tests, but we can potentially create a ticket and backfill those tests later. My team can work with you to figure out the best way forward there.

**Comment by amznestebanpapp** [comment]
I like this solution, I disagree it should be off by default. If a developer opens the AP in isolation, it wont close, it will remain open. So, if you want to leave the AP open and iterate on the Editor, you just open the AP externally. This only closes the AP if it was the Editor the one that opened it. 

This is the same behavior I would expect from every application, if an application opens a process, it should close it on exit. If not, what the application is opening is more of a "service" (daemon).

**Comment by amznestebanpapp** [comment]
This PR needs to also consider Linux/macOS. If you dont want to do it as part of this PR, we need to create issues for it so we keep track of it (otherwise we end up with different behavior across platforms).

**Review by amznestebanpapp — CHANGES_REQUESTED** [review]
Needs to also consider Linux/macOS. If you dont want to do it as part of this PR, we need to create issues for it so we keep track of it (otherwise we end up with different behavior across platforms).

**Comment by jeremyong-az** [comment]
I'm leaving this off as the default mainly to allow tests to be added downstream and also to maintain workflows where binaries are distributed (as opposed to developers launching in Visual Studio).

@amznestebanpapp Can you help me make issues needed to track the Linux/Mac changes needed? I did not see a Linux/Mac version of `LaunchAssetProcessor` I could modify but more importantly, don't have access to a Linux machine at the moment to test it.

**Comment by amznestebanpapp** [comment]
> I'm leaving this off as the default mainly to allow tests to be added downstream and also to maintain workflows where binaries are distributed (as opposed to developers launching in Visual Studio).
> 
> @amznestebanpapp Can you help me make issues needed to track the Linux/Mac changes needed? I did not see a Linux/Mac version of `LaunchAssetProcessor` I could modify but more importantly, don't have access to a Linux machine at the moment to test it.

Sure, `Code\Framework\AzFramework\Platform\Linux\AzFramework\Asset\AssetSystemComponentHelper_Linux.cpp` is where it happens for Linux
and `Code\Framework\AzFramework\Platform\Mac\AzFramework\Asset\AssetSystemComponentHelper_Mac.cpp` is where it happens for Mac

Since you will need a Mac to test and for Linux the Editor is still not ready to launch, I will create two different github issues.

**Review by amznestebanpapp — APPROVED** [review]

**Comment by jeremyong-az** [comment]
Thanks! I actually have a Macbook but it's just not setup for development just yet so I should be able to do that when I get some spare cycles

**Review by amzn-jillich — APPROVED** [review]
Thanks for jumping onto this!

If we keep it disabled by default, can we encourage our team and anyone from the community who wants to join to enable it for some days to give it some test run and create a follow-up task to actually enable it? If we don't enable it by default, users will have to run into the issue, dive into and deal with it before finding out about a setting that they have to enable - this should just be the default behavior, once we know it is working well. Do you agree?

**Comment by jeremyong-az** [comment]
> Thanks for jumping onto this!
> 
> If we keep it disabled by default, can we encourage our team and anyone from the community who wants to join to enable it for some days to give it some test run and create a follow-up task to actually enable it? If we don't enable it by default, users will have to run into the issue, dive into and deal with it before finding out about a setting that they have to enable - this should just be the default behavior, once we know it is working well. Do you agree?

I believe this should be the default during development, and likely not the default for a shipped binary. I see a few ways of doing this.

1. Option one is a "hacky" solution, we simply use something like `IsDebuggerPresent` to detect if we're launching under a Visual Studio context, at which point we enable the lifetime tether.
2. Option two is to enable it by default and with _the shipping build_ (compiled sdks, installers, etc.) we set the cvar in the engine setreg file.

I'd prefer option two, maybe @amznestebanpapp or someone from the build team can chime in on how to achieve that.

**Review by AMZN-stankowi — APPROVED** [review]

**Comment by amznestebanpapp** [comment]
> > Thanks for jumping onto this!
> > If we keep it disabled by default, can we encourage our team and anyone from the community who wants to join to enable it for some days to give it some test run and create a follow-up task to actually enable it? If we don't enable it by default, users will have to run into the issue, dive into and deal with it before finding out about a setting that they have to enable - this should just be the default behavior, once we know it is working well. Do you agree?
> 
> I believe this should be the default during development, and likely not the default for a shipped binary. I see a few ways of doing this.
> 
> 1. Option one is a "hacky" solution, we simply use something like `IsDebuggerPresent` to detect if we're launching under a Visual Studio context, at which point we enable the lifetime tether.
> 2. Option two is to enable it by default and with _the shipping build_ (compiled sdks, installers, etc.) we set the cvar in the engine setreg file.
> 
> I'd prefer option two, maybe @amznestebanpapp or someone from the build team can chime in on how to achieve that.

Option 1 would be my preference. However, I still feel having this enabled would better match expectations, even in a non-development environment.
IMO, any process that spawns another process should terminate the spawned process when the parent process finishes. I see this as a "lifetime" definition. If the user opens the process, then the user has to close it. If a process opens the process, the process has to close it. Having a "I open it for you, but you have to close it" doesn't feel proper to me. 
The times I have seen other apps doing this, I get annoyed. I think this is valid is if the spawned process is a daemon. In that scenario, I understand the spawned process is a daemon/service so it has a defined lifecycle.

For Option 2, it cannot be through different compilation. There is no difference in compilation in the install process. To generate the compiled SDK, we build e.g. profile and then there is a set of cmake scripts that copy artifacts from the profile output to the install folder. There are some generated scripts, but compilation stays the same.
There is a way to create a different compilation, basically, we would have to create a cache variable and always invoke install with that cache variable in a certain value. However, this creates another problem... now we have a different behavior between what a developer builds and what the SDK produces, which can introduce bugs and create problems to debug (e.g. developers may not know that they have to change that cache variable to reproduce an issue where the AP is closed together with the Editor). Keeping what the developer debugs the same across scenarios reduces the window for errors and makes it easier to debug.

**Comment by AMZN-stankowi** [comment]
> Option 1 would be my preference. However, I still feel having this enabled would better match expectations, even in a non-development environment.
IMO, any process that spawns another process should terminate the spawned process when the parent process finishes. I see this as a "lifetime" definition. If the user opens the process, then the user has to close it. If a process opens the process, the process has to close it. Having a "I open it for you, but you have to close it" doesn't feel proper to me.
The times I have seen other apps doing this, I get annoyed. I think this is valid is if the spawned process is a daemon. In that scenario, I understand the spawned process is a daemon/service so it has a defined lifecycle.
Maybe we should get some community opinions about this? put it under a vote?

In the past, we've avoided this because Asset Processor startup time can be long for projects with a lot of content. There are also cases where a user needs to shut down and re-launch the Editor, and may have launched Asset Processor originally via launching the editor. It's also useful to have content up and running and ready to go, so if a content creator is actively working in a DCC tool, doesn't have the Editor currently open but does have Asset Processor open, their assets are processed as they work.

The gotcha to this is it's common for content creators to launch Asset Processor by launching the editor. If we were able to adjust that habit and get people to launch Asset Processor first, separately, then it wouldn't be that big of a deal to tear down the Asset Processor when the Editor shuts down.

**Comment by amznestebanpapp** [comment]
> In the past, we've avoided this because Asset Processor startup time can be long for projects with a lot of content. There are also cases where a user needs to shut down and re-launch the Editor, and may have launched Asset Processor originally via launching the editor. It's also useful to have content up and running and ready to go, so if a content creator is actively working in a DCC tool, doesn't have the Editor currently open but does have Asset Processor open, their assets are processed as they work.
> 
> The gotcha to this is it's common for content creators to launch Asset Processor by launching the editor. If we were able to adjust that habit and get people to launch Asset Processor first, separately, then it wouldn't be that big of a deal to tear down the Asset Processor when the Editor shuts down.

It will also motivate us to make AP startup faster ;)
I would like to understand why someone needs to re-launch the Editor, that sounds like a workflow issue. IMO, the scenarios where the Editor needs to be relaunched are the same where the AP needs to be relaunched (enabled gems changed, recompilation, etc).
If someone is working on DCC and wants their assets processed, I would expect they open the AP. Sounds like someone may be opening the Editor, then closing it, just to have the AP open, is that the case? 
Two missing things I see is that the project manager doesnt have an option to open the AP. The installer adds an icon to the Editor but not to the AP. Those two things are easily fixed.

**Comment by AMZN-stankowi** [comment]
> It will also motivate us to make AP startup faster ;)
I would like to understand why someone needs to re-launch the Editor, that sounds like a workflow issue. IMO, the scenarios where the Editor needs to be relaunched are the same where the AP needs to be relaunched (enabled gems changed, recompilation, etc).
If someone is working on DCC and wants their assets processed, I would expect they open the AP. Sounds like someone may be opening the Editor, then closing it, just to have the AP open, is that the case?
Two missing things I see is that the project manager doesnt have an option to open the AP. The installer adds an icon to the Editor but not to the AP. Those two things are easily fixed.

On AP startup: Yeah, it's something we've put a lot of time into in the past, but it's creeping up again. We need to find some time to address that.

On Editor relaunches: It's mostly workflow issues that can eventually be resolved other ways, but it still comes up relatively often. The current one is the temporary lack of hot reloading for a few asset types, like meshes. We need to relaunch the Editor whenever we change a mesh, so skipping on AP startup time while iterating on an FBX file is helpful there. In the past it's been other temporary issues. If you know the flow of these tools you can purposely launch AP first, then the Editor, and not run into that with this change, but if you're just getting AP up and running by launching Editor, it won't help.

If the project manager becomes the tool that content creators start to use to get into O3DE tools, then you're right, this can be handled there. We've had other teams build their own front end tools so they can have content creators pull pre-built binaries from an internal server instead of needing to build locally themselves, and use that same tool to launch relevant binaries. I don't know if the plans for the project manager includes that or not.

**Comment by jeremyong-az** [comment]
Fair bit to unpack here:

1. I agree that fundamentally, asset processor should ideally have a fast start, but maybe this is difficult because of e.g. the number of dlls loaded and the presence of a virus scanner that hooks into each one, etc.
2. Most users initially will not have a lot of content, _or_ will be going through the developer workflow.
3. If we change the default behavior this would be a breaking change

Points 1 and 2 suggest we should change the default, and point 3 suggests we shouldn't. There is also a middle ground where we leave this PR as is to address an existing workflow issue (suboptimally), and later add a dialog on launch that checks for the presence of a `Registry/ap_lifetime.setreg` file. If the file doesn't exist, and if the user didn't change the default, we prompt if the user would like to close the AP when the editor closes, and if so, we create a file to change the default. Eventually, if the AP start time improves and asset management to accelerate editor launch is improved, we can remove the dialog.

**Comment by jeremyong-az** [comment]
(last force push was a rebase)

**Comment by amznestebanpapp** [comment]
> If the project manager becomes the tool that content creators start to use to get into O3DE tools, then you're right, this can be handled there. We've had other teams build their own front end tools so they can have content creators pull pre-built binaries from an internal server instead of needing to build locally themselves, and use that same tool to launch relevant binaries. I don't know if the plans for the project manager includes that or not.

Yes, the project manager will become the entry-point GUI for any project-centric workflow. The installer produces two shortcuts: "O3DE Editor" and "O3DE Project Manager". The "O3DE Editor" is unusable until you create the first project and register it as the default (without that it will just open the ProjectManager). I would argue we should just have the Project Manager and have them go through there. If they want, they can create shortcuts that open the Editor directly for a project (and do the same for an AP), maybe the Project Manager can also do that (create the shortcuts).
There wont be a need to create a tool to pull pre-built binaries because that is what the installer does. Eventually, the installer/project manager will have an option to update. Studios/contributors can create their own installers so they can tweak their studio to pull their updates.

**Comment by amznestebanpapp** [comment]
> Points 1 and 2 suggest we should change the default, and point 3 suggests we shouldn't. There is also a middle ground where we leave this PR as is to address an existing workflow issue (suboptimally), and later add a dialog on launch that checks for the presence of a `Registry/ap_lifetime.setreg` file. If the file doesn't exist, and if the user didn't change the default, we prompt if the user would like to close the AP when the editor closes, and if so, we create a file to change the default. Eventually, if the AP start time improves and asset management to accelerate editor launch is improved, we can remove the dialog.

I am fine to merge this as is and create another issue/discussion around the behavior. I feel we need more people involved in the decision since is really up to expectations and how people prefer to work.
If most votes go to keep the AP open after the Editor closes, I will "disagree and commit" :)

**Comment by jeremyong-az** [comment]
> I am fine to merge this as is and create another issue/discussion around the behavior. I feel we need more people involved in the decision since is really up to expectations and how people prefer to work.
> If most votes go to keep the AP open after the Editor closes, I will "disagree and commit" :)

Haha indeed, this is a "two way decision" after all :) Can you help me with this merge? I don't have permissions needed

**Pull request merged**
