### PR TITLE
Automation to add a exception checklist for stabilization PRs

### PR DESCRIPTION
**Pull request by amzn-changml**
## What does this PR do?

As per https://github.com/o3de/sig-build/issues/96, this adds a automation that will comment on any PR targeting a stabilization branch with the exception checklist found in the sig-release process file: https://github.com/o3de/sig-release/blob/main/releases/Process/O3DE%20Exception%20Checklist.md

## How was this PR tested?

Tested in a personal fork. An example of the comment can be found here: https://github.com/amzn-changml/o3de/pull/14

### CODE REVIEW

**Review by brianherrera — APPROVED** [review]

**Review by cgalvan — APPROVED** [review]

**Review by lumberyard-employee-dm — APPROVED** [review]
I am assuming the Merge button would be grayed out until the entire checklist is checked, such as in your test PR?

**Comment by amzn-changml** [comment]
> I am assuming the Merge button would be grayed out until the entire checklist is checked, such as in your test PR?

I think its due to lack of permissions in my fork. It is currently not blocking merges, only to serve as a reminder

**Comment by tonybalandiuk** [comment]
Looks good. Thank you very much @amzn-changml  . This is an important step in improving stabilization code submissions.

**Review by tonybalandiuk — APPROVED** [review]
Looks good.

**Comment by vincent6767** [comment]
Looks good to me. Thanks! I have a few question thar I'll bring up in the GitHub issue instead

**Pull request merged**
