### PR TITLE
Requesting material canvas and material editor merge from development to stabilization

### PR DESCRIPTION
**Pull request by gadams3**
## What does this PR do?

This PR covers a series of features and fixes for material editor, material canvas, and shader management console, that were not able to be reviewed or pass AR before stabilization was cut.

Some of the bug fixes need to be merged regardless.

Some changes affect all of the tools mentioned above, like a crash fix executing scripts, another viewport crash pics if the edit remote feature processor is enabled, improved default layouts, and support for saving custom layouts.

For material canvas specifically, there is a new icon to differentiate it from material editor, easier to understand generated variable names and display names in the inspector, the ability to create and edit node and shader configurations from within material canvas, and combined example PBR and example PBR 2 into one material template called experimental PBR.

Getting these changes merged will make it easier to focus on fixes in stabilization that can be easily merged back. Material canvas is still in an experimental state but accessible hand launchable from the main editor. These changes address some early feedback and make it much more presentable. All of the tools mentioned currently run as separate processes. Therefore, most of the changes will have no impact on the stability of the main editor.

Changes merged in this PR.
https://github.com/o3de/o3de/pull/11607
https://github.com/o3de/o3de/pull/11665
https://github.com/o3de/o3de/pull/11676
https://github.com/o3de/o3de/pull/11716
https://github.com/o3de/o3de/pull/11593

## How was this PR tested?

Built, launched, manually tested all tools and compare changes against development branch

### CODE REVIEW

**Review by cgalvan — APPROVED** [review]

**Review by lsemp3d — APPROVED** [review]
I approve on behalf of SIG-Content

**Review by bhanuja-s — APPROVED** [review]
I approve on behalf of sig-ui-ux.

**Comment by galibzon** [comment]
- What is the impact if this PR is not merged into `stabilization/2210`?
Material canvas has been exposed and it is accessible through the main editor now. It is currently using the same icon as material editors and will confuse users. The PR contains a mix of bug fixes, crash fixes, and improvements affecting multiple tools using the same code base: material editor, material canvas, shader management console. It will be far simpler to fix any bugs affecting these tools in the stabilization branch once these changes are merged versus attempting to fix them in two different branches with divergent code and data, potentially leading to other issues merging those changes back to development from stabilization.

**Review by Kadino — APPROVED** [review]
I think this is fine merging to Stabilization. If it destabilizes the branch, it shouldn't be too hard to revert the change.

Notable that there are no unit tests added, which I would expect for AtomToolsAnyDocument. However it is up to @o3de/sig-graphics-audio to decide where to invest in their automated tests.

**Comment by tonybalandiuk** [comment]
I approve on behalf of sig-release. Please proceed to merge @gadams3 

- [X] @galibzon 1. Owning SIG requests the exception, by a Sig Representative (Chair/co-chair) adding the PR to the exception requests queue board.
- [X] @galibzon 2. Owning SIG comments on the PR explaining impact if this code does not go into stabilization.
- [X] @lsemp3d 3. Unrelated SIG representative (chair/cochair) approves the exception, adding a comment indicating approval and the SIG they represent.
- [X]@bhanuja-s 4. UX SIG representative (chair/cochair) approves the exception, adding a comment indicating approval and the SIG they represent.
- [X] @Kadino  5. Testing SIG representative (chair/cochair) approves the exception, adding a comment indicating approval and the SIG they represent.
- [X]  @tonybalandiuk  6. SIG-Release Release Manager or co-Release Manager approves the exception, adding a comment indicating approval and the SIG they represent.
- [ ] 7. If all approvals are accepted, then the exception PR may be merged
- [ ] 8. Merged PR is verified successful via testing. If Merged PR verification testing failed, consult reps from step 3-5 and discussion occurs on fixing the failure vs backing out change
- [ ] 9. Exception is complete

**Pull request merged**
