### PR TITLE
Remove virtual keyword in AssetEditorMainWindow

### PR DESCRIPTION
**Pull request by BytesOfPiDev**
SetupUI() is called in the AssetEditorMainWindow constructor.

It should not be virtual because derived classes will not receive the call. No other code in O3DE overrides this function.

Signed-off-by: Andre Mitchell <andre.mitchell@bytesofpi.com>

### CODE REVIEW

**Comment by amznestebanpapp** [comment]
@BytesOfPiDev the change is having issues to pass in build automation, looks like is not related to the change, I kicked another run, hopefully this one passes

**Comment by lumberyard-employee-dm** [comment]
@BytesOfPiDev It looks like the change failed to build again.
Can you try to pull the latest o3de:development into this branch?

**Comment by BytesOfPiDev** [comment]
> 
> 
> @BytesOfPiDev It looks like the change failed to build again. Can you try to pull the latest o3de:development into this branch?

Yeah, done.

**Comment by lumberyard-employee-dm** [comment]
I'll kick off a build now.

**Comment by amznestebanpapp** [comment]
> @BytesOfPiDev It looks like the change failed to build again. Can you try to pull the latest o3de:development into this branch?

PRs merge against the target branch when validating. If there is a conflict they fail to build at the beginning.
This one is hitting so many flaky tests... I am going to run a clean workspace.

**Pull request merged**
