### PR TITLE
Move reflection probe feature processor file

### PR DESCRIPTION
**Pull request by Bindless-Chicken**
This PR moves the reflection probe feature processor file out of the public include folder next to its implementation and add some reflection probe files that were missing in the cmake file list.

### CODE REVIEW

**Comment by cgalvan** [comment]
Change looks OK to me, but I'd like graphics to take a look

**Comment by rgba16f** [comment]
Jenkins AR build started.
https://jenkins.build.o3de.org/job/O3DE/view/change-requests/job/PR-7189/

**Comment by rgba16f** [comment]
I discussed on discord with @Bindless-Chicken, there needs to be a 2nd PR to update the reference to the moved file in o3de-atom-sampleviewer.

**Review by rgba16f — APPROVED** [review]

**Review by hultonha — APPROVED** [review]
LGTM :+1:

**Comment by hultonha** [comment]
@rgba16f This can be merged now but want to make sure it doesn't break atom-sampleviewer, can you confirm when this is safe to merge. Thanks!

**Comment by rgba16f** [comment]
@hultonha Bindless-Chicken has a parallel PR up for the AtomSampleViewer change - https://github.com/o3de/o3de-atom-sampleviewer/pull/327

**Comment by hultonha** [comment]
> @hultonha Bindless-Chicken has a parallel PR up for the AtomSampleViewer change - [o3de/o3de-atom-sampleviewer#327](https://github.com/o3de/o3de-atom-sampleviewer/pull/327)

Awesome! I've just approved that one, so they can both be merged together now :+1:

**Comment by AMZN-alexpete** [comment]
This was an API breaking change that the PopcornFX gem is using https://github.com/PopcornFX/O3DEPopcornFXPlugin/blob/development/Code/Source/Integration/Render/AtomIntegration/PopcornFXFeatureProcessor.cpp#L17 If we really don't want this header in the public includes, we should use a deprecation strategy and include the reason for the API change in the PR.

**Pull request merged**
