### PR TITLE
Updated physx4 packaged to rev6 to include linux monolithic gixes

### PR DESCRIPTION
**Pull request by AMZN-Olex**
## What does this PR do?

Updated the package use of Physx4 on Linux.

## How was this PR tested?

Locally from the packaged and running the test in jenkins after pushing the package to dev package source (not the public!).

### CODE REVIEW

**Comment by lumberyard-employee-dm** [comment]
> Updated physx4 packaged to rev6 to include linux monolithic gixes

Yes, all the monolithic "gixes".

**Review by lumberyard-employee-dm — APPROVED** [review]

**Review by nick-l-o3de — APPROVED** [review]
Byut much to review here, looks standard

**Review by spham-amzn — COMMENTED** [review]
BuildInPackages_linux_aarch64.cmake is going to need some love too

**Comment by AMZN-Olex** [comment]
> BuildInPackages_linux_aarch64.cmake is going to need some love too

Yep and then PhysX5 packages. @spham-amzn

**Review by lumberyard-employee-dm — APPROVED** [review]

**Pull request merged**
