### PR TITLE
optimization ReverseUpAndDown function

### PR DESCRIPTION
**Pull request by godpiao**
change CImageEx:: ReverseUpDown function to avoid new uint32(width*height).

### CODE REVIEW

**Review by amznestebanpapp — APPROVED** [review]

**Review by lumberyard-employee-dm — APPROVED** [review]

**Review by hultonha — APPROVED** [review]
LGTM 👍

**Comment by hultonha** [comment]
@godpiao I think you need to mere latest dev into your branch for the AR run to succeed, other than that it should be good to do :+1:

**Comment by godpiao** [comment]
> @godpiao I think you need to mere latest dev into your branch for the AR run to succeed, other than that it should be good to do 👍

yes， I rebase the newest, what dose the "Some checks haven’t completed yet" mean?

**Comment by lumberyard-employee-dm** [comment]
> > @godpiao I think you need to mere latest dev into your branch for the AR run to succeed, other than that it should be good to do 👍
> 
> yes， I rebase the newest, what dose the "Some checks haven’t completed yet" mean?

There are two checks that github performs for PRs in the O3DE repo.
The first is to make sure that commits have DCO signoff on them.
The second is to make sure the change has made it through AR: https://jenkins.build.o3de.org/job/O3DE/view/change-requests/job/PR-5972/

**Pull request merged**
