### PR TITLE
feat: remove GetReferenceCoordSys

### PR DESCRIPTION
**Pull request by pollend**
## What does this PR do?
 
doesn't seem like SetReferenceCoordSys is ever called, something seems wrong with how this works with the viewport? wonder if something was broken or is this logic unused?

### CODE REVIEW

**Comment by guillaume-haerinck** [comment]
It used to be to construct the snap grid and get mouse to gizmo movement so yeah very likely replaced by o3de alternative

**Comment by pollend** [comment]
> It used to be to construct the snap grid and get mouse to gizmo movement so yeah very likely replaced by o3de alternative

you're right i can easily drop all this code.

**Review by gadams3 — APPROVED** [review]

**Review by nick-l-o3de — APPROVED** [review]

**Comment by nick-l-o3de** [comment]
The test that was causing this to fail has been fixed, please rebase on latest, and try again.

**Comment by nick-l-o3de** [comment]
Oof.  Sorry for the conflict here - I pushed a different PR by yourself and it looks like it conflicts with this PR from yourself @pollend

**Pull request merged**
