### PR TITLE
Fixed crash when typing asset name and clicking browse

### PR DESCRIPTION
**Pull request by AMZN-AlexOteiza**

### CODE REVIEW

**Review by gadams3 — APPROVED** [review]
Looks reasonable to me. What was the crash?

**Review by AMZN-daimini — APPROVED** [review]

**Review by hultonha — APPROVED** [review]
Did this not turn out to be a lifetime issue then?

**Comment by AMZN-AlexOteiza** [comment]
> Did this not turn out to be a lifetime issue then?

It was very tangled but we resolved it by changing the UX

**Comment by AMZN-AlexOteiza** [comment]
> Looks reasonable to me. What was the crash?

https://github.com/o3de/o3de/issues/4190

**Pull request merged**
